-- v11_fuente_herramienta_estado.sql

-- 1) Columna ESTADO: 1 = activa, 0 = inactiva.
ALTER TABLE FUENTEHERRAMIENTA
  ADD FUENTEHERRAMIENTAESTADO NUMBER(1) DEFAULT 1 NOT NULL;

-- 2) Inactivar el catálogo legacy (preservadas como referencia histórica).
UPDATE FUENTEHERRAMIENTA SET FUENTEHERRAMIENTAESTADO = 0;

-- 3) Insertar las 10 herramientas oficiales (VBA MinTrabajo).
INSERT INTO FUENTEHERRAMIENTA (FUENTEHERRAMIENTAID, FUENTEHERRAMIENTANOMBRE, FUENTEHERRAMIENTAESTADO)
  VALUES (24, 'ENCUESTAS', 1);
INSERT INTO FUENTEHERRAMIENTA (FUENTEHERRAMIENTAID, FUENTEHERRAMIENTANOMBRE, FUENTEHERRAMIENTAESTADO)
  VALUES (25, 'ENTREVISTAS', 1);
INSERT INTO FUENTEHERRAMIENTA (FUENTEHERRAMIENTAID, FUENTEHERRAMIENTANOMBRE, FUENTEHERRAMIENTAESTADO)
  VALUES (26, 'GRUPOS FOCALES', 1);
INSERT INTO FUENTEHERRAMIENTA (FUENTEHERRAMIENTAID, FUENTEHERRAMIENTANOMBRE, FUENTEHERRAMIENTAESTADO)
  VALUES (27, 'ANÁLISIS DE EVALUACIONES DE DESEMPEÑO', 1);
INSERT INTO FUENTEHERRAMIENTA (FUENTEHERRAMIENTAID, FUENTEHERRAMIENTANOMBRE, FUENTEHERRAMIENTAESTADO)
  VALUES (28, 'REVISIÓN DE INDICADORES', 1);
INSERT INTO FUENTEHERRAMIENTA (FUENTEHERRAMIENTAID, FUENTEHERRAMIENTANOMBRE, FUENTEHERRAMIENTAESTADO)
  VALUES (29, 'ANÁLISIS INTERNO DE LA EMPRESA O GREMIO', 1);
INSERT INTO FUENTEHERRAMIENTA (FUENTEHERRAMIENTAID, FUENTEHERRAMIENTANOMBRE, FUENTEHERRAMIENTAESTADO)
  VALUES (30, 'DIAGNÓSTICOS SECTORIALES O TERRITORIALES', 1);
INSERT INTO FUENTEHERRAMIENTA (FUENTEHERRAMIENTAID, FUENTEHERRAMIENTANOMBRE, FUENTEHERRAMIENTAESTADO)
  VALUES (31, 'CAMBIOS TECNOLÓGICOS, NORMATIVOS O DE MERCADO', 1);
INSERT INTO FUENTEHERRAMIENTA (FUENTEHERRAMIENTAID, FUENTEHERRAMIENTANOMBRE, FUENTEHERRAMIENTAESTADO)
  VALUES (32, 'ESTRATEGIAS DE CRECIMIENTO, INNOVACIÓN O RECONVERSIÓN PRODUCTIVA', 1);
INSERT INTO FUENTEHERRAMIENTA (FUENTEHERRAMIENTAID, FUENTEHERRAMIENTANOMBRE, FUENTEHERRAMIENTAESTADO)
  VALUES (33, 'OTROS', 1);

COMMIT;
