-- v13_tipoambiente_normalizar.sql
-- ──────────────────────────────────────────────────────────────────────────
-- Normaliza el catálogo TIPOAMBIENTE para que coincida con el formulario
-- oficial del VBA del MinTrabajo (11 ítems en mayúsculas).
--
-- La columna TIPOAMBIENTEACTIVO ya existe (NUMBER(1), 1=activo, 0=inactivo).
-- Esta migración:
--   1) Cambia los nombres de los IDs 1..11 a mayúsculas según el VBA.
--   2) Inactiva los IDs 12..15 (combinaciones con AULA VIRTUAL que NO están
--      en el listado oficial del MinTrabajo).
--
-- Las AF que ya apuntan a esos IDs siguen funcionando — el dropdown del
-- formulario solo mostrará los 11 activos.
-- ──────────────────────────────────────────────────────────────────────────

-- 1) Renombrar IDs 1..11 a mayúsculas según VBA MinTrabajo.
UPDATE TIPOAMBIENTE SET TIPOAMBIENTENOMBRE = 'AULAS BÁSICAS (ESPACIOS FÍSICOS EN FINCAS Y TALLERES, INSTITUCIONES BÁSICA Y MEDIA, SALONES COMUNALES)' WHERE TIPOAMBIENTEID = 1;
UPDATE TIPOAMBIENTE SET TIPOAMBIENTENOMBRE = 'AULA CONVENCIONAL (INSTITUCIONES DE EDUCACIÓN SUPERIOR)' WHERE TIPOAMBIENTEID = 2;
UPDATE TIPOAMBIENTE SET TIPOAMBIENTENOMBRE = 'SALONES (HOTELES, LABORATORIOS, AULAS GASTRONOMÍA, SALONES EMPRESARIALES)' WHERE TIPOAMBIENTEID = 3;
UPDATE TIPOAMBIENTE SET TIPOAMBIENTENOMBRE = 'AUDITORIO' WHERE TIPOAMBIENTEID = 4;
UPDATE TIPOAMBIENTE SET TIPOAMBIENTENOMBRE = 'PLATAFORMA O HERRAMIENTA TECNOLÓGICA' WHERE TIPOAMBIENTEID = 5;
UPDATE TIPOAMBIENTE SET TIPOAMBIENTENOMBRE = 'AULA VIRTUAL' WHERE TIPOAMBIENTEID = 6;
UPDATE TIPOAMBIENTE SET TIPOAMBIENTENOMBRE = 'PUESTO DE TRABAJO REAL O SIMULADO' WHERE TIPOAMBIENTEID = 7;
UPDATE TIPOAMBIENTE SET TIPOAMBIENTENOMBRE = 'AUDITORIO - PLATAFORMA O HERRAMIENTA TECNOLÓGICA' WHERE TIPOAMBIENTEID = 8;
UPDATE TIPOAMBIENTE SET TIPOAMBIENTENOMBRE = 'AULA CONVENCIONAL - PLATAFORMA O HERRAMIENTA TECNOLÓGICA' WHERE TIPOAMBIENTEID = 9;
UPDATE TIPOAMBIENTE SET TIPOAMBIENTENOMBRE = 'AULA BÁSICA - PLATAFORMA O HERRAMIENTA TECNOLÓGICA' WHERE TIPOAMBIENTEID = 10;
UPDATE TIPOAMBIENTE SET TIPOAMBIENTENOMBRE = 'SALONES (HOTELES, LABORATORIOS, AULAS GASTRONOMÍA, SALONES EMPRESARIALES) - PLATAFORMA O HERRAMIENTA TECNOLOGICA' WHERE TIPOAMBIENTEID = 11;

-- 2) Inactivar IDs 12..15 (combinaciones con AULA VIRTUAL no presentes en VBA).
UPDATE TIPOAMBIENTE SET TIPOAMBIENTEACTIVO = 0 WHERE TIPOAMBIENTEID IN (12, 13, 14, 15);

-- 3) Asegurar que los IDs 1..11 sigan activos.
UPDATE TIPOAMBIENTE SET TIPOAMBIENTEACTIVO = 1 WHERE TIPOAMBIENTEID BETWEEN 1 AND 11;

COMMIT;
