-- v14_proyecto_versiones.sql

CREATE TABLE PROYECTOVERSION (
  PROYECTOVERSIONID    NUMBER          NOT NULL,
  PROYECTOID           NUMBER          NOT NULL,
  VERSIONNUMERO        NUMBER          NOT NULL,
  VERSIONCODIGO        VARCHAR2(60)    NOT NULL,
  VERSIONFECHA         TIMESTAMP       DEFAULT SYSDATE NOT NULL,
  VERSIONUSUARIO       VARCHAR2(200),
  VERSIONSNAPSHOT      CLOB            NOT NULL,
  VERSIONHASH          VARCHAR2(64),
  VERSIONESTADOAL      NUMBER          DEFAULT 1,
  VERSIONCOMENTARIO    VARCHAR2(2000),
  CONSTRAINT PK_PROYECTOVERSION PRIMARY KEY (PROYECTOVERSIONID),
  CONSTRAINT FK_PROYECTOVERSION_PROYECTO
    FOREIGN KEY (PROYECTOID) REFERENCES PROYECTO(PROYECTOID),
  CONSTRAINT UQ_PROYECTOVERSION_NUM
    UNIQUE (PROYECTOID, VERSIONNUMERO),
  CONSTRAINT UQ_PROYECTOVERSION_COD
    UNIQUE (VERSIONCODIGO)
);

CREATE INDEX IX_PROYECTOVERSION_PROY     ON PROYECTOVERSION (PROYECTOID);
CREATE INDEX IX_PROYECTOVERSION_FECHA    ON PROYECTOVERSION (VERSIONFECHA DESC);

CREATE SEQUENCE PROYECTOVERSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

COMMIT;
