-- v15_proyecto_version_final_anulada.sql

ALTER TABLE PROYECTOVERSION ADD (
  VERSIONESFINAL       NUMBER(1)    DEFAULT 0 NOT NULL,
  VERSIONANULADA       NUMBER(1)    DEFAULT 0 NOT NULL,
  VERSIONFINALFECHA    TIMESTAMP    NULL,
  VERSIONFINALUSUARIO  VARCHAR2(200) NULL,
  VERSIONANULADAFECHA  TIMESTAMP    NULL,
  VERSIONANULADAUSUARIO VARCHAR2(200) NULL
);

-- Una sola versión FINAL por proyecto.
CREATE UNIQUE INDEX UX_PROYECTOVERSION_FINAL
  ON PROYECTOVERSION (CASE WHEN VERSIONESFINAL = 1 THEN PROYECTOID ELSE NULL END);

-- Nota: VERSIONCODIGO ya tiene UNIQUE constraint desde v14, no se redefine.

COMMIT;
