-- v16_proyecto_aprobado.sql

CREATE TABLE PROYECTOAPROBADO (
  PROYECTOID            NUMBER          NOT NULL,
  PROYECTOVERSIONID     NUMBER          NOT NULL,
  VERSIONCODIGO         VARCHAR2(60)    NOT NULL,
  VERSIONHASH           VARCHAR2(64)    NOT NULL,
  FECHAAPROBACION       TIMESTAMP       DEFAULT SYSDATE NOT NULL,
  USUARIOAPROBO         VARCHAR2(200),
  COMENTARIOAPROBACION  VARCHAR2(2000),
  CONSTRAINT PK_PROYECTOAPROBADO PRIMARY KEY (PROYECTOID),
  CONSTRAINT FK_PROYECTOAPROBADO_PROY
    FOREIGN KEY (PROYECTOID)        REFERENCES PROYECTO(PROYECTOID),
  CONSTRAINT FK_PROYECTOAPROBADO_VER
    FOREIGN KEY (PROYECTOVERSIONID) REFERENCES PROYECTOVERSION(PROYECTOVERSIONID)
);

CREATE INDEX IX_PROYECTOAPROBADO_FECHA ON PROYECTOAPROBADO (FECHAAPROBACION DESC);

-- GRANTS y SINÓNIMOS — replicar el patrón de las demás tablas de SEPLOCAL

GRANT SELECT, INSERT, UPDATE, DELETE ON PROYECTOAPROBADO TO SEP_APP;
GRANT SELECT                         ON PROYECTOAPROBADO TO SEP_LECTOR;

CREATE OR REPLACE SYNONYM SEP_APP.PROYECTOAPROBADO    FOR SEPLOCAL.PROYECTOAPROBADO;
CREATE OR REPLACE SYNONYM SEP_LECTOR.PROYECTOAPROBADO FOR SEPLOCAL.PROYECTOAPROBADO;

COMMIT;
