-- v18_convocatoria_resultados_publicados.sql

ALTER TABLE CONVOCATORIA ADD (
  CONVOCATORIARESULTADOSPUBLICADOS NUMBER(1) DEFAULT 0 NOT NULL
);

UPDATE CONVOCATORIA c
   SET CONVOCATORIARESULTADOSPUBLICADOS = 1
 WHERE EXISTS (
   SELECT 1 FROM PROYECTO p
    WHERE p.CONVOCATORIAID = c.CONVOCATORIAID
      AND p.PROYECTOESTADO IN (3, 4)
 );

COMMIT;
