-- v20_banco_evaluadores.sql
-- ──────────────────────────────────────────────────────────────────────────
-- Banco de Evaluadores: 3 catálogos + 6 tablas principales.
--
-- Diseño basado en docs/evaluador/00-propuesta-modulo-evaluadores.md
--
--   1) Catálogos (gestionados desde el panel admin):
--        ROLEVALUADOR   - Roles que cumple un evaluador en cada evaluación
--                         (EVALUADOR, ANALISTA, COORDINADOR, etc.)
--        PROCESOEVAL    - Procesos de evaluación (FCE, FEEC, ...)
--        TIPOESTUDIO    - Tipos de estudio (HV, Pregrado, Posgrado, ...)
--
--   2) Banco:
--        EVALUADOR                    - Extensión 1:1 de PERSONA con datos
--                                       específicos del banco. La foto va
--                                       en BLOB en BD.
--        EVALUADORPARTICIPACION       - Historial por año/proceso (reemplaza
--                                       las 64 columnas repetidas del Excel).
--        EVALUADORESTUDIO             - HV, diplomas, certificados (PDF).
--        EVALUADOREXPERIENCIA         - Certificados laborales (PDF).
--        EVALUADORTIC                 - Formación TIC complementaria (PDF).
--        EVALUADORPRUEBACONOCIMIENTO  - Pruebas anuales por evaluador.
--
-- Notas:
--   - PERSONA, USUARIO, REGIONAL, CENTROFORMACION, CIUDAD y TIPOEVENTO ya
--     existen — el módulo se apalanca en ellas, no las duplica.
--   - El evaluador NO inicia sesión en el SEP en la fase inicial. La FK a
--     USUARIO queda prevista vía PERSONA por si más adelante se decide.
--   - MODALIDADPART se modela como VARCHAR2 ('PRESENCIAL', 'PAT', 'VIRTUAL')
--     hasta confirmar si existe una tabla MODALIDAD reutilizable.
--   - Tope de archivos sugerido: 8 MB por documento (validado a nivel
--     aplicación, no en BD).
-- ──────────────────────────────────────────────────────────────────────────


-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 1. CATÁLOGOS                                                            ║
-- ╚════════════════════════════════════════════════════════════════════════╝

-- ── ROLEVALUADOR ──────────────────────────────────────────────────────────
CREATE TABLE ROLEVALUADOR (
  ROLEVALUADORID      NUMBER         NOT NULL,
  ROLEVALUADORNOMBRE  VARCHAR2(80)   NOT NULL,
  ROLEVALUADORDESC    VARCHAR2(200)  NULL,
  ROLEVALUADORACTIVO  NUMBER(1)      DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ROLEVALUADOR PRIMARY KEY (ROLEVALUADORID),
  CONSTRAINT UQ_ROLEVALUADOR_NOMBRE UNIQUE (ROLEVALUADORNOMBRE)
);

CREATE SEQUENCE ROLEVALUADOR_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

INSERT INTO ROLEVALUADOR (ROLEVALUADORID, ROLEVALUADORNOMBRE) VALUES (ROLEVALUADOR_SEQ.NEXTVAL, 'EVALUADOR');
INSERT INTO ROLEVALUADOR (ROLEVALUADORID, ROLEVALUADORNOMBRE) VALUES (ROLEVALUADOR_SEQ.NEXTVAL, 'ANALISTA');
INSERT INTO ROLEVALUADOR (ROLEVALUADORID, ROLEVALUADORNOMBRE) VALUES (ROLEVALUADOR_SEQ.NEXTVAL, 'COORDINADOR');

-- ── PROCESOEVAL ───────────────────────────────────────────────────────────
CREATE TABLE PROCESOEVAL (
  PROCESOID      NUMBER         NOT NULL,
  PROCESONOMBRE  VARCHAR2(80)   NOT NULL,
  PROCESODESC    VARCHAR2(200)  NULL,
  PROCESOACTIVO  NUMBER(1)      DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PROCESOEVAL PRIMARY KEY (PROCESOID),
  CONSTRAINT UQ_PROCESOEVAL_NOMBRE UNIQUE (PROCESONOMBRE)
);

CREATE SEQUENCE PROCESOEVAL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

INSERT INTO PROCESOEVAL (PROCESOID, PROCESONOMBRE, PROCESODESC) VALUES (PROCESOEVAL_SEQ.NEXTVAL, 'FCE',  'Formación Continua Especializada');
INSERT INTO PROCESOEVAL (PROCESOID, PROCESONOMBRE, PROCESODESC) VALUES (PROCESOEVAL_SEQ.NEXTVAL, 'FEEC', 'Formación Especializada Empresa Campesina');

-- ── TIPOESTUDIO ───────────────────────────────────────────────────────────
CREATE TABLE TIPOESTUDIO (
  TIPOESTUDIOID      NUMBER         NOT NULL,
  TIPOESTUDIONOMBRE  VARCHAR2(80)   NOT NULL,
  TIPOESTUDIOACTIVO  NUMBER(1)      DEFAULT 1 NOT NULL,
  CONSTRAINT PK_TIPOESTUDIO PRIMARY KEY (TIPOESTUDIOID),
  CONSTRAINT UQ_TIPOESTUDIO_NOMBRE UNIQUE (TIPOESTUDIONOMBRE)
);

CREATE SEQUENCE TIPOESTUDIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

INSERT INTO TIPOESTUDIO (TIPOESTUDIOID, TIPOESTUDIONOMBRE) VALUES (TIPOESTUDIO_SEQ.NEXTVAL, 'HV');
INSERT INTO TIPOESTUDIO (TIPOESTUDIOID, TIPOESTUDIONOMBRE) VALUES (TIPOESTUDIO_SEQ.NEXTVAL, 'PREGRADO');
INSERT INTO TIPOESTUDIO (TIPOESTUDIOID, TIPOESTUDIONOMBRE) VALUES (TIPOESTUDIO_SEQ.NEXTVAL, 'POSGRADO');
INSERT INTO TIPOESTUDIO (TIPOESTUDIOID, TIPOESTUDIONOMBRE) VALUES (TIPOESTUDIO_SEQ.NEXTVAL, 'DIPLOMADO');
INSERT INTO TIPOESTUDIO (TIPOESTUDIOID, TIPOESTUDIONOMBRE) VALUES (TIPOESTUDIO_SEQ.NEXTVAL, 'CERTIFICADO');
INSERT INTO TIPOESTUDIO (TIPOESTUDIOID, TIPOESTUDIONOMBRE) VALUES (TIPOESTUDIO_SEQ.NEXTVAL, 'OTRO');


-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 2. EVALUADOR — extensión 1:1 de PERSONA                                 ║
-- ╚════════════════════════════════════════════════════════════════════════╝

CREATE TABLE EVALUADOR (
  EVALUADORID            NUMBER         NOT NULL,
  PERSONAID              NUMBER         NOT NULL,
  CENTROID               NUMBER         NULL,
  REGIONALID             NUMBER         NULL,
  EVALUADORCARGO         VARCHAR2(120)  NULL,
  EVALUADORPROFESION     VARCHAR2(200)  NULL,
  EVALUADORPOSGRADO      VARCHAR2(400)  NULL,
  EVALUADOROTROSEST      CLOB           NULL,
  EVALUADORJEFEDIR       VARCHAR2(200)  NULL,
  EVALUADORQUIENAPRUEBA  VARCHAR2(200)  NULL,
  EVALUADORFOTO          BLOB           NULL,
  EVALUADORFOTOMIME      VARCHAR2(40)   NULL,
  EVALUADORACTIVO        NUMBER(1)      DEFAULT 1       NOT NULL,
  FECHACREACION          TIMESTAMP      DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_EVALUADOR PRIMARY KEY (EVALUADORID),
  CONSTRAINT UQ_EVALUADOR_PERSONA UNIQUE (PERSONAID),
  CONSTRAINT FK_EVALUADOR_PERSONA
    FOREIGN KEY (PERSONAID) REFERENCES PERSONA(PERSONAID)
);

CREATE INDEX IX_EVALUADOR_ACTIVO ON EVALUADOR (EVALUADORACTIVO, EVALUADORID);

CREATE SEQUENCE EVALUADOR_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 3. EVALUADORPARTICIPACION — historial por año/proceso (1:N)             ║
-- ╚════════════════════════════════════════════════════════════════════════╝

CREATE TABLE EVALUADORPARTICIPACION (
  PARTICIPACIONID        NUMBER         NOT NULL,
  EVALUADORID            NUMBER         NOT NULL,
  ANIO                   NUMBER(4)      NOT NULL,
  PERIODO                CHAR(2)        NULL,
  ROLEVALUADORID         NUMBER         NULL,
  MODALIDADPART          VARCHAR2(20)   NULL,
  PROCESOID              NUMBER         NULL,
  PROCESOREVOCADO        NUMBER(1)      DEFAULT 0 NOT NULL,
  PROYECTOSEVALUADOS     CLOB           NULL,
  MESA                   VARCHAR2(120)  NULL,
  EQUIPOEVALUADOR        VARCHAR2(120)  NULL,
  DINAMIZADORPERSONAID   NUMBER         NULL,
  RETROALIMENTACION      CLOB           NULL,
  OBSERVACIONES          CLOB           NULL,
  CONSTRAINT PK_EVALUADORPARTICIPACION PRIMARY KEY (PARTICIPACIONID),
  CONSTRAINT FK_PART_EVALUADOR
    FOREIGN KEY (EVALUADORID) REFERENCES EVALUADOR(EVALUADORID),
  CONSTRAINT FK_PART_ROL
    FOREIGN KEY (ROLEVALUADORID) REFERENCES ROLEVALUADOR(ROLEVALUADORID),
  CONSTRAINT FK_PART_PROCESO
    FOREIGN KEY (PROCESOID) REFERENCES PROCESOEVAL(PROCESOID),
  CONSTRAINT FK_PART_DINAMIZADOR
    FOREIGN KEY (DINAMIZADORPERSONAID) REFERENCES PERSONA(PERSONAID)
);

CREATE INDEX IX_PART_EVAL_ANIO ON EVALUADORPARTICIPACION (EVALUADORID, ANIO DESC);

CREATE SEQUENCE EVALUADORPARTICIPACION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 4. EVALUADORESTUDIO — HV, diplomas y certificados académicos            ║
-- ╚════════════════════════════════════════════════════════════════════════╝

CREATE TABLE EVALUADORESTUDIO (
  ESTUDIOID         NUMBER         NOT NULL,
  EVALUADORID       NUMBER         NOT NULL,
  TIPOESTUDIOID     NUMBER         NOT NULL,
  ESTUDIOTITULO     VARCHAR2(200)  NULL,
  INSTITUCION       VARCHAR2(200)  NULL,
  FECHAGRADO        DATE           NULL,
  ARCHIVOPDF        BLOB           NULL,
  ARCHIVOMIME       VARCHAR2(40)   NULL,
  ARCHIVONOMBRE     VARCHAR2(200)  NULL,
  FECHACARGUE       TIMESTAMP      DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_EVALUADORESTUDIO PRIMARY KEY (ESTUDIOID),
  CONSTRAINT FK_ESTUDIO_EVALUADOR
    FOREIGN KEY (EVALUADORID) REFERENCES EVALUADOR(EVALUADORID),
  CONSTRAINT FK_ESTUDIO_TIPO
    FOREIGN KEY (TIPOESTUDIOID) REFERENCES TIPOESTUDIO(TIPOESTUDIOID)
);

CREATE INDEX IX_ESTUDIO_EVAL ON EVALUADORESTUDIO (EVALUADORID);

CREATE SEQUENCE EVALUADORESTUDIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 5. EVALUADOREXPERIENCIA — certificados laborales                        ║
-- ╚════════════════════════════════════════════════════════════════════════╝

CREATE TABLE EVALUADOREXPERIENCIA (
  EXPERIENCIAID    NUMBER         NOT NULL,
  EVALUADORID      NUMBER         NOT NULL,
  CARGOEXP         VARCHAR2(200)  NULL,
  ENTIDADEXP       VARCHAR2(200)  NULL,
  FECHAINICIO      DATE           NULL,
  FECHAFIN         DATE           NULL,
  ARCHIVOPDF       BLOB           NULL,
  ARCHIVOMIME      VARCHAR2(40)   NULL,
  ARCHIVONOMBRE    VARCHAR2(200)  NULL,
  CONSTRAINT PK_EVALUADOREXPERIENCIA PRIMARY KEY (EXPERIENCIAID),
  CONSTRAINT FK_EXP_EVALUADOR
    FOREIGN KEY (EVALUADORID) REFERENCES EVALUADOR(EVALUADORID)
);

CREATE INDEX IX_EXP_EVAL ON EVALUADOREXPERIENCIA (EVALUADORID);

CREATE SEQUENCE EVALUADOREXPERIENCIA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 6. EVALUADORTIC — formación TIC complementaria                          ║
-- ╚════════════════════════════════════════════════════════════════════════╝

CREATE TABLE EVALUADORTIC (
  TICID            NUMBER         NOT NULL,
  EVALUADORID      NUMBER         NOT NULL,
  TIPOEVENTOID     NUMBER         NULL,
  TICNOMBRE        VARCHAR2(200)  NOT NULL,
  TICHORAS         NUMBER         NULL,
  FECHAFIN         DATE           NULL,
  ARCHIVOPDF       BLOB           NULL,
  ARCHIVOMIME      VARCHAR2(40)   NULL,
  ARCHIVONOMBRE    VARCHAR2(200)  NULL,
  CONSTRAINT PK_EVALUADORTIC PRIMARY KEY (TICID),
  CONSTRAINT FK_TIC_EVALUADOR
    FOREIGN KEY (EVALUADORID) REFERENCES EVALUADOR(EVALUADORID)
);

CREATE INDEX IX_TIC_EVAL ON EVALUADORTIC (EVALUADORID);

CREATE SEQUENCE EVALUADORTIC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 7. EVALUADORPRUEBACONOCIMIENTO — pruebas anuales                        ║
-- ╚════════════════════════════════════════════════════════════════════════╝

CREATE TABLE EVALUADORPRUEBA (
  PRUEBAID            NUMBER         NOT NULL,
  EVALUADORID         NUMBER         NOT NULL,
  ANIO                NUMBER(4)      NOT NULL,
  PERIODO             CHAR(2)        NULL,
  FECHAPRESENTACION   DATE           NULL,
  HORARIO             VARCHAR2(40)   NULL,
  INTENTOS            NUMBER         NULL,
  PUNTAJEMAYOR        NUMBER(5,2)    NULL,
  PRUEBANUMERO        NUMBER         NULL,
  EFECTIVIDAD         NUMBER(5,2)    NULL,
  CORRECTAS           NUMBER         NULL,
  INCORRECTAS         NUMBER         NULL,
  TOTALTIEMPO         VARCHAR2(40)   NULL,
  OBSERVACION         VARCHAR2(400)  NULL,
  CONSTRAINT PK_EVALUADORPRUEBA PRIMARY KEY (PRUEBAID),
  CONSTRAINT FK_PRUEBA_EVALUADOR
    FOREIGN KEY (EVALUADORID) REFERENCES EVALUADOR(EVALUADORID)
);

CREATE INDEX IX_PRUEBA_EVAL_ANIO ON EVALUADORPRUEBA (EVALUADORID, ANIO DESC);

CREATE SEQUENCE EVALUADORPRUEBA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;


-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 8. GRANTS y SINÓNIMOS                                                   ║
-- ╚════════════════════════════════════════════════════════════════════════╝

-- ── Catálogos ─────────────────────────────────────────────────────────────
GRANT SELECT, INSERT, UPDATE, DELETE ON ROLEVALUADOR     TO SEP_APP;
GRANT SELECT                         ON ROLEVALUADOR     TO SEP_LECTOR;
GRANT SELECT                         ON ROLEVALUADOR_SEQ TO SEP_APP;

GRANT SELECT, INSERT, UPDATE, DELETE ON PROCESOEVAL      TO SEP_APP;
GRANT SELECT                         ON PROCESOEVAL      TO SEP_LECTOR;
GRANT SELECT                         ON PROCESOEVAL_SEQ  TO SEP_APP;

GRANT SELECT, INSERT, UPDATE, DELETE ON TIPOESTUDIO      TO SEP_APP;
GRANT SELECT                         ON TIPOESTUDIO      TO SEP_LECTOR;
GRANT SELECT                         ON TIPOESTUDIO_SEQ  TO SEP_APP;

-- ── Banco ─────────────────────────────────────────────────────────────────
GRANT SELECT, INSERT, UPDATE, DELETE ON EVALUADOR        TO SEP_APP;
GRANT SELECT                         ON EVALUADOR        TO SEP_LECTOR;
GRANT SELECT                         ON EVALUADOR_SEQ    TO SEP_APP;

GRANT SELECT, INSERT, UPDATE, DELETE ON EVALUADORPARTICIPACION     TO SEP_APP;
GRANT SELECT                         ON EVALUADORPARTICIPACION     TO SEP_LECTOR;
GRANT SELECT                         ON EVALUADORPARTICIPACION_SEQ TO SEP_APP;

GRANT SELECT, INSERT, UPDATE, DELETE ON EVALUADORESTUDIO      TO SEP_APP;
GRANT SELECT                         ON EVALUADORESTUDIO      TO SEP_LECTOR;
GRANT SELECT                         ON EVALUADORESTUDIO_SEQ  TO SEP_APP;

GRANT SELECT, INSERT, UPDATE, DELETE ON EVALUADOREXPERIENCIA     TO SEP_APP;
GRANT SELECT                         ON EVALUADOREXPERIENCIA     TO SEP_LECTOR;
GRANT SELECT                         ON EVALUADOREXPERIENCIA_SEQ TO SEP_APP;

GRANT SELECT, INSERT, UPDATE, DELETE ON EVALUADORTIC      TO SEP_APP;
GRANT SELECT                         ON EVALUADORTIC      TO SEP_LECTOR;
GRANT SELECT                         ON EVALUADORTIC_SEQ  TO SEP_APP;

GRANT SELECT, INSERT, UPDATE, DELETE ON EVALUADORPRUEBA      TO SEP_APP;
GRANT SELECT                         ON EVALUADORPRUEBA      TO SEP_LECTOR;
GRANT SELECT                         ON EVALUADORPRUEBA_SEQ  TO SEP_APP;

-- ── Sinónimos para SEP_APP ────────────────────────────────────────────────
CREATE OR REPLACE SYNONYM SEP_APP.ROLEVALUADOR              FOR SEPLOCAL.ROLEVALUADOR;
CREATE OR REPLACE SYNONYM SEP_APP.ROLEVALUADOR_SEQ          FOR SEPLOCAL.ROLEVALUADOR_SEQ;
CREATE OR REPLACE SYNONYM SEP_APP.PROCESOEVAL               FOR SEPLOCAL.PROCESOEVAL;
CREATE OR REPLACE SYNONYM SEP_APP.PROCESOEVAL_SEQ           FOR SEPLOCAL.PROCESOEVAL_SEQ;
CREATE OR REPLACE SYNONYM SEP_APP.TIPOESTUDIO               FOR SEPLOCAL.TIPOESTUDIO;
CREATE OR REPLACE SYNONYM SEP_APP.TIPOESTUDIO_SEQ           FOR SEPLOCAL.TIPOESTUDIO_SEQ;

CREATE OR REPLACE SYNONYM SEP_APP.EVALUADOR                 FOR SEPLOCAL.EVALUADOR;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADOR_SEQ             FOR SEPLOCAL.EVALUADOR_SEQ;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORPARTICIPACION    FOR SEPLOCAL.EVALUADORPARTICIPACION;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORPARTICIPACION_SEQ FOR SEPLOCAL.EVALUADORPARTICIPACION_SEQ;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORESTUDIO          FOR SEPLOCAL.EVALUADORESTUDIO;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORESTUDIO_SEQ      FOR SEPLOCAL.EVALUADORESTUDIO_SEQ;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADOREXPERIENCIA      FOR SEPLOCAL.EVALUADOREXPERIENCIA;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADOREXPERIENCIA_SEQ  FOR SEPLOCAL.EVALUADOREXPERIENCIA_SEQ;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORTIC              FOR SEPLOCAL.EVALUADORTIC;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORTIC_SEQ          FOR SEPLOCAL.EVALUADORTIC_SEQ;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORPRUEBA           FOR SEPLOCAL.EVALUADORPRUEBA;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORPRUEBA_SEQ       FOR SEPLOCAL.EVALUADORPRUEBA_SEQ;

-- ── Sinónimos para SEP_LECTOR ─────────────────────────────────────────────
CREATE OR REPLACE SYNONYM SEP_LECTOR.ROLEVALUADOR              FOR SEPLOCAL.ROLEVALUADOR;
CREATE OR REPLACE SYNONYM SEP_LECTOR.ROLEVALUADOR_SEQ          FOR SEPLOCAL.ROLEVALUADOR_SEQ;
CREATE OR REPLACE SYNONYM SEP_LECTOR.PROCESOEVAL               FOR SEPLOCAL.PROCESOEVAL;
CREATE OR REPLACE SYNONYM SEP_LECTOR.PROCESOEVAL_SEQ           FOR SEPLOCAL.PROCESOEVAL_SEQ;
CREATE OR REPLACE SYNONYM SEP_LECTOR.TIPOESTUDIO               FOR SEPLOCAL.TIPOESTUDIO;
CREATE OR REPLACE SYNONYM SEP_LECTOR.TIPOESTUDIO_SEQ           FOR SEPLOCAL.TIPOESTUDIO_SEQ;

CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADOR                 FOR SEPLOCAL.EVALUADOR;
CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADOR_SEQ             FOR SEPLOCAL.EVALUADOR_SEQ;
CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADORPARTICIPACION    FOR SEPLOCAL.EVALUADORPARTICIPACION;
CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADORPARTICIPACION_SEQ FOR SEPLOCAL.EVALUADORPARTICIPACION_SEQ;
CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADORESTUDIO          FOR SEPLOCAL.EVALUADORESTUDIO;
CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADORESTUDIO_SEQ      FOR SEPLOCAL.EVALUADORESTUDIO_SEQ;
CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADOREXPERIENCIA      FOR SEPLOCAL.EVALUADOREXPERIENCIA;
CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADOREXPERIENCIA_SEQ  FOR SEPLOCAL.EVALUADOREXPERIENCIA_SEQ;
CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADORTIC              FOR SEPLOCAL.EVALUADORTIC;
CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADORTIC_SEQ          FOR SEPLOCAL.EVALUADORTIC_SEQ;
CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADORPRUEBA           FOR SEPLOCAL.EVALUADORPRUEBA;
CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADORPRUEBA_SEQ       FOR SEPLOCAL.EVALUADORPRUEBA_SEQ;

COMMIT;
