-- v22_evaluador_documento_generico.sql

-- 1. TIPODOCUMENTOEVAL — catálogo de tipos de documento

CREATE TABLE TIPODOCUMENTOEVAL (
  TIPODOCUMENTOEVALID  NUMBER(10)     NOT NULL,
  CODIGO               NVARCHAR2(40)  NOT NULL,
  NOMBRE               NVARCHAR2(120) NOT NULL,
  ADMITEMULTIPLE       NUMBER(1)      DEFAULT 1   NOT NULL,
  ORDEN                NUMBER(3)      DEFAULT 100 NOT NULL,
  ACTIVO               NUMBER(1)      DEFAULT 1   NOT NULL,
  CONSTRAINT PK_TIPODOCEVAL PRIMARY KEY (TIPODOCUMENTOEVALID),
  CONSTRAINT UQ_TIPODOCEVAL_CODIGO UNIQUE (CODIGO)
);

COMMENT ON COLUMN TIPODOCUMENTOEVAL.CODIGO IS
  'Código estable (ej. CEDULA, AUTORIZACION, CONFIDENCIALIDAD) usado por el backend.';
COMMENT ON COLUMN TIPODOCUMENTOEVAL.ADMITEMULTIPLE IS
  '1 = varios documentos por evaluador; 0 = uno único (se reemplaza al subir).';
COMMENT ON COLUMN TIPODOCUMENTOEVAL.ORDEN IS
  'Orden de visualización en el listado del evaluador (menor primero).';

-- 2. EVALUADORDOCUMENTO — PDF por evaluador

CREATE TABLE EVALUADORDOCUMENTO (
  DOCUMENTOID           NUMBER(10)     NOT NULL,
  EVALUADORID           NUMBER(10)     NOT NULL,
  TIPODOCUMENTOEVALID   NUMBER(10)     NOT NULL,
  DOCUMENTODESCRIPCION  NVARCHAR2(300) NULL,
  ANIOREFERENCIA        NUMBER(4)      NULL,
  ARCHIVOPDF            BLOB           NOT NULL,
  ARCHIVOMIME           NVARCHAR2(120) NOT NULL,
  ARCHIVONOMBRE         NVARCHAR2(255) NULL,
  FECHACARGUE           DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_EVALUADORDOCUMENTO PRIMARY KEY (DOCUMENTOID),
  CONSTRAINT FK_EVALDOC_EVAL FOREIGN KEY (EVALUADORID)
    REFERENCES EVALUADOR(EVALUADORID),
  CONSTRAINT FK_EVALDOC_TIPO FOREIGN KEY (TIPODOCUMENTOEVALID)
    REFERENCES TIPODOCUMENTOEVAL(TIPODOCUMENTOEVALID)
);

CREATE INDEX IX_EVALDOC_EVAL ON EVALUADORDOCUMENTO (EVALUADORID);
CREATE INDEX IX_EVALDOC_TIPO ON EVALUADORDOCUMENTO (TIPODOCUMENTOEVALID);

-- 3. SEED — solo CEDULA en Fase 1

-- El resto de tipos (autorización tratamiento datos, confidencialidad,
INSERT INTO TIPODOCUMENTOEVAL
  (TIPODOCUMENTOEVALID, CODIGO, NOMBRE, ADMITEMULTIPLE, ORDEN)
  VALUES (1, N'CEDULA', N'Documento de identificación', 0, 10);

-- 4. GRANTS y SINÓNIMOS

GRANT SELECT, INSERT, UPDATE, DELETE ON TIPODOCUMENTOEVAL  TO SEP_APP;
GRANT SELECT                         ON TIPODOCUMENTOEVAL  TO SEP_LECTOR;

GRANT SELECT, INSERT, UPDATE, DELETE ON EVALUADORDOCUMENTO TO SEP_APP;
GRANT SELECT                         ON EVALUADORDOCUMENTO TO SEP_LECTOR;

CREATE OR REPLACE SYNONYM SEP_APP.TIPODOCUMENTOEVAL     FOR SEPLOCAL.TIPODOCUMENTOEVAL;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORDOCUMENTO    FOR SEPLOCAL.EVALUADORDOCUMENTO;

CREATE OR REPLACE SYNONYM SEP_LECTOR.TIPODOCUMENTOEVAL  FOR SEPLOCAL.TIPODOCUMENTOEVAL;
CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADORDOCUMENTO FOR SEPLOCAL.EVALUADORDOCUMENTO;

COMMIT;
