-- v23_evaluador_documento_tipos_extra.sql

-- Seed idempotente de tipos de documento (Fase 2)

INSERT INTO TIPODOCUMENTOEVAL (TIPODOCUMENTOEVALID, CODIGO, NOMBRE, ADMITEMULTIPLE, ORDEN)
  SELECT 2, N'AUTORIZACION', N'Correo de autorización', 1, 20 FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM TIPODOCUMENTOEVAL WHERE CODIGO = N'AUTORIZACION');

INSERT INTO TIPODOCUMENTOEVAL (TIPODOCUMENTOEVALID, CODIGO, NOMBRE, ADMITEMULTIPLE, ORDEN)
  SELECT 3, N'CONFIDENCIALIDAD', N'Acuerdo de confidencialidad', 1, 30 FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM TIPODOCUMENTOEVAL WHERE CODIGO = N'CONFIDENCIALIDAD');

INSERT INTO TIPODOCUMENTOEVAL (TIPODOCUMENTOEVALID, CODIGO, NOMBRE, ADMITEMULTIPLE, ORDEN)
  SELECT 4, N'EXPERIENCIA_PROFESIONAL', N'Experiencia laboral profesional', 1, 40 FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM TIPODOCUMENTOEVAL WHERE CODIGO = N'EXPERIENCIA_PROFESIONAL');

INSERT INTO TIPODOCUMENTOEVAL (TIPODOCUMENTOEVALID, CODIGO, NOMBRE, ADMITEMULTIPLE, ORDEN)
  SELECT 5, N'EXPERIENCIA_PROYECTOS', N'Experiencia laboral en proyectos', 1, 50 FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM TIPODOCUMENTOEVAL WHERE CODIGO = N'EXPERIENCIA_PROYECTOS');

INSERT INTO TIPODOCUMENTOEVAL (TIPODOCUMENTOEVALID, CODIGO, NOMBRE, ADMITEMULTIPLE, ORDEN)
  SELECT 6, N'CERTIFICADO_PARTICIPACION', N'Certificado de participación en evaluación', 1, 60 FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM TIPODOCUMENTOEVAL WHERE CODIGO = N'CERTIFICADO_PARTICIPACION');

COMMIT;
