-- v24_regional_centroformacion.sql
-- Regionales y Centros de Formación del SENA (fuente: directorio oficial 436_2.pdf).
-- Idempotente: usa q-strings + EXCEPTION para ORA-00955/01408 (ya existe).
-- Ejecutar como SEPLOCAL en SQL Developer.

-- Tabla REGIONAL ─────────────────────────────────────────────────────
BEGIN
  EXECUTE IMMEDIATE q'[CREATE TABLE REGIONAL (
    REGIONALID       NUMBER(10)     NOT NULL,
    REGIONALNOMBRE   NVARCHAR2(120) NOT NULL,
    REGIONALACTIVO   NUMBER(1)      DEFAULT 1 NOT NULL,
    CONSTRAINT PK_REGIONAL PRIMARY KEY (REGIONALID)
  )]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Tabla CENTROFORMACION ──────────────────────────────────────────────
BEGIN
  EXECUTE IMMEDIATE q'[CREATE TABLE CENTROFORMACION (
    CENTROID         NUMBER(10)     NOT NULL,
    REGIONALID       NUMBER(10)     NOT NULL,
    CENTRONOMBRE     NVARCHAR2(300) NOT NULL,
    CIUDADID         NUMBER(22),
    CENTROACTIVO     NUMBER(1)      DEFAULT 1 NOT NULL,
    CONSTRAINT PK_CENTROFORMACION PRIMARY KEY (CENTROID),
    CONSTRAINT FK_CF_REGIONAL FOREIGN KEY (REGIONALID) REFERENCES REGIONAL(REGIONALID),
    CONSTRAINT FK_CF_CIUDAD   FOREIGN KEY (CIUDADID)   REFERENCES CIUDAD(CIUDADID)
  )]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Índices (ORA-01408 = ya está indexada, ORA-00955 = índice ya existe) ─
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_CF_REGIONAL ON CENTROFORMACION (REGIONALID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 AND SQLCODE != -1408 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_CF_CIUDAD ON CENTROFORMACION (CIUDADID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 AND SQLCODE != -1408 THEN RAISE; END IF;
END;
/

-- Regionales ─────────────────────────────────────────────────────────
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 1, N'Dirección General' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 1);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 5, N'Antioquia' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 5);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 8, N'Atlántico' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 8);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 11, N'Distrito Capital' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 11);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 13, N'Bolívar' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 13);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 15, N'Boyacá' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 15);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 17, N'Caldas' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 17);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 18, N'Caquetá' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 18);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 19, N'Cauca' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 19);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 20, N'Cesar' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 20);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 23, N'Córdoba' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 23);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 25, N'Cundinamarca' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 25);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 27, N'Chocó' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 27);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 41, N'Huila' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 41);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 44, N'Guajira' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 44);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 47, N'Magdalena' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 47);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 50, N'Meta' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 50);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 52, N'Nariño' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 52);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 54, N'Norte de Santander' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 54);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 63, N'Quindío' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 63);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 66, N'Risaralda' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 66);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 68, N'Santander' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 68);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 70, N'Sucre' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 70);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 73, N'Tolima' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 73);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 76, N'Valle del Cauca' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 76);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 81, N'Arauca' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 81);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 85, N'Casanare' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 85);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 86, N'Putumayo' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 86);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 88, N'San Andrés' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 88);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 91, N'Amazonas' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 91);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 94, N'Guainía' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 94);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 95, N'Guaviare' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 95);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 97, N'Vaupés' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 97);
INSERT INTO REGIONAL (REGIONALID, REGIONALNOMBRE) SELECT 99, N'Vichada' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM REGIONAL WHERE REGIONALID = 99);

-- Centros de formación ───────────────────────────────────────────────
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 1001, 1, N'Dirección General', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 1001);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9301, 5, N'Centro de Comercio', 5001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9301);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9401, 5, N'Centro de Servicios de Salud', 5001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9401);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9402, 5, N'Centro de Servicios y Gestión Empresarial', 5001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9402);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9101, 5, N'Centro de los Recursos Naturales Renovables - la Salada', 5129 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9101);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9201, 5, N'Centro del Diseño y Manufactura de Cuero', 5360 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9201);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9202, 5, N'Centro de Formación En Diseño, Confección y Moda', 5360 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9202);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9205, 5, N'Centro Tecnológico del Mobiliario', 5360 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9205);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9203, 5, N'Centro Para El Desarrollo del Hábitat y la Construcción', 5001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9203);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9204, 5, N'Centro de Tecnología de la Manufactura Avanzada', 5001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9204);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9206, 5, N'Tecnológico de Gestión Industrial', 5001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9206);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9501, 5, N'Complejo Tecnológico Para la Gestión Agroempresarial', 5154 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9501);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9502, 5, N'Complejo Tecnológico Minero Agroempresarial', 5579 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9502);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9503, 5, N'Centro de la Innovación, la Agroindustria y El Turismo', 5615 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9503);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9504, 5, N'Complejo Tecnológico Agroindustrial, Pecuario y Turístico', 5045 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9504);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9103, 8, N'Centro Para El Desarrollo Agroecológico y Agroindustrial', 8001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9103);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9302, 8, N'Centro de Comercio y Servicios', 8001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9302);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9207, 8, N'Centro Nacional Colombo Alemán', 8001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9207);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9208, 8, N'Centro Industrial y de Aviación', 8001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9208);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9405, 11, N'Centro de Servicios Financieros', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9405);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9209, 11, N'Centro de Tecnologías Para la Construcción y la Madera', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9209);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9210, 11, N'Centro de Electricidad, Electrónica y Telecomunicaciones', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9210);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9212, 11, N'Centro de Manufactura En Textiles y Cuero', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9212);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9214, 11, N'Centro Metalmecánico', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9214);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9215, 11, N'Centro de Materiales y Ensayos', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9215);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9211, 11, N'Centro de Gestión Industrial', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9211);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9216, 11, N'Centro de Diseño y Metrología', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9216);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9217, 11, N'Centro Para la Industria de la Comunicación Gráfica', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9217);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9406, 11, N'Centro Nacional de Hotelería, Turismo y Alimentos', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9406);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9403, 11, N'Centro de Formación de Talento Humano En Salud', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9403);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9404, 11, N'Centro de Gestión Administrativa', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9404);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9508, 11, N'Centro de Gestión y Fortalecimiento Socio Empresarial', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9508);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9303, 11, N'Centro de Gestión de Mercados, Logística y Tecnologías de la Información', 11001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9303);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9104, 13, N'Centro Agroempresarial y Minero', 13001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9104);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9304, 13, N'Centro de Comercio y Servicios', 13001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9304);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9105, 13, N'Centro Náutico Internacional, Fluvial y Portuario', 13001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9105);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9218, 13, N'Centro Para la Industria Petroquímica', 13001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9218);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9514, 15, N'Centro Industrial de Mantenimiento y Manufactura', 15759 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9514);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9110, 15, N'Centro de Desarrollo Agropecuario y Agroindustrial', 15238 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9110);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9111, 15, N'Centro Minero', 15759 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9111);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9305, 15, N'Centro de Gestión Administrativa y Fortalecimiento Empresarial', 15001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9305);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9112, 17, N'Centro Para la Formación Cafetera', 17001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9112);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9219, 17, N'Centro de Automatización Industrial', 17001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9219);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9220, 17, N'Centro de Procesos Industriales', 17001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9220);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9306, 17, N'Centro de Comercio y Servicios', 17001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9306);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9515, 17, N'Centro Pecuario y Agroempresarial', 17380 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9515);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9516, 18, N'Centro Tecnológico de la Amazonía', 18001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9516);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9113, 19, N'Centro Agropecuario', 19001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9113);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9221, 19, N'Centro de Teleinformática y Producción Industrial', 19001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9221);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9307, 19, N'Centro de Comercio y Servicios', 19001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9307);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9521, 20, N'Centro de Operación y Mantenimiento Minero', 20001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9521);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9114, 20, N'Centro Biotecnológico del Caribe', 20001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9114);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9520, 20, N'Centro Agroempresarial', 20011 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9520);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9523, 23, N'Centro de Comercio, Industria y Turismo de Córdoba', 23001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9523);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9115, 23, N'Centro Agropecuario y de Biotecnología El Porvenir', 23189 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9115);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9509, 25, N'Centro de Desarrollo Agroindustrial y Empresarial', 25875 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9509);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9510, 25, N'Centro Agroecológico y Empresarial', 25290 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9510);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9511, 25, N'Centro de la Tecnología del Diseño y la Productividad Empresarial', 25307 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9511);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9512, 25, N'Centro de Biotecnología Agropecuaria', 25473 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9512);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9232, 25, N'Centro Industrial y Desarrollo Empresarial de Soacha', 25754 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9232);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9513, 25, N'Centro de Desarrollo Agroempresarial', 25175 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9513);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9522, 27, N'Centro de Recursos Naturales, Industria y Biodiversidad', 27001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9522);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9527, 41, N'Centro de la Industria, la Empresa y los Servicios', 41001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9527);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9116, 41, N'Centro de Formación Agroindustrial', 41132 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9116);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9525, 41, N'Centro Agroempresarial y Desarrollo Pecuario del Huila', 41298 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9525);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9526, 41, N'Centro de Desarrollo Agroempresarial y Turístico del Huila', 41396 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9526);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9528, 41, N'Centro de Gestión y Desarrollo Sostenible Surcolombiano', 41551 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9528);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9222, 44, N'Centro Industrial y de Energías Alternativas', 44001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9222);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9524, 44, N'Centro Agroempresarial y Acuícola', 44279 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9524);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9529, 47, N'Centro de Logística y Promoción Ecoturística del Magdalena', 47001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9529);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9118, 47, N'Centro Acuícola y Agroindustrial de Gaira', 47001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9118);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9532, 50, N'Centro de Industria y Servicios del Meta', 50001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9532);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9117, 50, N'Centro Agroindustrial del Meta', 50573 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9117);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9536, 52, N'Centro Internacional de Producción Limpia - Lope', 52001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9536);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9534, 52, N'Centro Sur Colombiano de Logística Internacional', 52356 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9534);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9535, 52, N'Centro Agroindustrial y Pesquero de la Costa Pacífica', 52835 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9535);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9119, 54, N'Centro Atención Sector Agropecuario', 54001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9119);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9537, 54, N'Centro de la Industria, la Empresa y los Servicios', 54001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9537);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9538, 63, N'Centro de Comercio, Industria y Turismo', 63001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9538);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9120, 63, N'Centro Agroindustrial', 63001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9120);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9231, 63, N'Centro Para El Desarrollo Tecnológico de la Construcción', 63001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9231);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9121, 66, N'Centro Atención Sector Agropecuario', 66001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9121);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9308, 66, N'Centro de Comercio y Servicios', 66001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9308);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9223, 66, N'Centro de Diseño e Innovación Tecnológica Industrial', 66170 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9223);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9309, 68, N'Centro de Servicios Empresariales y Turísticos', 68001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9309);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9122, 68, N'Centro Atención Sector Agropecuario', 68547 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9122);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9224, 68, N'Centro Industrial de Mantenimiento Integral', 68307 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9224);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9225, 68, N'Centro Industrial del Diseño y la Manufactura', 68276 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9225);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9540, 68, N'Centro Industrial y del Desarrollo Tecnológico', 68081 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9540);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9541, 68, N'Centro Agroturístico', 68679 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9541);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9545, 68, N'Centro Agroempresarial y Turístico de los Andes', 68432 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9545);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9546, 68, N'Centro de Gestión Agroempresarial del Oriente', 68861 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9546);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9542, 70, N'Centro de la Innovación, la Tecnología y los Servicios', 70001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9542);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9226, 73, N'Centro de Industria y Construcción', 73001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9226);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9310, 73, N'Centro de Comercio y Servicios', 73001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9310);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9123, 73, N'Centro Agropecuario la Granja', 73268 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9123);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9227, 76, N'Centro de Electricidad y Automatización Industrial - Ceai', 76001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9227);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9229, 76, N'Centro de Diseño Tecnológico Industrial', 76001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9229);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9230, 76, N'Centro Nacional de Asistencia Técnica A la Industria - Astin', 76001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9230);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9311, 76, N'Centro de Gestión Tecnológica de Servicios', 76001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9311);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9124, 76, N'Centro Agropecuario de Buga', 76111 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9124);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9126, 76, N'Centro Náutico Pesquero de Buenaventura', 76109 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9126);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9228, 76, N'Centro de la Construcción', 76001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9228);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9543, 76, N'Centro de Tecnologías Agroindustriales', 76147 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9543);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9544, 76, N'Centro de Biotecnología Industrial', 76520 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9544);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9125, 76, N'Centro Latinoamericano de Especies Menores', 76834 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9125);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9530, 81, N'Centro de Gestión y Desarrollo Agroindustrial de Arauca', 81001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9530);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9519, 85, N'Centro Agroindustrial y Fortalecimiento Empresarial de Casanare', 85001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9519);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9518, 86, N'Centro Agroforestal y Acuícola Arapaima', 86568 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9518);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9539, 88, N'Centro de Formación Turística, Gente de Mar y de Servicios', 88001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9539);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9517, 91, N'Centro Para la Biodiversidad y El Turismo del Amazonas', 91001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9517);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9547, 94, N'Centro Ambiental y Ecoturístico del Nororiente Amazónico', 94001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9547);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9533, 95, N'Centro de Desarrollo Agroindustrial, Turístico y Tecnológico del Guaviare', 95001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9533);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9548, 97, N'Centro Agropecuario y de Servicios Ambientales Jirijirimo', 97001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9548);
INSERT INTO CENTROFORMACION (CENTROID, REGIONALID, CENTRONOMBRE, CIUDADID) SELECT 9531, 99, N'Centro de Producción y Transformación Agroindustrial de la Orinoquía', 99001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CENTROFORMACION WHERE CENTROID = 9531);

-- Grants + sinónimos para SEP_APP / SEP_LECTOR ───────────────────────
GRANT SELECT, INSERT, UPDATE, DELETE ON REGIONAL         TO SEP_APP;
GRANT SELECT                         ON REGIONAL         TO SEP_LECTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON CENTROFORMACION  TO SEP_APP;
GRANT SELECT                         ON CENTROFORMACION  TO SEP_LECTOR;

CREATE OR REPLACE SYNONYM SEP_APP.REGIONAL           FOR SEPLOCAL.REGIONAL;
CREATE OR REPLACE SYNONYM SEP_APP.CENTROFORMACION    FOR SEPLOCAL.CENTROFORMACION;
CREATE OR REPLACE SYNONYM SEP_LECTOR.REGIONAL        FOR SEPLOCAL.REGIONAL;
CREATE OR REPLACE SYNONYM SEP_LECTOR.CENTROFORMACION FOR SEPLOCAL.CENTROFORMACION;

COMMIT;
