-- v25_evaluador_jefe_municipio.sql
-- Amplía EVALUADOR con datos estructurados del jefe directo y el municipio
-- donde el evaluador reside. Idempotente vía EXCEPTION (ORA-01430 = columna
-- ya existe, ORA-02264 = constraint ya existe).
--
-- Notas:
--   * EVALUADORJEFEDIR (texto libre) se conserva por compatibilidad — el
--     servicio dejó de escribir en esa columna, pero las filas antiguas la
--     siguen exponiendo.
--   * EVALUADORQUIENAPRUEBA se preserva para Fase 4 (flujo de aprobación).
--   * EVALUADORMUNICIPIOID reutiliza el catálogo CIUDAD ya cargado.
--
-- Ejecutar como SEPLOCAL en SQL Developer.

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE EVALUADOR ADD (EVALUADORJEFENOMBRE NVARCHAR2(200))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE EVALUADOR ADD (EVALUADORJEFEEMAIL NVARCHAR2(150))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE EVALUADOR ADD (EVALUADORJEFECARGO NVARCHAR2(150))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE EVALUADOR ADD (EVALUADORMUNICIPIOID NUMBER(22))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[ALTER TABLE EVALUADOR ADD CONSTRAINT FK_EVALUADOR_MUNICIPIO
    FOREIGN KEY (EVALUADORMUNICIPIOID) REFERENCES CIUDAD(CIUDADID)]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -2264 AND SQLCODE != -2275 THEN RAISE; END IF;
END;
/

COMMIT;
