-- v25_evaluador_jefe_municipio.sql

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE EVALUADOR ADD (EVALUADORJEFENOMBRE NVARCHAR2(200))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE EVALUADOR ADD (EVALUADORJEFEEMAIL NVARCHAR2(150))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE EVALUADOR ADD (EVALUADORJEFECARGO NVARCHAR2(150))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE EVALUADOR ADD (EVALUADORMUNICIPIOID NUMBER(22))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[ALTER TABLE EVALUADOR ADD CONSTRAINT FK_EVALUADOR_MUNICIPIO
    FOREIGN KEY (EVALUADORMUNICIPIOID) REFERENCES CIUDAD(CIUDADID)]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -2264 AND SQLCODE != -2275 THEN RAISE; END IF;
END;
/

COMMIT;
