-- v27_evaluador_convocatoria_seed.sql
-- Seed idempotente del catálogo TIPODOCUMENTOCONV.
-- Los cinco tipos base que la Fase 5 exige para el sub-módulo de convocatorias.
-- Ejecutar como SEPLOCAL en SQL Developer.

INSERT INTO TIPODOCUMENTOCONV
  (TIPODOCUMENTOCONVID, CODIGO, NOMBRE, EXTENSIONESPERMITIDAS, ORDEN)
SELECT 1, N'INVITACION', N'Correo de invitación', N'pdf,msg', 10
  FROM DUAL
 WHERE NOT EXISTS (
   SELECT 1 FROM TIPODOCUMENTOCONV WHERE UPPER(CODIGO) = 'INVITACION'
 );

INSERT INTO TIPODOCUMENTOCONV
  (TIPODOCUMENTOCONVID, CODIGO, NOMBRE, EXTENSIONESPERMITIDAS, ORDEN)
SELECT 2, N'RATIFICACION', N'Correo de ratificación', N'pdf,msg', 20
  FROM DUAL
 WHERE NOT EXISTS (
   SELECT 1 FROM TIPODOCUMENTOCONV WHERE UPPER(CODIGO) = 'RATIFICACION'
 );

INSERT INTO TIPODOCUMENTOCONV
  (TIPODOCUMENTOCONVID, CODIGO, NOMBRE, EXTENSIONESPERMITIDAS, ORDEN)
SELECT 3, N'LISTADO_ASISTENCIA_PRESENCIAL', N'Listado de asistencia — Presencial', N'pdf,xlsx,xls', 30
  FROM DUAL
 WHERE NOT EXISTS (
   SELECT 1 FROM TIPODOCUMENTOCONV WHERE UPPER(CODIGO) = 'LISTADO_ASISTENCIA_PRESENCIAL'
 );

INSERT INTO TIPODOCUMENTOCONV
  (TIPODOCUMENTOCONVID, CODIGO, NOMBRE, EXTENSIONESPERMITIDAS, ORDEN)
SELECT 4, N'LISTADO_ASISTENCIA_PAT', N'Listado de asistencia — PAT (Excel)', N'xlsx,xls', 40
  FROM DUAL
 WHERE NOT EXISTS (
   SELECT 1 FROM TIPODOCUMENTOCONV WHERE UPPER(CODIGO) = 'LISTADO_ASISTENCIA_PAT'
 );

INSERT INTO TIPODOCUMENTOCONV
  (TIPODOCUMENTOCONVID, CODIGO, NOMBRE, EXTENSIONESPERMITIDAS, ORDEN)
SELECT 5, N'EXCEL_SELECCION', N'Excel de selección del equipo evaluador', N'xlsx,xls', 50
  FROM DUAL
 WHERE NOT EXISTS (
   SELECT 1 FROM TIPODOCUMENTOCONV WHERE UPPER(CODIGO) = 'EXCEL_SELECCION'
 );

COMMIT;
