-- v30_evaluador_aprobacion.sql

-- 1. Tabla

BEGIN
  EXECUTE IMMEDIATE q'[CREATE TABLE EVALUADORAPROBACION (
    APROBACIONID           NUMBER(10)      NOT NULL,
    PARTICIPACIONID        NUMBER(10)      NOT NULL,
    APROBADORNOMBRE        NVARCHAR2(200)  NOT NULL,
    APROBADOREMAIL         NVARCHAR2(150)  NOT NULL,
    APROBADORCARGO         NVARCHAR2(150),
    FECHAAPROBACION        DATE            NOT NULL,
    CORREOEVIDENCIA        BLOB,
    CORREOEVIDENCIAMIME    NVARCHAR2(120),
    CORREOEVIDENCIANOMBRE  NVARCHAR2(255),
    OBSERVACIONES          NVARCHAR2(1000),
    USUARIOCREACION        NVARCHAR2(200),
    FECHACREACION          DATE            DEFAULT SYSDATE NOT NULL,
    USUARIOMODIFICACION    NVARCHAR2(200),
    FECHAMODIFICACION      DATE,
    CONSTRAINT PK_EVALUADORAPROBACION PRIMARY KEY (APROBACIONID),
    CONSTRAINT UQ_APROB_PARTICIPACION UNIQUE (PARTICIPACIONID),
    CONSTRAINT FK_APROB_PART FOREIGN KEY (PARTICIPACIONID)
      REFERENCES EVALUADORPARTICIPACION(PARTICIPACIONID)
  )]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE EVALUADORAPROBACION IS
  'Autorización del jefe directo para participar en un ciclo de evaluación. 1:1 con la participación.';
COMMENT ON COLUMN EVALUADORAPROBACION.CORREOEVIDENCIA IS
  'Correo de autorización (.msg de Outlook o PDF). Tope 20 MB validado en aplicación.';
COMMENT ON COLUMN EVALUADORAPROBACION.APROBADOREMAIL IS
  'Correo del jefe que autoriza. Desnormalizado a propósito: puede ser alguien fuera de PERSONA.';

-- 2. Secuencia e índices

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE EVALUADORAPROBACION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_APROB_FECHA ON EVALUADORAPROBACION (FECHAAPROBACION DESC)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 AND SQLCODE != -1408 THEN RAISE; END IF;
END;
/

-- 3. GRANTS y SINÓNIMOS

GRANT SELECT, INSERT, UPDATE, DELETE ON EVALUADORAPROBACION     TO SEP_APP;
GRANT SELECT                         ON EVALUADORAPROBACION     TO SEP_LECTOR;
GRANT SELECT                         ON EVALUADORAPROBACION_SEQ TO SEP_APP;

CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORAPROBACION        FOR SEPLOCAL.EVALUADORAPROBACION;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORAPROBACION_SEQ    FOR SEPLOCAL.EVALUADORAPROBACION_SEQ;
CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADORAPROBACION     FOR SEPLOCAL.EVALUADORAPROBACION;

COMMIT;
