-- v34_evaluador_participacion_spine.sql
-- ──────────────────────────────────────────────────────────────────────────
-- Convierte EVALUADORPARTICIPACION en la COLUMNA VERTEBRAL del ciclo anual.
--
-- Hasta ahora participaciones, pruebas, documentos y convocatorias eran
-- cuatro islas que solo compartían un NUMBER(4) con el año. Esta migración
-- las ata:
--
--   EVALUADORPARTICIPACION  + CONVOCATORIAID, ESTADOPARTID, AREAID,
--                             MODALIDADPARTID, ESTRANSVERSAL, fechas, motivo
--   EVALUADORPRUEBA         + PARTICIPACIONID, APROBADA, PUNTAJEMINIMO
--   EVALUADORDOCUMENTO      + PARTICIPACIONID
--   EVALUADORCONVOCATORIA   + CONVOCATORIASEPID, notas de corte, MODALIDADPARTID
--
-- Y agrega dos tablas hijas que vienen del módulo de retroalimentación:
--   EVALUADORPARTGRUPO    — grupos (mesas) 1..8 en que participa ese año
--   EVALUADORPARTALCANCE  — alcance explícito de un evaluador transversal
--
-- Los PARTICIPACIONID nuevos son NULLABLE a propósito: el histórico 2021-2023
-- (pruebas sueltas, documentos sin ciclo) entra sin bloqueo y se ata después.
--
-- Idempotente. Ejecutar como SEPLOCAL, DESPUÉS de la v29.
-- ──────────────────────────────────────────────────────────────────────────


-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 1. EVALUADORPARTICIPACION — columnas del ciclo                          ║
-- ╚════════════════════════════════════════════════════════════════════════╝

DECLARE
  PROCEDURE add_col(p_tabla VARCHAR2, p_ddl VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ' || p_tabla || ' ADD (' || p_ddl || ')';
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
  END;
BEGIN
  add_col('EVALUADORPARTICIPACION', 'CONVOCATORIAID NUMBER(10)');
  add_col('EVALUADORPARTICIPACION', 'ESTADOPARTID NUMBER(10)');
  add_col('EVALUADORPARTICIPACION', 'AREAID NUMBER(10)');
  add_col('EVALUADORPARTICIPACION', 'MODALIDADPARTID NUMBER(10)');
  add_col('EVALUADORPARTICIPACION', 'ESTRANSVERSAL NUMBER(1) DEFAULT 0');
  add_col('EVALUADORPARTICIPACION', 'MOTIVONOPARTICIPA NVARCHAR2(300)');
  add_col('EVALUADORPARTICIPACION', 'FECHAINICIO DATE');
  add_col('EVALUADORPARTICIPACION', 'FECHAFIN DATE');
  add_col('EVALUADORPARTICIPACION', 'USUARIOCREACION NVARCHAR2(200)');
  add_col('EVALUADORPARTICIPACION', 'FECHACREACION DATE DEFAULT SYSDATE');
  add_col('EVALUADORPARTICIPACION', 'USUARIOMODIFICACION NVARCHAR2(200)');
  add_col('EVALUADORPARTICIPACION', 'FECHAMODIFICACION DATE');

  add_col('EVALUADORPRUEBA', 'PARTICIPACIONID NUMBER(10)');
  add_col('EVALUADORPRUEBA', 'APROBADA NUMBER(1)');
  add_col('EVALUADORPRUEBA', 'PUNTAJEMINIMO NUMBER(5,2)');
  add_col('EVALUADORPRUEBA', 'USUARIOCREACION NVARCHAR2(200)');
  add_col('EVALUADORPRUEBA', 'FECHACREACION DATE DEFAULT SYSDATE');

  add_col('EVALUADORDOCUMENTO', 'PARTICIPACIONID NUMBER(10)');
  add_col('EVALUADORDOCUMENTO', 'USUARIOCREACION NVARCHAR2(200)');

  add_col('EVALUADORCONVOCATORIA', 'CONVOCATORIASEPID NUMBER(10)');
  add_col('EVALUADORCONVOCATORIA', 'MODALIDADPARTID NUMBER(10)');
  add_col('EVALUADORCONVOCATORIA', 'PUNTAJEMINIMOPRUEBA NUMBER(5,2)');
  add_col('EVALUADORCONVOCATORIA', 'CALIFICACIONMINIMACURSO NUMBER(5,2)');
  add_col('EVALUADORCONVOCATORIA', 'USUARIOCREACION NVARCHAR2(200)');
  add_col('EVALUADORCONVOCATORIA', 'USUARIOMODIFICACION NVARCHAR2(200)');
  add_col('EVALUADORCONVOCATORIA', 'FECHAMODIFICACION DATE');
END;
/

COMMENT ON COLUMN EVALUADORPARTICIPACION.CONVOCATORIAID IS
  'Ciclo del banco al que pertenece. Habilita heredar los documentos generales del año sin duplicarlos por evaluador.';
COMMENT ON COLUMN EVALUADORPARTICIPACION.ESTADOPARTID IS
  'Estado declarado del ciclo. El backend calcula además un estadoSugerido desde el checklist y avisa si divergen.';
COMMENT ON COLUMN EVALUADORPARTICIPACION.AREAID IS
  'Área (Técnica/Jurídica/Financiera) en la que actuó ESE año. Es contexto anual, no atributo de la persona.';
COMMENT ON COLUMN EVALUADORPARTICIPACION.ESTRANSVERSAL IS
  '1 = evaluó con alcance explícito multi-área (ver EVALUADORPARTALCANCE), no por su grupo.';
COMMENT ON COLUMN EVALUADORPARTICIPACION.MOTIVONOPARTICIPA IS
  'Por qué declinó / no aprobó / se le revocó. Obligatorio en aplicación cuando el estado es ESNEGATIVO = 1.';

COMMENT ON COLUMN EVALUADORPRUEBA.PARTICIPACIONID IS
  'Ciclo al que corresponde la prueba. NULL = histórico suelto (2021-2023) que todavía no se ató a una participación.';
COMMENT ON COLUMN EVALUADORPRUEBA.PUNTAJEMINIMO IS
  'Nota de corte vigente al presentar. Congelada para que un cambio posterior no reescriba el histórico.';

COMMENT ON COLUMN EVALUADORDOCUMENTO.PARTICIPACIONID IS
  'NULL = documento personal permanente (cédula, HV). No nulo = documento propio de ese ciclo.';

COMMENT ON COLUMN EVALUADORCONVOCATORIA.CONVOCATORIASEPID IS
  'FK lógica a la CONVOCATORIA real del SEP (la de proyectos). Nullable: un ciclo del banco puede no mapear 1:1.';
COMMENT ON COLUMN EVALUADORCONVOCATORIA.PUNTAJEMINIMOPRUEBA IS
  'Nota de corte de la prueba de conocimiento de ESE año. Cambia año a año.';


-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 2. Constraints                                                          ║
-- ╚════════════════════════════════════════════════════════════════════════╝

DECLARE
  PROCEDURE add_fk(p_ddl VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_ddl;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2264 AND SQLCODE != -2275 AND SQLCODE != -955 THEN RAISE; END IF;
  END;
BEGIN
  add_fk(q'[ALTER TABLE EVALUADORPARTICIPACION ADD CONSTRAINT FK_PART_CONVOCATORIA
    FOREIGN KEY (CONVOCATORIAID) REFERENCES EVALUADORCONVOCATORIA(CONVOCATORIAID)]');
  add_fk(q'[ALTER TABLE EVALUADORPARTICIPACION ADD CONSTRAINT FK_PART_ESTADO
    FOREIGN KEY (ESTADOPARTID) REFERENCES ESTADOPARTICIPACION(ESTADOPARTID)]');
  add_fk(q'[ALTER TABLE EVALUADORPARTICIPACION ADD CONSTRAINT FK_PART_AREA
    FOREIGN KEY (AREAID) REFERENCES AREAEVALUACION(AREAID)]');
  add_fk(q'[ALTER TABLE EVALUADORPARTICIPACION ADD CONSTRAINT FK_PART_MODALIDAD
    FOREIGN KEY (MODALIDADPARTID) REFERENCES MODALIDADPART(MODALIDADPARTID)]');

  add_fk(q'[ALTER TABLE EVALUADORPRUEBA ADD CONSTRAINT FK_PRUEBA_PART
    FOREIGN KEY (PARTICIPACIONID) REFERENCES EVALUADORPARTICIPACION(PARTICIPACIONID)]');

  add_fk(q'[ALTER TABLE EVALUADORDOCUMENTO ADD CONSTRAINT FK_EVALDOC_PART
    FOREIGN KEY (PARTICIPACIONID) REFERENCES EVALUADORPARTICIPACION(PARTICIPACIONID)]');

  add_fk(q'[ALTER TABLE EVALUADORCONVOCATORIA ADD CONSTRAINT FK_CONV_MODALIDAD
    FOREIGN KEY (MODALIDADPARTID) REFERENCES MODALIDADPART(MODALIDADPARTID)]');
END;
/

-- Índices para las consultas del panel por año.
DECLARE
  PROCEDURE add_idx(p_ddl VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_ddl;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 AND SQLCODE != -1408 THEN RAISE; END IF;
  END;
BEGIN
  add_idx('CREATE INDEX IX_PART_CONVOCATORIA ON EVALUADORPARTICIPACION (CONVOCATORIAID)');
  add_idx('CREATE INDEX IX_PART_ESTADO       ON EVALUADORPARTICIPACION (ESTADOPARTID)');
  add_idx('CREATE INDEX IX_PRUEBA_PART       ON EVALUADORPRUEBA (PARTICIPACIONID)');
  add_idx('CREATE INDEX IX_EVALDOC_PART      ON EVALUADORDOCUMENTO (PARTICIPACIONID)');
  add_idx('CREATE INDEX IX_CONV_SEP          ON EVALUADORCONVOCATORIA (CONVOCATORIASEPID)');
END;
/


-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 3. EVALUADORPARTGRUPO — grupos/mesas del año (N:M)                      ║
-- ╚════════════════════════════════════════════════════════════════════════╝
-- Viene de EvalPersona.grupos [1..8]. Una persona puede estar en varios
-- grupos el mismo año (ej. un apoyo jurídico en los grupos 1, 2 y 8), por eso
-- es tabla y no columna.

BEGIN
  EXECUTE IMMEDIATE q'[CREATE TABLE EVALUADORPARTGRUPO (
    PARTGRUPOID      NUMBER(10)   NOT NULL,
    PARTICIPACIONID  NUMBER(10)   NOT NULL,
    GRUPONUMERO      NUMBER(3)    NOT NULL,
    ESPRINCIPAL      NUMBER(1)    DEFAULT 0 NOT NULL,
    CONSTRAINT PK_EVALUADORPARTGRUPO PRIMARY KEY (PARTGRUPOID),
    CONSTRAINT UQ_PARTGRUPO UNIQUE (PARTICIPACIONID, GRUPONUMERO),
    CONSTRAINT FK_PARTGRUPO_PART FOREIGN KEY (PARTICIPACIONID)
      REFERENCES EVALUADORPARTICIPACION(PARTICIPACIONID)
  )]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE EVALUADORPARTGRUPO IS
  'Grupos (mesas) en que participó el evaluador ese año. Alimenta el generador de la matriz de retroalimentación.';

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE EVALUADORPARTGRUPO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_PARTGRUPO_GRUPO ON EVALUADORPARTGRUPO (GRUPONUMERO)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 AND SQLCODE != -1408 THEN RAISE; END IF;
END;
/


-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 4. EVALUADORPARTALCANCE — alcance del evaluador transversal             ║
-- ╚════════════════════════════════════════════════════════════════════════╝
-- Aplana EvalPersona.alcanceEvaluacion [{area, roles[]}] a una fila por
-- (participación, área, rol). Solo aplica cuando ESTRANSVERSAL = 1.

BEGIN
  EXECUTE IMMEDIATE q'[CREATE TABLE EVALUADORPARTALCANCE (
    PARTALCANCEID    NUMBER(10)   NOT NULL,
    PARTICIPACIONID  NUMBER(10)   NOT NULL,
    AREAID           NUMBER(10)   NOT NULL,
    ROLEVALUADORID   NUMBER(10)   NOT NULL,
    CONSTRAINT PK_EVALUADORPARTALCANCE PRIMARY KEY (PARTALCANCEID),
    CONSTRAINT UQ_PARTALCANCE UNIQUE (PARTICIPACIONID, AREAID, ROLEVALUADORID),
    CONSTRAINT FK_PARTALC_PART FOREIGN KEY (PARTICIPACIONID)
      REFERENCES EVALUADORPARTICIPACION(PARTICIPACIONID),
    CONSTRAINT FK_PARTALC_AREA FOREIGN KEY (AREAID)
      REFERENCES AREAEVALUACION(AREAID),
    CONSTRAINT FK_PARTALC_ROL FOREIGN KEY (ROLEVALUADORID)
      REFERENCES ROLEVALUADOR(ROLEVALUADORID)
  )]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE EVALUADORPARTALCANCE IS
  'Qué roles de qué áreas le corresponde retroalimentar a un evaluador transversal. Una fila por (área, rol).';

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE EVALUADORPARTALCANCE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/


-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 5. BACKFILL de los datos existentes                                     ║
-- ╚════════════════════════════════════════════════════════════════════════╝

-- 5.1 MODALIDADPARTID desde el texto libre que hoy existe.
UPDATE EVALUADORPARTICIPACION p
   SET p.MODALIDADPARTID = (
         SELECT m.MODALIDADPARTID FROM MODALIDADPART m
          WHERE UPPER(m.CODIGO) = UPPER(TRIM(p.MODALIDADPART))
       )
 WHERE p.MODALIDADPARTID IS NULL
   AND p.MODALIDADPART IS NOT NULL
   AND EXISTS (
         SELECT 1 FROM MODALIDADPART m
          WHERE UPPER(m.CODIGO) = UPPER(TRIM(p.MODALIDADPART))
       );

UPDATE EVALUADORCONVOCATORIA c
   SET c.MODALIDADPARTID = (
         SELECT m.MODALIDADPARTID FROM MODALIDADPART m
          WHERE UPPER(m.CODIGO) = UPPER(TRIM(c.MODALIDADPART))
       )
 WHERE c.MODALIDADPARTID IS NULL
   AND c.MODALIDADPART IS NOT NULL
   AND EXISTS (
         SELECT 1 FROM MODALIDADPART m
          WHERE UPPER(m.CODIGO) = UPPER(TRIM(c.MODALIDADPART))
       );

-- 5.2 ESTADOPARTID: el histórico existente se marca FINALIZADO, salvo lo que
--     tenía la bandera PROCESOREVOCADO = 1, que pasa a REVOCADO.
UPDATE EVALUADORPARTICIPACION
   SET ESTADOPARTID = (SELECT ESTADOPARTID FROM ESTADOPARTICIPACION WHERE CODIGO = N'REVOCADO')
 WHERE ESTADOPARTID IS NULL
   AND NVL(PROCESOREVOCADO, 0) = 1;

UPDATE EVALUADORPARTICIPACION
   SET ESTADOPARTID = (SELECT ESTADOPARTID FROM ESTADOPARTICIPACION WHERE CODIGO = N'FINALIZADO')
 WHERE ESTADOPARTID IS NULL;

-- 5.3 CONVOCATORIAID: solo cuando existe UNA convocatoria del banco que
--     coincida en año (y periodo si ambos lo tienen). Si hay ambigüedad se
--     deja NULL para que el coordinador lo resuelva desde la UI.
UPDATE EVALUADORPARTICIPACION p
   SET p.CONVOCATORIAID = (
         SELECT MIN(c.CONVOCATORIAID) FROM EVALUADORCONVOCATORIA c
          WHERE c.ANIO = p.ANIO
            AND (p.PERIODO IS NULL OR c.PERIODO IS NULL OR TRIM(c.PERIODO) = TRIM(p.PERIODO))
       )
 WHERE p.CONVOCATORIAID IS NULL
   AND (SELECT COUNT(*) FROM EVALUADORCONVOCATORIA c
         WHERE c.ANIO = p.ANIO
           AND (p.PERIODO IS NULL OR c.PERIODO IS NULL OR TRIM(c.PERIODO) = TRIM(p.PERIODO))) = 1;

-- 5.4 EVALUADORPRUEBA.PARTICIPACIONID: se ata solo cuando el evaluador tiene
--     exactamente una participación en ese año. Con dos, queda NULL (histórico
--     suelto) y se resuelve a mano — es preferible a adivinar mal.
UPDATE EVALUADORPRUEBA pr
   SET pr.PARTICIPACIONID = (
         SELECT MIN(pa.PARTICIPACIONID) FROM EVALUADORPARTICIPACION pa
          WHERE pa.EVALUADORID = pr.EVALUADORID AND pa.ANIO = pr.ANIO
       )
 WHERE pr.PARTICIPACIONID IS NULL
   AND (SELECT COUNT(*) FROM EVALUADORPARTICIPACION pa
         WHERE pa.EVALUADORID = pr.EVALUADORID AND pa.ANIO = pr.ANIO) = 1;

-- 5.5 EVALUADORDOCUMENTO.PARTICIPACIONID: misma regla usando ANIOREFERENCIA.
--     Los documentos sin año quedan como permanentes (NULL), que es correcto.
UPDATE EVALUADORDOCUMENTO d
   SET d.PARTICIPACIONID = (
         SELECT MIN(pa.PARTICIPACIONID) FROM EVALUADORPARTICIPACION pa
          WHERE pa.EVALUADORID = d.EVALUADORID AND pa.ANIO = d.ANIOREFERENCIA
       )
 WHERE d.PARTICIPACIONID IS NULL
   AND d.ANIOREFERENCIA IS NOT NULL
   AND (SELECT COUNT(*) FROM EVALUADORPARTICIPACION pa
         WHERE pa.EVALUADORID = d.EVALUADORID AND pa.ANIO = d.ANIOREFERENCIA) = 1;

-- 5.6 EVALUADORAPROBACION desde el texto libre EVALUADOR.EVALUADORQUIENAPRUEBA.
--     Se crea una aprobación en la participación más antigua del evaluador,
--     marcada para revisión. Sin correo ni fecha reales: es solo rescate del dato.
INSERT INTO EVALUADORAPROBACION
  (APROBACIONID, PARTICIPACIONID, APROBADORNOMBRE, APROBADOREMAIL,
   FECHAAPROBACION, OBSERVACIONES, USUARIOCREACION)
SELECT EVALUADORAPROBACION_SEQ.NEXTVAL,
       pa.PARTICIPACIONID,
       SUBSTR(TRIM(e.EVALUADORQUIENAPRUEBA), 1, 200),
       N'pendiente@revisar.local',
       NVL(pa.FECHACREACION, SYSDATE),
       N'Migrado desde EVALUADOR.EVALUADORQUIENAPRUEBA (v34). Falta correo y fecha reales.',
       'migracion-v34'
  FROM EVALUADOR e
  JOIN (
        SELECT EVALUADORID, MIN(PARTICIPACIONID) AS PARTICIPACIONID, MIN(FECHACREACION) AS FECHACREACION
          FROM EVALUADORPARTICIPACION
         GROUP BY EVALUADORID
       ) pa ON pa.EVALUADORID = e.EVALUADORID
 WHERE e.EVALUADORQUIENAPRUEBA IS NOT NULL
   AND LENGTH(TRIM(e.EVALUADORQUIENAPRUEBA)) > 0
   AND NOT EXISTS (
         SELECT 1 FROM EVALUADORAPROBACION a WHERE a.PARTICIPACIONID = pa.PARTICIPACIONID
       );

-- 5.7 Rescate best-effort de EVALUADORJEFEDIR hacia la columna estructurada.
UPDATE EVALUADOR
   SET EVALUADORJEFENOMBRE = SUBSTR(TRIM(EVALUADORJEFEDIR), 1, 200)
 WHERE EVALUADORJEFENOMBRE IS NULL
   AND EVALUADORJEFEDIR IS NOT NULL
   AND LENGTH(TRIM(EVALUADORJEFEDIR)) > 0;


-- ╔════════════════════════════════════════════════════════════════════════╗
-- ║ 6. GRANTS y SINÓNIMOS                                                   ║
-- ╚════════════════════════════════════════════════════════════════════════╝

GRANT SELECT, INSERT, UPDATE, DELETE ON EVALUADORPARTGRUPO       TO SEP_APP;
GRANT SELECT                         ON EVALUADORPARTGRUPO       TO SEP_LECTOR;
GRANT SELECT                         ON EVALUADORPARTGRUPO_SEQ   TO SEP_APP;

GRANT SELECT, INSERT, UPDATE, DELETE ON EVALUADORPARTALCANCE     TO SEP_APP;
GRANT SELECT                         ON EVALUADORPARTALCANCE     TO SEP_LECTOR;
GRANT SELECT                         ON EVALUADORPARTALCANCE_SEQ TO SEP_APP;

CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORPARTGRUPO         FOR SEPLOCAL.EVALUADORPARTGRUPO;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORPARTGRUPO_SEQ     FOR SEPLOCAL.EVALUADORPARTGRUPO_SEQ;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORPARTALCANCE       FOR SEPLOCAL.EVALUADORPARTALCANCE;
CREATE OR REPLACE SYNONYM SEP_APP.EVALUADORPARTALCANCE_SEQ   FOR SEPLOCAL.EVALUADORPARTALCANCE_SEQ;

CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADORPARTGRUPO      FOR SEPLOCAL.EVALUADORPARTGRUPO;
CREATE OR REPLACE SYNONYM SEP_LECTOR.EVALUADORPARTALCANCE    FOR SEPLOCAL.EVALUADORPARTALCANCE;

COMMIT;
