-- Migración: Articulación Territorial para el Desarrollo

-- 1. Tabla ARTICULACIONTERRITORIAL

CREATE TABLE ARTICULACIONTERRITORIAL (
  ARTICULACIONTERRITORIALID      NUMBER           NOT NULL,
  ARTICULACIONTERRITORIALNOMBRE  NVARCHAR2(400)   NOT NULL,
  ARTICULACIONTERRITORIALESTADO  NUMBER(1)  DEFAULT 1 NOT NULL,
  CONSTRAINT PK_ARTTERRDES PRIMARY KEY (ARTICULACIONTERRITORIALID)
);

-- 2. Datos del catálogo

INSERT INTO ARTICULACIONTERRITORIAL (ARTICULACIONTERRITORIALID, ARTICULACIONTERRITORIALNOMBRE) VALUES
  (1, 'DESARROLLO RURAL, ECONOMÍA CAMPESINA Y PRODUCTIVIDAD TERRITORIAL');
INSERT INTO ARTICULACIONTERRITORIAL (ARTICULACIONTERRITORIALID, ARTICULACIONTERRITORIALNOMBRE) VALUES
  (2, 'ENCADENAMIENTOS PRODUCTIVOS, ECONOMÍA CAMPESINA Y ECONOMÍA POPULAR PARA LA COMPETITIVIDAD');
INSERT INTO ARTICULACIONTERRITORIAL (ARTICULACIONTERRITORIALID, ARTICULACIONTERRITORIALNOMBRE) VALUES
  (3, 'SISTEMAS ALIMENTARIOS SOSTENIBLES Y ARTICULACIÓN CAMPO-CIUDAD');
INSERT INTO ARTICULACIONTERRITORIAL (ARTICULACIONTERRITORIALID, ARTICULACIONTERRITORIALNOMBRE) VALUES
  (4, 'PARTICIPACIÓN, DIÁLOGO SOCIAL Y FORTALECIMIENTO DEL TEJIDO PRODUCTIVO RURAL Y URBANO');
INSERT INTO ARTICULACIONTERRITORIAL (ARTICULACIONTERRITORIALID, ARTICULACIONTERRITORIALNOMBRE) VALUES
  (5, 'GESTIÓN TERRITORIAL, USO SOSTENIBLE DEL SUELO Y DESARROLLO PRODUCTIVO');
INSERT INTO ARTICULACIONTERRITORIAL (ARTICULACIONTERRITORIALID, ARTICULACIONTERRITORIALNOMBRE) VALUES
  (6, 'JUSTICIA AMBIENTAL Y SOSTENIBILIDAD PARA LA COMPETITIVIDAD TERRITORIAL Y EMPRESARIAL');
INSERT INTO ARTICULACIONTERRITORIAL (ARTICULACIONTERRITORIALID, ARTICULACIONTERRITORIALNOMBRE) VALUES
  (7, 'EQUIDAD, DIVERSIDAD E INCLUSIÓN COMO FACTORES DE PRODUCTIVIDAD');

-- 3. Nueva columna en UNIDADTEMATICA
--      SELECT COLUMN_NAME FROM USER_TAB_COLUMNS
--      WHERE TABLE_NAME='UNIDADTEMATICA'
--      AND COLUMN_NAME='ARTICULACIONTERRITORIALID';

ALTER TABLE UNIDADTEMATICA ADD ARTICULACIONTERRITORIALID NUMBER;

ALTER TABLE UNIDADTEMATICA
  ADD CONSTRAINT FK_UT_ARTTERR
  FOREIGN KEY (ARTICULACIONTERRITORIALID)
  REFERENCES ARTICULACIONTERRITORIAL(ARTICULACIONTERRITORIALID);

COMMIT;
