-- v42_proyecto_manual_por_proponente.sql

SET SERVEROUTPUT ON;

DECLARE
  v_existe NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_existe FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'EVALUADORPARTPROYECTO' AND CONSTRAINT_NAME = 'CK_PARTPROY_REF';

  IF v_existe > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EVALUADORPARTPROYECTO DROP CONSTRAINT CK_PARTPROY_REF';
    DBMS_OUTPUT.PUT_LINE('Restriccion anterior eliminada.');
  END IF;

  EXECUTE IMMEDIATE
    'ALTER TABLE EVALUADORPARTPROYECTO ADD CONSTRAINT CK_PARTPROY_REF CHECK (' ||
    'PROYECTOID IS NOT NULL OR GUARDADOID IS NOT NULL OR ' ||
    'NOMBREPROYECTO IS NOT NULL OR RAZONSOCIAL IS NOT NULL)';
  DBMS_OUTPUT.PUT_LINE('Restriccion recreada, ahora acepta tambien RAZONSOCIAL.');
END;
/

-- Verificación

DECLARE
  v_id   NUMBER;
  v_part NUMBER;
  v_cond VARCHAR2(4000);
BEGIN
  SELECT SEARCH_CONDITION_VC INTO v_cond FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'EVALUADORPARTPROYECTO' AND CONSTRAINT_NAME = 'CK_PARTPROY_REF';
  DBMS_OUTPUT.PUT_LINE('Condicion actual: ' || v_cond);

  IF UPPER(v_cond) NOT LIKE '%RAZONSOCIAL%' THEN
    RAISE_APPLICATION_ERROR(-20042, 'La restriccion no quedo con RAZONSOCIAL.');
  END IF;

  -- Prueba real contra una participación cualquiera, y se deshace.
  SELECT MIN(PARTICIPACIONID) INTO v_part FROM EVALUADORPARTICIPACION;
  IF v_part IS NULL THEN
    DBMS_OUTPUT.PUT_LINE('(no hay participaciones para probar la insercion)');
  ELSE
    SELECT EVALUADORPARTPROYECTO_SEQ.NEXTVAL INTO v_id FROM dual;
    INSERT INTO EVALUADORPARTPROYECTO
      (PARTPROYECTOID, PARTICIPACIONID, RAZONSOCIAL, USUARIOCREACION)
    VALUES (v_id, v_part, 'PRUEBA DE LA MIGRACION V42', 'v42');
    DBMS_OUTPUT.PUT_LINE('Insercion con solo el proponente: OK');
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Fila de prueba deshecha.');
  END IF;

  DBMS_OUTPUT.PUT_LINE('-- Listo: se puede registrar un proyecto con solo el proponente.');
END;
/
