-- =============================================================================
-- Migración: Retos Nacionales para Alineación de AF
-- Versión: 4.0
-- Fecha: 2026-04-20
-- Autor: JoSeLoDiAz
-- Descripción: Crea tabla RETONACIONAL con los 8 retos del PND 2022-2026
--              y agrega RETONACIONALID a AFCOMPONENTE para mapear los
--              componentes estratégicos (IDs 775-875, sin tipo) a su reto.
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Tabla RETONACIONAL
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE RETONACIONAL (
  RETONACIONALID     NUMBER        NOT NULL,
  RETONACIONALNOMBRE NVARCHAR2(600) NOT NULL,
  RETONACIONALESTADO NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_RETONACIONAL PRIMARY KEY (RETONACIONALID)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Datos de Retos Nacionales (PND Colombia Potencia Mundial de la Vida 2022-2026)
-- ─────────────────────────────────────────────────────────────────────────────

INSERT INTO RETONACIONAL (RETONACIONALID, RETONACIONALNOMBRE) VALUES
  (1, 'AGROECOLOGÍA, AGRICULTURA, AGROINDUSTRIA, BIOECONOMÍA, SOSTENIBILIDAD Y GESTIÓN AMBIENTAL (BASES DEL PLAN NACIONAL DE DESARROLLO, COLOMBIA POTENCIA MUNDIAL DE LA VIDA 2022 – 2026)');
INSERT INTO RETONACIONAL (RETONACIONALID, RETONACIONALNOMBRE) VALUES
  (2, 'EDUCACIÓN, INCLUSIÓN SOCIAL Y DESARROLLO HUMANO (BASES DEL PLAN NACIONAL DE DESARROLLO, COLOMBIA POTENCIA MUNDIAL DE LA VIDA 2022 – 2026)');
INSERT INTO RETONACIONAL (RETONACIONALID, RETONACIONALNOMBRE) VALUES
  (3, 'SALUD, SERVICIOS DE CUIDADO Y REINDUSTRIALIZACIÓN DEL SECTOR SALUD (BASES DEL PLAN NACIONAL DE DESARROLLO, COLOMBIA POTENCIA MUNDIAL DE LA VIDA 2022 – 2026)');
INSERT INTO RETONACIONAL (RETONACIONALID, RETONACIONALNOMBRE) VALUES
  (4, 'TECNOLOGÍAS DIGITALES, INNOVACIÓN Y PRODUCTIVIDAD (BASES DEL PLAN NACIONAL DE DESARROLLO, COLOMBIA POTENCIA MUNDIAL DE LA VIDA 2022 – 2026)');
INSERT INTO RETONACIONAL (RETONACIONALID, RETONACIONALNOMBRE) VALUES
  (5, 'DESARROLLO EMPRESARIAL, CONOCIMIENTO Y COMPETITIVIDAD TERRITORIAL (BASES DEL PLAN NACIONAL DE DESARROLLO, COLOMBIA POTENCIA MUNDIAL DE LA VIDA 2022 – 2026)');
INSERT INTO RETONACIONAL (RETONACIONALID, RETONACIONALNOMBRE) VALUES
  (6, 'TURISMO SOSTENIBLE Y CULTURA POPULAR (BASES DEL PLAN NACIONAL DE DESARROLLO, COLOMBIA POTENCIA MUNDIAL DE LA VIDA 2022 – 2026)');
INSERT INTO RETONACIONAL (RETONACIONALID, RETONACIONALNOMBRE) VALUES
  (7, 'TRANSICIÓN ENERGÉTICA Y MINERÍA SUSTENTABLE (BASES DEL PLAN NACIONAL DE DESARROLLO, COLOMBIA POTENCIA MUNDIAL DE LA VIDA 2022 – 2026, CONPES 4142 DE 2022 POLÍTICA NACIONAL DE REINDUSTRIALIZACIÓN)');
INSERT INTO RETONACIONAL (RETONACIONALID, RETONACIONALNOMBRE) VALUES
  (8, 'REINDUSTRIALIZACIÓN PARA LA DEFENSA Y LA VIDA (CONPES 4129 DE 2023 POLÍTICA NACIONAL DE REINDUSTRIALIZACIÓN)');

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Agregar RETONACIONALID a AFCOMPONENTE
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE AFCOMPONENTE ADD RETONACIONALID NUMBER;

ALTER TABLE AFCOMPONENTE
  ADD CONSTRAINT FK_AFCOMP_RETO
  FOREIGN KEY (RETONACIONALID)
  REFERENCES RETONACIONAL(RETONACIONALID);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Mapeo de AFCOMPONENTE (IDs 775-875, sin tipo) a su RETO NACIONAL
-- ─────────────────────────────────────────────────────────────────────────────

-- Reto 1: Agroecología, Agricultura, Agroindustria, Bioeconomía, Sostenibilidad
UPDATE AFCOMPONENTE SET RETONACIONALID = 1
  WHERE AFCOMPONENTEID IN (775,776,777,778,779,780,781,782,783,784,
                            820,821,822,823,824,825,826,827,828,829);

-- Reto 2: Educación, Inclusión Social y Desarrollo Humano
UPDATE AFCOMPONENTE SET RETONACIONALID = 2
  WHERE AFCOMPONENTEID IN (785,786,787,788,789,790,791,792,
                            833,834,835,836,837,838,839,840);

-- Reto 3: Salud, Servicios de Cuidado y Reindustrialización Sector Salud
UPDATE AFCOMPONENTE SET RETONACIONALID = 3
  WHERE AFCOMPONENTEID IN (793,794,795,796,797,798,799);

-- Reto 4: Tecnologías Digitales, Innovación y Productividad
UPDATE AFCOMPONENTE SET RETONACIONALID = 4
  WHERE AFCOMPONENTEID IN (800,801,802,803,804,805,806,807,808,
                            809,810,811,812,813,814,815);

-- Reto 5: Desarrollo Empresarial, Conocimiento y Competitividad Territorial
UPDATE AFCOMPONENTE SET RETONACIONALID = 5
  WHERE AFCOMPONENTEID IN (816,817,818,819,875);

-- Reto 6: Turismo Sostenible y Cultura Popular
UPDATE AFCOMPONENTE SET RETONACIONALID = 6
  WHERE AFCOMPONENTEID IN (830,831,832);

-- Reto 7: Transición Energética y Minería Sustentable
UPDATE AFCOMPONENTE SET RETONACIONALID = 7
  WHERE AFCOMPONENTEID IN (841,842,843,844,845,846,847,848,849,850,
                            851,852,853,854,855,856,857,858,859,860,
                            861,862,863,864,865,866);

-- Reto 8: Reindustrialización para la Defensa y la Vida
UPDATE AFCOMPONENTE SET RETONACIONALID = 8
  WHERE AFCOMPONENTEID IN (867,868,869,870,871,872,873,874);

COMMIT;
