-- Reversa de la carga del consolidado 2023.

UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=39, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=2 WHERE PRUEBAID=71;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=33, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=1 WHERE PRUEBAID=75;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=85, PUNTAJEMAYOR=34, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=1 WHERE PRUEBAID=81;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=100, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=1 WHERE PRUEBAID=28;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=40, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=2 WHERE PRUEBAID=14;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=39, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=2 WHERE PRUEBAID=23;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=33, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=1 WHERE PRUEBAID=40;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=35, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=1 WHERE PRUEBAID=52;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=34, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=1 WHERE PRUEBAID=56;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=32, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=1 WHERE PRUEBAID=67;

-- Las creadas hay que borrarlas a mano si se revierte.
COMMIT;
