-- Reversa de la carga del consolidado 2021.

UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=91, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=1 WHERE PRUEBAID=50;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=97, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=4 WHERE PRUEBAID=38;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=100, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=1 WHERE PRUEBAID=34;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=80, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=1 WHERE PRUEBAID=49;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=83, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=2 WHERE PRUEBAID=65;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=94, PUNTAJEMAYOR=90, PUNTAJEMINIMO=NULL, APROBADA=NULL, INTENTOS=2 WHERE PRUEBAID=86;

COMMIT;
