-- Reversa de la carga del consolidado 2022.

UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=87, PUNTAJEMINIMO=NULL, APROBADA=NULL WHERE PRUEBAID=27;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=36, PUNTAJEMINIMO=NULL, APROBADA=NULL WHERE PRUEBAID=15;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=34, PUNTAJEMINIMO=NULL, APROBADA=NULL WHERE PRUEBAID=39;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=37, PUNTAJEMINIMO=NULL, APROBADA=NULL WHERE PRUEBAID=51;
UPDATE EVALUADORPRUEBA SET EFECTIVIDAD=NULL, PUNTAJEMAYOR=33, PUNTAJEMINIMO=NULL, APROBADA=NULL WHERE PRUEBAID=66;

COMMIT;
