-- =============================================================================
-- Migración: Actualización de Retos Nacionales y Componentes Estratégicos
-- Versión: 5.0
-- Fecha: 2026-04-20
-- Autor: JoSeLoDiAz
-- Descripción: Actualiza nombres de RETONACIONAL (1,3,7), agrega reto 9,
--              reemplaza componentes estratégicos (IDs 775-875) por la lista
--              oficial actualizada (92 componentes, IDs 876-967).
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Actualizar nombres de RETONACIONAL existentes
-- ─────────────────────────────────────────────────────────────────────────────

UPDATE RETONACIONAL SET RETONACIONALNOMBRE = 'AGROECOLOGÍA, AGRICULTURA, AGROINDUSTRIA, BIOECONOMÍA, SOSTENIBILIDAD Y GESTIÓN AMBIENTAL (BASES DEL PLAN NACIONAL DE DESARROLLO, COLOMBIA POTENCIA MUNDIAL DE LA VIDA 2022 – 2026 Y ESTRATEGIA PRIORIZADA POR LA DIRECCIÓN DEL SISTEMA NACIONAL DE FORMACIÓN PARA EL TRABAJO DEL SENA - DSNFT)'
  WHERE RETONACIONALID = 1;

UPDATE RETONACIONAL SET RETONACIONALNOMBRE = 'SALUD, SERVICIOS DE CUIDADO Y REINDUSTRIALIZACIÓN DEL SECTOR SALUD (BASES DEL PLAN NACIONAL DE DESARROLLO, COLOMBIA POTENCIA MUNDIAL DE LA VIDA 2022 – 2026) (CONPES 4129 DE 2023 POLÍTICA NACIONAL DE REINDUSTRIALIZACIÓN)'
  WHERE RETONACIONALID = 3;

UPDATE RETONACIONAL SET RETONACIONALNOMBRE = 'TRANSICIÓN ENERGÉTICA Y MINERÍA SUSTENTABLE (BASES DEL PLAN NACIONAL DE DESARROLLO, COLOMBIA POTENCIA MUNDIAL DE LA VIDA 2022 – 2026)'
  WHERE RETONACIONALID = 7;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Insertar Reto Nacional 9
-- ─────────────────────────────────────────────────────────────────────────────

INSERT INTO RETONACIONAL (RETONACIONALID, RETONACIONALNOMBRE, RETONACIONALESTADO)
  VALUES (9, 'DESARROLLO TERRITORIAL Y AGENDAS DEPARTAMENTALES', 1);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Limpiar componentes anteriores (IDs 775-875)
-- ─────────────────────────────────────────────────────────────────────────────

DELETE FROM AFALINEACION WHERE COMPONENTE BETWEEN 775 AND 875;
DELETE FROM AFCOMPONENTE  WHERE AFCOMPONENTEID BETWEEN 775 AND 875;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Insertar nuevos componentes estratégicos (IDs 876-967)
--    AFCOMPONENTEESTADO = 1 (Activo)
-- ─────────────────────────────────────────────────────────────────────────────

-- Reto 1: Agroecología, Agricultura, Agroindustria, Bioeconomía (44 items, IDs 876-919)
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (876, 'AGROINDUSTRIA CAMPESINA E INFRAESTRUCTURA PRODUCTIVA - DSNFT.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (877, 'COMERCIALIZACIÓN DE PRODUCTOS CAMPESINOS - DSNFT.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (878, 'TRANSICIÓN AGROECOLÓGICA - DSNFT.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (879, 'ASOCIATIVIDAD Y COOPERATIVISMO - DSNFT.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (880, 'GESTIÓN COMUNITARIA DEL AGUA Y DE LOS ECOSISTEMAS - DSNFT.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (881, 'DERECHOS CAMPESINOS Y REFORMA AGRARIA - DSNFT.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (882, 'PRÁCTICAS COMUNITARIAS Y TRADICIONALES (GASTRONOMÍA, TURISMO, ARTESANÍAS) - DSNFT.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (883, 'INFRAESTRUCTURA COMUNITARIA Y MEJORAMIENTO DE VIVIENDA - DSNFT.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (884, 'SOSTENIBILIDAD AMBIENTAL.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (885, 'DIVERSIFICACIÓN DE CULTIVOS.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (886, 'MANEJO ECOLÓGICO DE PLAGAS.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (887, 'PRODUCCIÓN DE INSUMOS AGROECOLÓGICOS.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (888, 'BIOMASA Y PRODUCCIÓN DE BIOINSUMOS.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (889, 'GESTIÓN Y CONSERVACIÓN HÍDRICA.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (890, 'RECUPERACIÓN DE SEMILLAS NATIVAS Y CRIOLLAS.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (891, 'ENERGÍAS RENOVABLES EN FINCAS.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (892, 'CRIANZA AGROECOLÓGICA DE ANIMALES.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (893, 'ADAPTACIÓN AL CAMBIO CLIMÁTICO.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (894, 'RECONVERSIÓN PRODUCTIVA TERRITORIAL.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (895, 'TRANSFORMACIÓN Y COMERCIALIZACIÓN DE PRODUCTOS AGROECOLÓGICOS.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (896, 'EDUCACIÓN AMBIENTAL.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (897, 'GOBERNANZA LOCAL.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (898, 'SOBERANÍA ALIMENTARIA.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (899, 'SEGURIDAD ALIMENTARIA Y NUTRICIONAL.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (900, 'ELABORACIÓN DE ALIMENTOS Y BEBIDAS.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (901, 'DERECHO HUMANO A LA ALIMENTACIÓN.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (902, 'EQUIDAD DE GÉNERO EN LA AGROECOLOGÍA.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (903, 'GESTIÓN AMBIENTAL.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (904, 'RESIDUOS SÓLIDOS Y SANEAMIENTO BÁSICO.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (905, 'BIODIVERSIDAD.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (906, 'SERVICIOS ECOSISTÉMICOS.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (907, 'ENERGÍAS LIMPIAS.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (908, 'ECONOMÍA CIRCULAR.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (909, 'CRECIMIENTO VERDE.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (910, 'NEUTRALIDAD DE CARBONO.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (911, 'RESTAURACIÓN ECOLÓGICA.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (912, 'BIOECONOMÍA.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (913, 'GANADERÍA REGENERATIVA.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (914, 'TRANSFERENCIA TECNOLÓGICA AGROINDUSTRIAL.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (915, 'AGRICULTURA DIGITAL.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (916, 'ENCADENAMIENTOS PRODUCTIVOS.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (917, 'ENCADENAMIENTOS DE EXPORTACIÓN PARA FORTALECER LA COMPETITIVIDAD.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (918, 'EXPANSIÓN INTERNACIONAL DE LA PRODUCCIÓN AGROINDUSTRIAL.', 1, 1);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (919, 'CONSTRUCCIÓN Y MATERIALES SOSTENIBLES.', 1, 1);

-- Reto 2: Educación, Inclusión Social y Desarrollo Humano (7 items, IDs 920-926)
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (920, 'EDUCACIÓN DE CALIDAD Y FORTALECIMIENTO PEDAGÓGICO.', 1, 2);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (921, 'EDUCACIÓN ECONÓMICA Y FINANCIERA.', 1, 2);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (922, 'EDUCACIÓN CIUDADANA.', 1, 2);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (923, 'DIVERSIDAD CULTURAL, AMBIENTAL Y SOCIAL VINCULADA AL TERRITORIO.', 1, 2);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (924, 'CONSTRUCCIÓN DE PAZ.', 1, 2);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (925, 'ENFOQUE DE GÉNERO Y DIFERENCIAL.', 1, 2);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (926, 'INCLUSIÓN SOCIAL Y PRODUCTIVA DE MUJERES.', 1, 2);

-- Reto 3: Salud, Servicios de Cuidado y Reindustrialización Sector Salud (8 items, IDs 927-934)
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (927, 'PROMOCIÓN DE LA SALUD Y PREVENCIÓN.', 1, 3);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (928, 'ATENCIÓN INTEGRAL EN SALUD, SALUD FÍSICA, MENTAL Y SOCIAL.', 1, 3);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (929, 'SERVICIOS DE CUIDADO.', 1, 3);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (930, 'SALUD DIGITAL.', 1, 3);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (931, 'PRODUCCIÓN LOCAL DE EXCIPIENTES, MEDICAMENTOS, VACUNAS Y DISPOSITIVOS MÉDICOS.', 1, 3);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (932, 'SERVICIOS MÉDICOS DE EXPORTACIÓN.', 1, 3);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (933, 'FARMACÉUTICA, INVESTIGACIÓN, AUDITORÍA Y BIOTECNOLOGÍA.', 1, 3);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (934, 'ATENCIÓN DE LA SALUD HUMANA.', 1, 3);

-- Reto 4: Tecnologías Digitales, Innovación y Productividad (7 items, IDs 935-941)
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (935, 'USO Y APROPIACIÓN DE TECNOLOGÍAS DIGITALES.', 1, 4);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (936, 'USO CONCRETO Y APLICABLE DE INTELIGENCIA ARTIFICIAL.', 1, 4);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (937, 'INNOVACIÓN DIGITAL DEL SECTOR PRODUCTIVO.', 1, 4);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (938, 'FORTALECIMIENTO DE SERVICIOS TIC.', 1, 4);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (939, 'PROGRAMACIÓN Y CIENCIA DE DATOS.', 1, 4);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (940, 'INFRAESTRUCTURA TECNOLÓGICA.', 1, 4);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (941, 'CIBERSEGURIDAD Y TRANSFERENCIA TECNOLÓGICA.', 1, 4);

-- Reto 5: Desarrollo Empresarial, Conocimiento y Competitividad Territorial (8 items, IDs 942-949)
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (942, 'CRECIMIENTO EMPRESARIAL.', 1, 5);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (943, 'GESTIÓN DEL CONOCIMIENTO.', 1, 5);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (944, 'INVESTIGACIÓN E INNOVACIÓN EMPRESARIAL.', 1, 5);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (945, 'DERECHOS DE PROPIEDAD INTELECTUAL Y PROTECCIÓN DE SABERES TRADICIONALES.', 1, 5);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (946, 'CIUDADES Y HÁBITATS RESILIENTES.', 1, 5);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (947, 'CONVERGENCIA REGIONAL.', 1, 5);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (948, 'INFRAESTRUCTURA Y SERVICIOS LOGÍSTICOS.', 1, 5);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (949, 'GESTIÓN DE RIESGOS.', 1, 5);

-- Reto 6: Turismo Sostenible y Cultura Popular (6 items, IDs 950-955)
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (950, 'TURISMO SOSTENIBLE.', 1, 6);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (951, 'ENCADENAMIENTOS ENTRE TURISMO CULTURAL Y PRODUCCIÓN REGIONAL.', 1, 6);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (952, 'DEPORTE, RECREACIÓN Y ACTIVIDADES FÍSICAS.', 1, 6);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (953, 'SERVICIOS DE CUIDADO.', 1, 6);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (954, 'EXPRESIONES ARTÍSTICAS Y CULTURALES.', 1, 6);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (955, 'SOSTENIBILIDAD DEL SECTOR ARTESANAL.', 1, 6);

-- Reto 7: Transición Energética y Minería Sustentable (6 items, IDs 956-961)
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (956, 'TRANSICIÓN ENERGÉTICA, DESCARBONIZACIÓN Y ENERGÍAS ALTERNATIVAS.', 1, 7);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (957, 'SEGURIDAD ENERGÉTICA.', 1, 7);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (958, 'PRODUCCIÓN Y ENSAMBLE DE EQUIPOS PARA SISTEMAS DE ENERGÍA.', 1, 7);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (959, 'CAPACIDADES TÉCNICAS PARA ASCENSO TECNOLÓGICO EN TRANSPORTE.', 1, 7);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (960, 'MOVILIDAD SOSTENIBLE.', 1, 7);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (961, 'MINERÍA FORMAL, EXPLORACIÓN Y COMERCIALIZACIÓN SOSTENIBLE DE MINERALES ESTRATÉGICOS.', 1, 7);

-- Reto 8: Reindustrialización para la Defensa y la Vida (2 items, IDs 962-963)
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (962, 'DESARROLLO INDUSTRIAL PARA DEFENSA Y VIDA.', 1, 8);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (963, 'INDUSTRIAS ASTILLERO, AERONÁUTICA Y SERVICIOS TECNOLÓGICOS INDUSTRIALES.', 1, 8);

-- Reto 9: Desarrollo Territorial y Agendas Departamentales (4 items, IDs 964-967)
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (964, 'TERRITORIOS Y SU BASE EMPRESARIAL.', 1, 9);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (965, 'AGENDAS DEPARTAMENTALES DE COMPETITIVIDAD E INNOVACIÓN.', 1, 9);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (966, 'FORTALECIMIENTO DE LAS VOCACIONES PRODUCTIVAS.', 1, 9);
INSERT INTO AFCOMPONENTE (AFCOMPONENTEID, AFCOMPONENTENOMBRE, AFCOMPONENTEESTADO, RETONACIONALID) VALUES (967, 'ARTICULACIÓN REGIONAL Y TERRITORIAL.', 1, 9);

COMMIT;
