-- Reversa de la v62: deja los nombres como estaban.

UPDATE PERSONA SET PERSONANOMBRES=N'LINA MARÍA                                                                                          ', PERSONAPRIMERAPELLIDO=N'ORJUELA             ', PERSONASEGUNDOAPELLIDO=N'RUSSI               ' WHERE PERSONAID=31005;
UPDATE PERSONA SET PERSONANOMBRES=N'JHON JAIRO                                                                                          ', PERSONAPRIMERAPELLIDO=N'GARCÍA              ', PERSONASEGUNDOAPELLIDO=N'MERCHÁN             ' WHERE PERSONAID=31423;
UPDATE PERSONA SET PERSONANOMBRES=N'YESENIA LIZETH                                                                                      ', PERSONAPRIMERAPELLIDO=N'DUARTE              ', PERSONASEGUNDOAPELLIDO=N'MEZA                ' WHERE PERSONAID=31426;
UPDATE PERSONA SET PERSONANOMBRES=N'BLANCA YANETH                                                                                       ', PERSONAPRIMERAPELLIDO=N'MURALLAS            ', PERSONASEGUNDOAPELLIDO=N'BUENO               ' WHERE PERSONAID=60812;
UPDATE PERSONA SET PERSONANOMBRES=N'LEON ERNESTO                                                                                        ', PERSONAPRIMERAPELLIDO=N' GOMEZ              ', PERSONASEGUNDOAPELLIDO=N'ZEA                 ' WHERE PERSONAID=93612;
UPDATE PERSONA SET PERSONANOMBRES=N'ADRIANA                                                                                             ', PERSONAPRIMERAPELLIDO=N'LÓPEZ               ', PERSONASEGUNDOAPELLIDO=N'DUQUE               ' WHERE PERSONAID=97574;
UPDATE PERSONA SET PERSONANOMBRES=N'EDDER ALCIDES                                                                                       ', PERSONAPRIMERAPELLIDO=N'PARODY              ', PERSONASEGUNDOAPELLIDO=N'CAMARGO             ' WHERE PERSONAID=97579;
UPDATE PERSONA SET PERSONANOMBRES=N'FRANCISCO JAVIER                                                                                    ', PERSONAPRIMERAPELLIDO=N'ARAZO               ', PERSONASEGUNDOAPELLIDO=N'GÓMEZ               ' WHERE PERSONAID=97591;
UPDATE PERSONA SET PERSONANOMBRES=N'MARTHA ELIZABETH                                                                                    ', PERSONAPRIMERAPELLIDO=N'CORTES              ', PERSONASEGUNDOAPELLIDO=N'RICO                ' WHERE PERSONAID=97601;
UPDATE PERSONA SET PERSONANOMBRES=N'MARIO ANDRES                                                                                        ', PERSONAPRIMERAPELLIDO=N'RODRIGUEZ           ', PERSONASEGUNDOAPELLIDO=N'LOPEZ               ' WHERE PERSONAID=117346;
UPDATE PERSONA SET PERSONANOMBRES=N'DAVID ALEXANDER                                                                                     ', PERSONAPRIMERAPELLIDO=N'FIQUE               ', PERSONASEGUNDOAPELLIDO=N'PARDO               ' WHERE PERSONAID=131958;
UPDATE PERSONA SET PERSONANOMBRES=N'SANDRA PATRICIA DE LA CONCEPCION                                                                    ', PERSONAPRIMERAPELLIDO=N'BARÓN               ', PERSONASEGUNDOAPELLIDO=N'FLÓREZ              ' WHERE PERSONAID=133978;
UPDATE PERSONA SET PERSONANOMBRES=N'ZULMA ROCIO                                                                                         ', PERSONAPRIMERAPELLIDO=N'GOMEZ               ', PERSONASEGUNDOAPELLIDO=N'GALEÓN              ' WHERE PERSONAID=134190;
UPDATE PERSONA SET PERSONANOMBRES=N'DIANA PAOLA                                                                                         ', PERSONAPRIMERAPELLIDO=N'BALLESTEROS         ', PERSONASEGUNDOAPELLIDO=N'RIVEROS             ' WHERE PERSONAID=141580;
UPDATE PERSONA SET PERSONANOMBRES=N'MARITZA                                                                                             ', PERSONAPRIMERAPELLIDO=N'VALENCIA            ', PERSONASEGUNDOAPELLIDO=N'GONZALEZ            ' WHERE PERSONAID=144938;
UPDATE PERSONA SET PERSONANOMBRES=N'ALEJANDRO                                                                                           ', PERSONAPRIMERAPELLIDO=N'ARIAS               ', PERSONASEGUNDOAPELLIDO=N'OSORIO              ' WHERE PERSONAID=186159;
UPDATE PERSONA SET PERSONANOMBRES=N'SANDRA MILENA                                                                                       ', PERSONAPRIMERAPELLIDO=N'REYES               ', PERSONASEGUNDOAPELLIDO=N'IBAÑEZ              ' WHERE PERSONAID=192090;
UPDATE PERSONA SET PERSONANOMBRES=N'ALINE ISABEL                                                                                        ', PERSONAPRIMERAPELLIDO=N'MELO                ', PERSONASEGUNDOAPELLIDO=N'HENRÍQUEZ           ' WHERE PERSONAID=192372;
UPDATE PERSONA SET PERSONANOMBRES=N'HUGO ARMANDO                                                                                        ', PERSONAPRIMERAPELLIDO=N'MATURANA            ', PERSONASEGUNDOAPELLIDO=N'MOSQUERA            ' WHERE PERSONAID=233480;

COMMIT;
