-- v62 — nombres de los evaluadores en Título, no en MAYÚSCULA.

-- El backend ya guarda así desde el módulo; esto empareja lo importado de Excel.

UPDATE PERSONA SET PERSONANOMBRES=N'Lina María', PERSONAPRIMERAPELLIDO=N'Orjuela', PERSONASEGUNDOAPELLIDO=N'Russi' WHERE PERSONAID=31005;
UPDATE PERSONA SET PERSONANOMBRES=N'Jhon Jairo', PERSONAPRIMERAPELLIDO=N'García', PERSONASEGUNDOAPELLIDO=N'Merchán' WHERE PERSONAID=31423;
UPDATE PERSONA SET PERSONANOMBRES=N'Yesenia Lizeth', PERSONAPRIMERAPELLIDO=N'Duarte', PERSONASEGUNDOAPELLIDO=N'Meza' WHERE PERSONAID=31426;
UPDATE PERSONA SET PERSONANOMBRES=N'Blanca Yaneth', PERSONAPRIMERAPELLIDO=N'Murallas', PERSONASEGUNDOAPELLIDO=N'Bueno' WHERE PERSONAID=60812;
UPDATE PERSONA SET PERSONANOMBRES=N'Leon Ernesto', PERSONAPRIMERAPELLIDO=N'Gomez', PERSONASEGUNDOAPELLIDO=N'Zea' WHERE PERSONAID=93612;
UPDATE PERSONA SET PERSONANOMBRES=N'Adriana', PERSONAPRIMERAPELLIDO=N'López', PERSONASEGUNDOAPELLIDO=N'Duque' WHERE PERSONAID=97574;
UPDATE PERSONA SET PERSONANOMBRES=N'Edder Alcides', PERSONAPRIMERAPELLIDO=N'Parody', PERSONASEGUNDOAPELLIDO=N'Camargo' WHERE PERSONAID=97579;
UPDATE PERSONA SET PERSONANOMBRES=N'Francisco Javier', PERSONAPRIMERAPELLIDO=N'Arazo', PERSONASEGUNDOAPELLIDO=N'Gómez' WHERE PERSONAID=97591;
UPDATE PERSONA SET PERSONANOMBRES=N'Martha Elizabeth', PERSONAPRIMERAPELLIDO=N'Cortes', PERSONASEGUNDOAPELLIDO=N'Rico' WHERE PERSONAID=97601;
UPDATE PERSONA SET PERSONANOMBRES=N'Mario Andres', PERSONAPRIMERAPELLIDO=N'Rodriguez', PERSONASEGUNDOAPELLIDO=N'Lopez' WHERE PERSONAID=117346;
UPDATE PERSONA SET PERSONANOMBRES=N'David Alexander', PERSONAPRIMERAPELLIDO=N'Fique', PERSONASEGUNDOAPELLIDO=N'Pardo' WHERE PERSONAID=131958;
UPDATE PERSONA SET PERSONANOMBRES=N'Sandra Patricia de la Concepcion', PERSONAPRIMERAPELLIDO=N'Barón', PERSONASEGUNDOAPELLIDO=N'Flórez' WHERE PERSONAID=133978;
UPDATE PERSONA SET PERSONANOMBRES=N'Zulma Rocio', PERSONAPRIMERAPELLIDO=N'Gomez', PERSONASEGUNDOAPELLIDO=N'Galeón' WHERE PERSONAID=134190;
UPDATE PERSONA SET PERSONANOMBRES=N'Diana Paola', PERSONAPRIMERAPELLIDO=N'Ballesteros', PERSONASEGUNDOAPELLIDO=N'Riveros' WHERE PERSONAID=141580;
UPDATE PERSONA SET PERSONANOMBRES=N'Maritza', PERSONAPRIMERAPELLIDO=N'Valencia', PERSONASEGUNDOAPELLIDO=N'Gonzalez' WHERE PERSONAID=144938;
UPDATE PERSONA SET PERSONANOMBRES=N'Alejandro', PERSONAPRIMERAPELLIDO=N'Arias', PERSONASEGUNDOAPELLIDO=N'Osorio' WHERE PERSONAID=186159;
UPDATE PERSONA SET PERSONANOMBRES=N'Sandra Milena', PERSONAPRIMERAPELLIDO=N'Reyes', PERSONASEGUNDOAPELLIDO=N'Ibañez' WHERE PERSONAID=192090;
UPDATE PERSONA SET PERSONANOMBRES=N'Aline Isabel', PERSONAPRIMERAPELLIDO=N'Melo', PERSONASEGUNDOAPELLIDO=N'Henríquez' WHERE PERSONAID=192372;
UPDATE PERSONA SET PERSONANOMBRES=N'Hugo Armando', PERSONAPRIMERAPELLIDO=N'Maturana', PERSONASEGUNDOAPELLIDO=N'Mosquera' WHERE PERSONAID=233480;

COMMIT;

-- REVERSA: docs/migraciones/v62_REVERSA_nombres_evaluadores.sql
