-- v69 — las 39 tablas del SEP que faltan en el Exadata del SENA.
--
-- Generado desde SEPLOCAL leyendo el diccionario, y contrastado contra SENADM:
-- ningun nombre que ya exista alla se emite. Crea SOLO estructura, ninguna fila.
--
-- ES ADITIVO: no toca ni una tabla, indice o secuencia que ya exista en el SENA.
-- Reversa: DROP de estas 39 tablas en orden inverso y de sus 26 secuencias.
--
-- El DDL de Oracle hace COMMIT implicito en cada sentencia: esto NO se puede
-- envolver en una transaccion. Si falla a la mitad, lo creado se queda creado y
-- hay que revertir a mano. Correr con un cliente que ABORTE al primer error
-- (sqlplus: WHENEVER SQLERROR EXIT FAILURE, que va abajo).
--
-- Correr como SENADM.

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET DEFINE OFF;


-- ========== 1. LAS 39 TABLAS, en orden topologico de llaves ==========

CREATE TABLE "AREAEVALUACION" (
  "AREAID" NUMBER(10,0) NOT NULL,
  "CODIGO" NVARCHAR2(30) NOT NULL,
  "NOMBRE" NVARCHAR2(80) NOT NULL,
  "GRUPOSDEFECTO" NVARCHAR2(60),
  "ORDEN" NUMBER(3,0) DEFAULT 100 NOT NULL,
  "ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  CONSTRAINT "PK_AREAEVALUACION" PRIMARY KEY ("AREAID"),
  CONSTRAINT "UQ_AREAEVAL_CODIGO" UNIQUE ("CODIGO")
);

CREATE TABLE "ARTICULACIONTERRITORIAL" (
  "ARTICULACIONTERRITORIALID" NUMBER NOT NULL,
  "ARTICULACIONTERRITORIALNOMBRE" NVARCHAR2(400) NOT NULL,
  "ARTICULACIONTERRITORIALESTADO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  CONSTRAINT "PK_ARTTERRDES" PRIMARY KEY ("ARTICULACIONTERRITORIALID")
);

CREATE TABLE "CONVPROYGUARDADO" (
  "GUARDADOID" NUMBER(10,0) NOT NULL,
  "CONVOCATORIAID" NUMBER(10,0) NOT NULL,
  "NIT" NVARCHAR2(30),
  "RAZONSOCIAL" NVARCHAR2(300),
  "NOMBREPROYECTO" NVARCHAR2(400),
  "MODALIDAD" NVARCHAR2(60),
  "NUMAF" NUMBER(6,0) DEFAULT 0 NOT NULL,
  "NUMBENEF" NUMBER(10,0) DEFAULT 0 NOT NULL,
  "VALORTOTAL" NUMBER(18,2) DEFAULT 0 NOT NULL,
  "COFINSENA" NUMBER(18,2) DEFAULT 0 NOT NULL,
  "USUARIOID" NUMBER(10,0),
  "FECHAGUARDADO" DATE DEFAULT SYSDATE NOT NULL,
  "DATOSJSON" CLOB NOT NULL,
  CONSTRAINT "PK_CONVPROYGUARDADO" PRIMARY KEY ("GUARDADOID")
);

CREATE TABLE "ESTADOPARTICIPACION" (
  "ESTADOPARTID" NUMBER(10,0) NOT NULL,
  "CODIGO" NVARCHAR2(30) NOT NULL,
  "NOMBRE" NVARCHAR2(80) NOT NULL,
  "DESCRIPCION" NVARCHAR2(300),
  "COLOR" NVARCHAR2(20) DEFAULT N'neutral' NOT NULL,
  "ORDEN" NUMBER(3,0) DEFAULT 100 NOT NULL,
  "ESFINAL" NUMBER(1,0) DEFAULT 0 NOT NULL,
  "ESNEGATIVO" NUMBER(1,0) DEFAULT 0 NOT NULL,
  "ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  CONSTRAINT "PK_ESTADOPARTICIPACION" PRIMARY KEY ("ESTADOPARTID"),
  CONSTRAINT "UQ_ESTADOPART_CODIGO" UNIQUE ("CODIGO")
);

CREATE TABLE "EVALUADOR" (
  "EVALUADORID" NUMBER NOT NULL,
  "PERSONAID" NUMBER NOT NULL,
  "CENTROID" NUMBER,
  "REGIONALID" NUMBER,
  "EVALUADORCARGO" VARCHAR2(120),
  "EVALUADORPROFESION" VARCHAR2(200),
  "EVALUADORPOSGRADO" VARCHAR2(400),
  "EVALUADORFOTO" BLOB,
  "EVALUADORFOTOMIME" VARCHAR2(40),
  "EVALUADORACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  "FECHACREACION" TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  "EVALUADORFOTONOMBRE" VARCHAR2(255),
  "EVALUADORJEFENOMBRE" NVARCHAR2(200),
  "EVALUADORJEFEEMAIL" NVARCHAR2(150),
  "EVALUADORJEFECARGO" NVARCHAR2(150),
  "EVALUADORMUNICIPIOID" NUMBER(22,0),
  "USUARIOCREACION" NVARCHAR2(200),
  "USUARIOMODIFICACION" NVARCHAR2(200),
  "FECHAMODIFICACION" DATE,
  "EVALUADORFOTOMINI" BLOB,
  CONSTRAINT "PK_EVALUADOR" PRIMARY KEY ("EVALUADORID"),
  CONSTRAINT "UQ_EVALUADOR_PERSONA" UNIQUE ("PERSONAID")
);

CREATE TABLE "EVALUADOREXPERIENCIA" (
  "EXPERIENCIAID" NUMBER NOT NULL,
  "EVALUADORID" NUMBER NOT NULL,
  "CARGOEXP" VARCHAR2(200),
  "ENTIDADEXP" VARCHAR2(200),
  "FECHAINICIO" DATE,
  "FECHAFIN" DATE,
  "ARCHIVOPDF" BLOB,
  "ARCHIVOMIME" VARCHAR2(40),
  "ARCHIVONOMBRE" VARCHAR2(200),
  "USUARIOCREACION" NVARCHAR2(200),
  "FECHACARGUE" DATE DEFAULT SYSDATE,
  CONSTRAINT "PK_EVALUADOREXPERIENCIA" PRIMARY KEY ("EXPERIENCIAID")
);

ALTER TABLE "EVALUADOREXPERIENCIA" ADD CONSTRAINT "FK_EXP_EVALUADOR" FOREIGN KEY ("EVALUADORID") REFERENCES "EVALUADOR" ("EVALUADORID");

CREATE TABLE "EVALUADORLOG" (
  "EVALUADORLOGID" NUMBER(10,0) NOT NULL,
  "EVALUADORID" NUMBER(10,0),
  "PARTICIPACIONID" NUMBER(10,0),
  "TABLA" NVARCHAR2(60) NOT NULL,
  "OPERACION" NVARCHAR2(20) NOT NULL,
  "REGISTROID" NUMBER(10,0),
  "USUARIOEMAIL" NVARCHAR2(200) NOT NULL,
  "USUARIOPERFILID" NUMBER(10,0),
  "FECHA" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  "COMENTARIO" NVARCHAR2(1000),
  "VALORANTES" NCLOB,
  "VALORDESPUES" NCLOB,
  CONSTRAINT "PK_EVALUADORLOG" PRIMARY KEY ("EVALUADORLOGID"),
  CONSTRAINT "CK_EVALLOG_OPER" CHECK (OPERACION IN (N'INSERT', N'UPDATE', N'DELETE', N'ESTADO', N'GENERAR', N'ANULAR', N'EMITIR'))
);

CREATE TABLE "EVALUADORTIC" (
  "TICID" NUMBER NOT NULL,
  "EVALUADORID" NUMBER NOT NULL,
  "TIPOEVENTOID" NUMBER,
  "TICNOMBRE" VARCHAR2(200) NOT NULL,
  "TICHORAS" NUMBER,
  "FECHAFIN" DATE,
  "ARCHIVOPDF" BLOB,
  "ARCHIVOMIME" VARCHAR2(40),
  "ARCHIVONOMBRE" VARCHAR2(200),
  "USUARIOCREACION" NVARCHAR2(200),
  "FECHACARGUE" DATE DEFAULT SYSDATE,
  CONSTRAINT "PK_EVALUADORTIC" PRIMARY KEY ("TICID")
);

ALTER TABLE "EVALUADORTIC" ADD CONSTRAINT "FK_TIC_EVALUADOR" FOREIGN KEY ("EVALUADORID") REFERENCES "EVALUADOR" ("EVALUADORID");

CREATE TABLE "MODALIDADPART" (
  "MODALIDADPARTID" NUMBER(10,0) NOT NULL,
  "CODIGO" NVARCHAR2(30) NOT NULL,
  "NOMBRE" NVARCHAR2(80) NOT NULL,
  "DESCRIPCION" NVARCHAR2(300),
  "ORDEN" NUMBER(3,0) DEFAULT 100 NOT NULL,
  "ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  CONSTRAINT "PK_MODALIDADPART" PRIMARY KEY ("MODALIDADPARTID"),
  CONSTRAINT "UQ_MODALIDADPART_CODIGO" UNIQUE ("CODIGO")
);

CREATE TABLE "PROCESOEVAL" (
  "PROCESOID" NUMBER NOT NULL,
  "PROCESONOMBRE" VARCHAR2(80) NOT NULL,
  "PROCESODESC" VARCHAR2(200),
  "PROCESOACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  CONSTRAINT "PK_PROCESOEVAL" PRIMARY KEY ("PROCESOID"),
  CONSTRAINT "UQ_PROCESOEVAL_NOMBRE" UNIQUE ("PROCESONOMBRE")
);

CREATE TABLE "PROYECTOVERSION" (
  "PROYECTOVERSIONID" NUMBER NOT NULL,
  "PROYECTOID" NUMBER NOT NULL,
  "VERSIONNUMERO" NUMBER NOT NULL,
  "VERSIONCODIGO" VARCHAR2(60) NOT NULL,
  "VERSIONFECHA" TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  "VERSIONUSUARIO" VARCHAR2(200),
  "VERSIONSNAPSHOT" CLOB NOT NULL,
  "VERSIONHASH" VARCHAR2(64),
  "VERSIONESTADOAL" NUMBER DEFAULT 1,
  "VERSIONCOMENTARIO" VARCHAR2(2000),
  "VERSIONESFINAL" NUMBER(1,0) DEFAULT 0 NOT NULL,
  "VERSIONANULADA" NUMBER(1,0) DEFAULT 0 NOT NULL,
  "VERSIONFINALFECHA" TIMESTAMP(6),
  "VERSIONFINALUSUARIO" VARCHAR2(200),
  "VERSIONANULADAFECHA" TIMESTAMP(6),
  "VERSIONANULADAUSUARIO" VARCHAR2(200),
  CONSTRAINT "PK_PROYECTOVERSION" PRIMARY KEY ("PROYECTOVERSIONID"),
  CONSTRAINT "UQ_PROYECTOVERSION_COD" UNIQUE ("VERSIONCODIGO"),
  CONSTRAINT "UQ_PROYECTOVERSION_NUM" UNIQUE ("PROYECTOID", "VERSIONNUMERO")
);

CREATE TABLE "REGIONAL" (
  "REGIONALID" NUMBER(10,0) NOT NULL,
  "REGIONALNOMBRE" NVARCHAR2(120) NOT NULL,
  "REGIONALACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  CONSTRAINT "PK_REGIONAL" PRIMARY KEY ("REGIONALID")
);

CREATE TABLE "RETONACIONAL" (
  "RETONACIONALID" NUMBER NOT NULL,
  "RETONACIONALNOMBRE" NVARCHAR2(600) NOT NULL,
  "RETONACIONALESTADO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  CONSTRAINT "PK_RETONACIONAL" PRIMARY KEY ("RETONACIONALID")
);

CREATE TABLE "ROLEVALUADOR" (
  "ROLEVALUADORID" NUMBER NOT NULL,
  "ROLEVALUADORNOMBRE" VARCHAR2(80) NOT NULL,
  "ROLEVALUADORDESC" VARCHAR2(200),
  "ROLEVALUADORACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  "ROLEVALUADORCODIGO" NVARCHAR2(40),
  "ROLEVALUADORORDEN" NUMBER(3,0) DEFAULT 100,
  "AREAID" NUMBER(10,0),
  CONSTRAINT "PK_ROLEVALUADOR" PRIMARY KEY ("ROLEVALUADORID"),
  CONSTRAINT "UQ_ROLEVALUADOR_NOMBRE" UNIQUE ("ROLEVALUADORNOMBRE")
);

ALTER TABLE "ROLEVALUADOR" ADD CONSTRAINT "FK_ROLEVAL_AREA" FOREIGN KEY ("AREAID") REFERENCES "AREAEVALUACION" ("AREAID");

CREATE TABLE "TIPODOCUMENTOCONV" (
  "TIPODOCUMENTOCONVID" NUMBER(10,0) NOT NULL,
  "CODIGO" NVARCHAR2(40) NOT NULL,
  "NOMBRE" NVARCHAR2(120) NOT NULL,
  "EXTENSIONESPERMITIDAS" NVARCHAR2(120) DEFAULT N'pdf' NOT NULL,
  "ORDEN" NUMBER(3,0) DEFAULT 100 NOT NULL,
  "ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  CONSTRAINT "PK_TIPODOCCONV" PRIMARY KEY ("TIPODOCUMENTOCONVID"),
  CONSTRAINT "UQ_TIPODOCCONV_CODIGO" UNIQUE ("CODIGO")
);

CREATE TABLE "TIPODOCUMENTOEVAL" (
  "TIPODOCUMENTOEVALID" NUMBER(10,0) NOT NULL,
  "CODIGO" NVARCHAR2(40) NOT NULL,
  "NOMBRE" NVARCHAR2(120) NOT NULL,
  "ADMITEMULTIPLE" NUMBER(1,0) DEFAULT 1 NOT NULL,
  "ORDEN" NUMBER(3,0) DEFAULT 100 NOT NULL,
  "ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  CONSTRAINT "PK_TIPODOCEVAL" PRIMARY KEY ("TIPODOCUMENTOEVALID"),
  CONSTRAINT "UQ_TIPODOCEVAL_CODIGO" UNIQUE ("CODIGO")
);

CREATE TABLE "TIPOESTUDIO" (
  "TIPOESTUDIOID" NUMBER NOT NULL,
  "TIPOESTUDIONOMBRE" VARCHAR2(80) NOT NULL,
  "TIPOESTUDIOACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  CONSTRAINT "PK_TIPOESTUDIO" PRIMARY KEY ("TIPOESTUDIOID"),
  CONSTRAINT "UQ_TIPOESTUDIO_NOMBRE" UNIQUE ("TIPOESTUDIONOMBRE")
);

CREATE TABLE "USUARIOPERFIL" (
  "USUARIOPERFILID" NUMBER NOT NULL,
  "USUARIOID" NUMBER NOT NULL,
  "PERFILID" NUMBER NOT NULL,
  "PREDETERMINADO" NUMBER(1,0) DEFAULT 0 NOT NULL,
  "ESTADO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  "FECHAULTIMOACCESO" TIMESTAMP(6),
  "FECHACREACION" TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT "PK_USUARIOPERFIL" PRIMARY KEY ("USUARIOPERFILID"),
  CONSTRAINT "UQ_USUARIOPERFIL_UP" UNIQUE ("USUARIOID", "PERFILID")
);

CREATE TABLE "CENTROFORMACION" (
  "CENTROID" NUMBER(10,0) NOT NULL,
  "REGIONALID" NUMBER(10,0) NOT NULL,
  "CENTRONOMBRE" NVARCHAR2(300) NOT NULL,
  "CIUDADID" NUMBER(22,0),
  "CENTROACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  CONSTRAINT "PK_CENTROFORMACION" PRIMARY KEY ("CENTROID")
);

ALTER TABLE "CENTROFORMACION" ADD CONSTRAINT "FK_CF_REGIONAL" FOREIGN KEY ("REGIONALID") REFERENCES "REGIONAL" ("REGIONALID");

CREATE TABLE "EVALUADORCONVOCATORIA" (
  "CONVOCATORIAID" NUMBER(10,0) NOT NULL,
  "ANIO" NUMBER(4,0) NOT NULL,
  "PERIODO" NVARCHAR2(4),
  "NOMBRE" NVARCHAR2(200) NOT NULL,
  "FECHAINICIO" DATE,
  "FECHAFIN" DATE,
  "OBSERVACIONES" NVARCHAR2(1000),
  "ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  "FECHACREACION" DATE DEFAULT SYSDATE NOT NULL,
  "CONVOCATORIASEPID" NUMBER(10,0),
  "MODALIDADPARTID" NUMBER(10,0),
  "PUNTAJEMINIMOPRUEBA" NUMBER(5,2),
  "CALIFICACIONMINIMACURSO" NUMBER(5,2),
  "USUARIOCREACION" NVARCHAR2(200),
  "USUARIOMODIFICACION" NVARCHAR2(200),
  "FECHAMODIFICACION" DATE,
  "CERTIFICADOTEXTO" NCLOB,
  "CERTIFICADOFIRMAID" NUMBER(10,0),
  "CERTIFICADOHABILITADO" NUMBER(1,0) DEFAULT 0,
  CONSTRAINT "PK_EVALUADORCONVOCATORIA" PRIMARY KEY ("CONVOCATORIAID")
);

ALTER TABLE "EVALUADORCONVOCATORIA" ADD CONSTRAINT "FK_CONV_MODALIDAD" FOREIGN KEY ("MODALIDADPARTID") REFERENCES "MODALIDADPART" ("MODALIDADPARTID");

CREATE TABLE "EVALUADORESTUDIO" (
  "ESTUDIOID" NUMBER NOT NULL,
  "EVALUADORID" NUMBER NOT NULL,
  "TIPOESTUDIOID" NUMBER NOT NULL,
  "ESTUDIOTITULO" VARCHAR2(200),
  "INSTITUCION" VARCHAR2(200),
  "FECHAGRADO" DATE,
  "ARCHIVOPDF" BLOB,
  "ARCHIVOMIME" VARCHAR2(40),
  "ARCHIVONOMBRE" VARCHAR2(200),
  "FECHACARGUE" TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  "USUARIOCREACION" NVARCHAR2(200),
  CONSTRAINT "PK_EVALUADORESTUDIO" PRIMARY KEY ("ESTUDIOID")
);

ALTER TABLE "EVALUADORESTUDIO" ADD CONSTRAINT "FK_ESTUDIO_EVALUADOR" FOREIGN KEY ("EVALUADORID") REFERENCES "EVALUADOR" ("EVALUADORID");

ALTER TABLE "EVALUADORESTUDIO" ADD CONSTRAINT "FK_ESTUDIO_TIPO" FOREIGN KEY ("TIPOESTUDIOID") REFERENCES "TIPOESTUDIO" ("TIPOESTUDIOID");

CREATE TABLE "EVALUADORPARTICIPACION" (
  "PARTICIPACIONID" NUMBER NOT NULL,
  "EVALUADORID" NUMBER NOT NULL,
  "ANIO" NUMBER(4,0) NOT NULL,
  "PERIODO" CHAR(2),
  "ROLEVALUADORID" NUMBER,
  "PROCESOID" NUMBER,
  "MESA" VARCHAR2(500),
  "EQUIPOEVALUADOR" VARCHAR2(500),
  "DINAMIZADORPERSONAID" NUMBER,
  "RETROALIMENTACION" CLOB,
  "OBSERVACIONES" CLOB,
  "CONVOCATORIAID" NUMBER(10,0),
  "ESTADOPARTID" NUMBER(10,0),
  "AREAID" NUMBER(10,0),
  "MODALIDADPARTID" NUMBER(10,0),
  "ESTRANSVERSAL" NUMBER(1,0) DEFAULT 0,
  "MOTIVONOPARTICIPA" NVARCHAR2(300),
  "FECHAINICIO" DATE,
  "FECHAFIN" DATE,
  "USUARIOCREACION" NVARCHAR2(200),
  "FECHACREACION" DATE DEFAULT SYSDATE,
  "USUARIOMODIFICACION" NVARCHAR2(200),
  "FECHAMODIFICACION" DATE,
  "DINAMIZADOR" VARCHAR2(500),
  CONSTRAINT "PK_EVALUADORPARTICIPACION" PRIMARY KEY ("PARTICIPACIONID")
);

ALTER TABLE "EVALUADORPARTICIPACION" ADD CONSTRAINT "FK_PART_AREA" FOREIGN KEY ("AREAID") REFERENCES "AREAEVALUACION" ("AREAID");

ALTER TABLE "EVALUADORPARTICIPACION" ADD CONSTRAINT "FK_PART_CONVOCATORIA" FOREIGN KEY ("CONVOCATORIAID") REFERENCES "EVALUADORCONVOCATORIA" ("CONVOCATORIAID");

ALTER TABLE "EVALUADORPARTICIPACION" ADD CONSTRAINT "FK_PART_ESTADO" FOREIGN KEY ("ESTADOPARTID") REFERENCES "ESTADOPARTICIPACION" ("ESTADOPARTID");

ALTER TABLE "EVALUADORPARTICIPACION" ADD CONSTRAINT "FK_PART_EVALUADOR" FOREIGN KEY ("EVALUADORID") REFERENCES "EVALUADOR" ("EVALUADORID");

ALTER TABLE "EVALUADORPARTICIPACION" ADD CONSTRAINT "FK_PART_MODALIDAD" FOREIGN KEY ("MODALIDADPARTID") REFERENCES "MODALIDADPART" ("MODALIDADPARTID");

ALTER TABLE "EVALUADORPARTICIPACION" ADD CONSTRAINT "FK_PART_PROCESO" FOREIGN KEY ("PROCESOID") REFERENCES "PROCESOEVAL" ("PROCESOID");

ALTER TABLE "EVALUADORPARTICIPACION" ADD CONSTRAINT "FK_PART_ROL" FOREIGN KEY ("ROLEVALUADORID") REFERENCES "ROLEVALUADOR" ("ROLEVALUADORID");

CREATE TABLE "EVALUADORPARTPROYECTO" (
  "PARTPROYECTOID" NUMBER(10,0) NOT NULL,
  "PARTICIPACIONID" NUMBER(10,0) NOT NULL,
  "PROYECTOID" NUMBER(10,0),
  "GUARDADOID" NUMBER(10,0),
  "NIT" NVARCHAR2(30),
  "RAZONSOCIAL" NVARCHAR2(300),
  "NOMBREPROYECTO" NVARCHAR2(400),
  "PUNTAJEOTORGADO" NUMBER(5,2),
  "FECHAEVALUACION" DATE,
  "OBSERVACIONES" NVARCHAR2(1000),
  "USUARIOCREACION" NVARCHAR2(200),
  "FECHACREACION" DATE DEFAULT SYSDATE NOT NULL,
  "USUARIOMODIFICACION" NVARCHAR2(200),
  "FECHAMODIFICACION" DATE,
  CONSTRAINT "PK_EVALUADORPARTPROYECTO" PRIMARY KEY ("PARTPROYECTOID"),
  CONSTRAINT "CK_PARTPROY_REF" CHECK (PROYECTOID IS NOT NULL OR GUARDADOID IS NOT NULL OR NOMBREPROYECTO IS NOT NULL OR RAZONSOCIAL IS NOT NULL)
);

ALTER TABLE "EVALUADORPARTPROYECTO" ADD CONSTRAINT "FK_PARTPROY_PART" FOREIGN KEY ("PARTICIPACIONID") REFERENCES "EVALUADORPARTICIPACION" ("PARTICIPACIONID");

CREATE TABLE "EVALUADORPRUEBA" (
  "PRUEBAID" NUMBER NOT NULL,
  "EVALUADORID" NUMBER NOT NULL,
  "ANIO" NUMBER(4,0) NOT NULL,
  "PERIODO" CHAR(2),
  "FECHAPRESENTACION" DATE,
  "HORARIO" VARCHAR2(40),
  "INTENTOS" NUMBER,
  "PUNTAJEMAYOR" NUMBER(5,2),
  "PRUEBANUMERO" NUMBER,
  "EFECTIVIDAD" NUMBER(5,2),
  "CORRECTAS" NUMBER,
  "INCORRECTAS" NUMBER,
  "TOTALTIEMPO" VARCHAR2(40),
  "OBSERVACION" VARCHAR2(400),
  "PARTICIPACIONID" NUMBER(10,0),
  "APROBADA" NUMBER(1,0),
  "PUNTAJEMINIMO" NUMBER(5,2),
  "USUARIOCREACION" NVARCHAR2(200),
  "FECHACREACION" DATE DEFAULT SYSDATE,
  CONSTRAINT "PK_EVALUADORPRUEBA" PRIMARY KEY ("PRUEBAID")
);

ALTER TABLE "EVALUADORPRUEBA" ADD CONSTRAINT "FK_PRUEBA_EVALUADOR" FOREIGN KEY ("EVALUADORID") REFERENCES "EVALUADOR" ("EVALUADORID");

ALTER TABLE "EVALUADORPRUEBA" ADD CONSTRAINT "FK_PRUEBA_PART" FOREIGN KEY ("PARTICIPACIONID") REFERENCES "EVALUADORPARTICIPACION" ("PARTICIPACIONID");

CREATE TABLE "PROYECTOAPROBADO" (
  "PROYECTOID" NUMBER NOT NULL,
  "PROYECTOVERSIONID" NUMBER NOT NULL,
  "VERSIONCODIGO" VARCHAR2(60) NOT NULL,
  "VERSIONHASH" VARCHAR2(64) NOT NULL,
  "FECHAAPROBACION" TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  "USUARIOAPROBO" VARCHAR2(200),
  "COMENTARIOAPROBACION" VARCHAR2(2000),
  CONSTRAINT "PK_PROYECTOAPROBADO" PRIMARY KEY ("PROYECTOID")
);

ALTER TABLE "PROYECTOAPROBADO" ADD CONSTRAINT "FK_PROYECTOAPROBADO_VER" FOREIGN KEY ("PROYECTOVERSIONID") REFERENCES "PROYECTOVERSION" ("PROYECTOVERSIONID");

CREATE TABLE "RETROFORMULARIO" (
  "RETROFORMULARIOID" NUMBER(10,0) NOT NULL,
  "CONVOCATORIAID" NUMBER(10,0),
  "NOMBRE" NVARCHAR2(200) NOT NULL,
  "VERSION" NUMBER(3,0) DEFAULT 1 NOT NULL,
  "ANIO" NUMBER(4,0),
  "ESCALAMIN" NUMBER(3,0) DEFAULT 1 NOT NULL,
  "ESCALAMAX" NUMBER(3,0) DEFAULT 5 NOT NULL,
  "DURACIONMINUTOS" NUMBER(4,0) DEFAULT 60 NOT NULL,
  "RESULTADOANONIMO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  "ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  "ABIERTO" NUMBER(1,0) DEFAULT 0 NOT NULL,
  "FECHAAPERTURA" DATE,
  "FECHACIERRE" DATE,
  "REGLASMATRIZ" NCLOB,
  "USUARIOCREACION" NVARCHAR2(200),
  "FECHACREACION" DATE DEFAULT SYSDATE NOT NULL,
  "USUARIOMODIFICACION" NVARCHAR2(200),
  "FECHAMODIFICACION" DATE,
  "ESCALAETIQUETAS" NVARCHAR2(400),
  CONSTRAINT "PK_RETROFORMULARIO" PRIMARY KEY ("RETROFORMULARIOID")
);

ALTER TABLE "RETROFORMULARIO" ADD CONSTRAINT "FK_RETROFORM_CONV" FOREIGN KEY ("CONVOCATORIAID") REFERENCES "EVALUADORCONVOCATORIA" ("CONVOCATORIAID");

CREATE TABLE "RETROPREGUNTA" (
  "RETROPREGUNTAID" NUMBER(10,0) NOT NULL,
  "RETROFORMULARIOID" NUMBER(10,0) NOT NULL,
  "NUMERO" NUMBER(3,0) NOT NULL,
  "TEXTO" NVARCHAR2(1000) NOT NULL,
  "CRITERIOS" NVARCHAR2(300),
  "TIPO" NVARCHAR2(30) NOT NULL,
  "PESO" NUMBER(5,2) DEFAULT 0 NOT NULL,
  "REQUERIDA" NUMBER(1,0) DEFAULT 0 NOT NULL,
  "ORDEN" NUMBER(3,0) DEFAULT 100 NOT NULL,
  "ACTIVO" NUMBER(1,0) DEFAULT 1 NOT NULL,
  CONSTRAINT "PK_RETROPREGUNTA" PRIMARY KEY ("RETROPREGUNTAID"),
  CONSTRAINT "UQ_RETROPREG_NUM" UNIQUE ("RETROFORMULARIOID", "NUMERO"),
  CONSTRAINT "CK_RETROPREG_TIPO" CHECK (TIPO IN (N'ESCALA', N'TEXTO_POR_PERSONA', N'TEXTO_GENERAL'))
);

ALTER TABLE "RETROPREGUNTA" ADD CONSTRAINT "FK_RETROPREG_FORM" FOREIGN KEY ("RETROFORMULARIOID") REFERENCES "RETROFORMULARIO" ("RETROFORMULARIOID");

CREATE TABLE "RETROSESION" (
  "RETROSESIONID" NUMBER(10,0) NOT NULL,
  "RETROFORMULARIOID" NUMBER(10,0) NOT NULL,
  "PARTICIPACIONID" NUMBER(10,0) NOT NULL,
  "FECHAINICIO" DATE DEFAULT SYSDATE NOT NULL,
  "FECHAENVIO" DATE,
  "DURACIONMINUTOS" NUMBER(4,0) DEFAULT 60 NOT NULL,
  "MINUTOSTRANSCURRIDOS" NUMBER(6,0),
  "SEEXCEDIO" NUMBER(1,0) DEFAULT 0 NOT NULL,
  "IPORIGEN" NVARCHAR2(60),
  "USUARIOEMAIL" NVARCHAR2(200),
  CONSTRAINT "PK_RETROSESION" PRIMARY KEY ("RETROSESIONID")
);

ALTER TABLE "RETROSESION" ADD CONSTRAINT "FK_RETROSES_FORM" FOREIGN KEY ("RETROFORMULARIOID") REFERENCES "RETROFORMULARIO" ("RETROFORMULARIOID");

ALTER TABLE "RETROSESION" ADD CONSTRAINT "FK_RETROSES_PART" FOREIGN KEY ("PARTICIPACIONID") REFERENCES "EVALUADORPARTICIPACION" ("PARTICIPACIONID");

CREATE TABLE "RETROSUGERENCIA" (
  "RETROSUGERENCIAID" NUMBER(10,0) NOT NULL,
  "RETROSESIONID" NUMBER(10,0) NOT NULL,
  "RETROPREGUNTAID" NUMBER(10,0),
  "PARTICIPACIONID" NUMBER(10,0) NOT NULL,
  "TEXTO" NCLOB,
  "FECHAENVIO" DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT "PK_RETROSUGERENCIA" PRIMARY KEY ("RETROSUGERENCIAID"),
  CONSTRAINT "UQ_RETROSUG_SES" UNIQUE ("RETROSESIONID")
);

ALTER TABLE "RETROSUGERENCIA" ADD CONSTRAINT "FK_RETROSUG_PART" FOREIGN KEY ("PARTICIPACIONID") REFERENCES "EVALUADORPARTICIPACION" ("PARTICIPACIONID");

ALTER TABLE "RETROSUGERENCIA" ADD CONSTRAINT "FK_RETROSUG_PREG" FOREIGN KEY ("RETROPREGUNTAID") REFERENCES "RETROPREGUNTA" ("RETROPREGUNTAID");

ALTER TABLE "RETROSUGERENCIA" ADD CONSTRAINT "FK_RETROSUG_SES" FOREIGN KEY ("RETROSESIONID") REFERENCES "RETROSESION" ("RETROSESIONID");

CREATE TABLE "CONVOCATORIADOCUMENTO" (
  "DOCUMENTOID" NUMBER(10,0) NOT NULL,
  "CONVOCATORIAID" NUMBER(10,0) NOT NULL,
  "TIPODOCUMENTOCONVID" NUMBER(10,0) NOT NULL,
  "DOCUMENTODESCRIPCION" NVARCHAR2(300),
  "ARCHIVOBLOB" BLOB NOT NULL,
  "ARCHIVOMIME" NVARCHAR2(120) NOT NULL,
  "ARCHIVONOMBRE" NVARCHAR2(255),
  "FECHACARGUE" DATE DEFAULT SYSDATE NOT NULL,
  "USUARIOCREACION" NVARCHAR2(200),
  CONSTRAINT "PK_CONVOCATORIADOCUMENTO" PRIMARY KEY ("DOCUMENTOID")
);

ALTER TABLE "CONVOCATORIADOCUMENTO" ADD CONSTRAINT "FK_CONVDOC_CONV" FOREIGN KEY ("CONVOCATORIAID") REFERENCES "EVALUADORCONVOCATORIA" ("CONVOCATORIAID");

ALTER TABLE "CONVOCATORIADOCUMENTO" ADD CONSTRAINT "FK_CONVDOC_TIPO" FOREIGN KEY ("TIPODOCUMENTOCONVID") REFERENCES "TIPODOCUMENTOCONV" ("TIPODOCUMENTOCONVID");

CREATE TABLE "EVALUADORAPROBACION" (
  "APROBACIONID" NUMBER(10,0) NOT NULL,
  "PARTICIPACIONID" NUMBER(10,0) NOT NULL,
  "APROBADORNOMBRE" NVARCHAR2(200) NOT NULL,
  "APROBADOREMAIL" NVARCHAR2(150) NOT NULL,
  "APROBADORCARGO" NVARCHAR2(150),
  "FECHAAPROBACION" DATE NOT NULL,
  "CORREOEVIDENCIA" BLOB,
  "CORREOEVIDENCIAMIME" NVARCHAR2(120),
  "CORREOEVIDENCIANOMBRE" NVARCHAR2(255),
  "OBSERVACIONES" NVARCHAR2(1000),
  "USUARIOCREACION" NVARCHAR2(200),
  "FECHACREACION" DATE DEFAULT SYSDATE NOT NULL,
  "USUARIOMODIFICACION" NVARCHAR2(200),
  "FECHAMODIFICACION" DATE,
  CONSTRAINT "PK_EVALUADORAPROBACION" PRIMARY KEY ("APROBACIONID"),
  CONSTRAINT "UQ_APROB_PARTICIPACION" UNIQUE ("PARTICIPACIONID")
);

ALTER TABLE "EVALUADORAPROBACION" ADD CONSTRAINT "FK_APROB_PART" FOREIGN KEY ("PARTICIPACIONID") REFERENCES "EVALUADORPARTICIPACION" ("PARTICIPACIONID");

CREATE TABLE "EVALUADORCAPACITACION" (
  "CAPACITACIONID" NUMBER(10,0) NOT NULL,
  "PARTICIPACIONID" NUMBER(10,0) NOT NULL,
  "NOMBRE" NVARCHAR2(200) NOT NULL,
  "ORIGEN" NVARCHAR2(20) DEFAULT N'EXTERNO' NOT NULL,
  "PLATAFORMA" NVARCHAR2(80),
  "HORAS" NUMBER(5,0),
  "FECHAINICIO" DATE,
  "FECHAFIN" DATE,
  "CALIFICACION" NUMBER(5,2),
  "CALIFICACIONMINIMA" NUMBER(5,2),
  "APROBADO" NUMBER(1,0) DEFAULT 0 NOT NULL,
  "INTENTOS" NUMBER(3,0),
  "ARCHIVOPDF" BLOB,
  "ARCHIVOMIME" NVARCHAR2(120),
  "ARCHIVONOMBRE" NVARCHAR2(255),
  "OBSERVACIONES" NVARCHAR2(1000),
  "USUARIOCREACION" NVARCHAR2(200),
  "FECHACREACION" DATE DEFAULT SYSDATE NOT NULL,
  "USUARIOMODIFICACION" NVARCHAR2(200),
  "FECHAMODIFICACION" DATE,
  CONSTRAINT "PK_EVALUADORCAPACITACION" PRIMARY KEY ("CAPACITACIONID"),
  CONSTRAINT "CK_CAPAC_ORIGEN" CHECK (ORIGEN IN (N'EXTERNO', N'SISTEMA'))
);

ALTER TABLE "EVALUADORCAPACITACION" ADD CONSTRAINT "FK_CAPAC_PART" FOREIGN KEY ("PARTICIPACIONID") REFERENCES "EVALUADORPARTICIPACION" ("PARTICIPACIONID");

CREATE TABLE "EVALUADORCERTIFICADO" (
  "CERTIFICADOID" NUMBER(10,0) NOT NULL,
  "PARTICIPACIONID" NUMBER(10,0) NOT NULL,
  "ANIO" NUMBER(4,0) NOT NULL,
  "CONSECUTIVO" NUMBER(6,0) NOT NULL,
  "CODIGOVERIFICACION" NVARCHAR2(40) NOT NULL,
  "FECHAEMISION" DATE DEFAULT SYSDATE NOT NULL,
  "EMITIDOPOR" NVARCHAR2(200) NOT NULL,
  "FIRMACERTIFICADOSID" NUMBER(10,0),
  "HORASCERTIFICADAS" NUMBER(5,0),
  "DATOSSNAPSHOT" NCLOB NOT NULL,
  "ARCHIVOPDF" BLOB,
  "ARCHIVOMIME" NVARCHAR2(120) DEFAULT N'application/pdf',
  "ARCHIVONOMBRE" NVARCHAR2(255),
  "ANULADO" NUMBER(1,0) DEFAULT 0 NOT NULL,
  "MOTIVOANULACION" NVARCHAR2(500),
  "FECHAANULACION" DATE,
  "ANULADOPOR" NVARCHAR2(200),
  CONSTRAINT "PK_EVALUADORCERTIFICADO" PRIMARY KEY ("CERTIFICADOID"),
  CONSTRAINT "UQ_CERT_CODIGO" UNIQUE ("CODIGOVERIFICACION"),
  CONSTRAINT "UQ_CERT_CONSECUTIVO" UNIQUE ("ANIO", "CONSECUTIVO")
);

ALTER TABLE "EVALUADORCERTIFICADO" ADD CONSTRAINT "FK_CERT_PART" FOREIGN KEY ("PARTICIPACIONID") REFERENCES "EVALUADORPARTICIPACION" ("PARTICIPACIONID");

CREATE TABLE "EVALUADORDOCUMENTO" (
  "DOCUMENTOID" NUMBER(10,0) NOT NULL,
  "EVALUADORID" NUMBER(10,0) NOT NULL,
  "TIPODOCUMENTOEVALID" NUMBER(10,0) NOT NULL,
  "DOCUMENTODESCRIPCION" NVARCHAR2(300),
  "ANIOREFERENCIA" NUMBER(4,0),
  "ARCHIVOPDF" BLOB NOT NULL,
  "ARCHIVOMIME" NVARCHAR2(120) NOT NULL,
  "ARCHIVONOMBRE" NVARCHAR2(255),
  "FECHACARGUE" DATE DEFAULT SYSDATE NOT NULL,
  "PARTICIPACIONID" NUMBER(10,0),
  "USUARIOCREACION" NVARCHAR2(200),
  CONSTRAINT "PK_EVALUADORDOCUMENTO" PRIMARY KEY ("DOCUMENTOID")
);

ALTER TABLE "EVALUADORDOCUMENTO" ADD CONSTRAINT "FK_EVALDOC_EVAL" FOREIGN KEY ("EVALUADORID") REFERENCES "EVALUADOR" ("EVALUADORID");

ALTER TABLE "EVALUADORDOCUMENTO" ADD CONSTRAINT "FK_EVALDOC_PART" FOREIGN KEY ("PARTICIPACIONID") REFERENCES "EVALUADORPARTICIPACION" ("PARTICIPACIONID");

ALTER TABLE "EVALUADORDOCUMENTO" ADD CONSTRAINT "FK_EVALDOC_TIPO" FOREIGN KEY ("TIPODOCUMENTOEVALID") REFERENCES "TIPODOCUMENTOEVAL" ("TIPODOCUMENTOEVALID");

CREATE TABLE "EVALUADORPARTALCANCE" (
  "PARTALCANCEID" NUMBER(10,0) NOT NULL,
  "PARTICIPACIONID" NUMBER(10,0) NOT NULL,
  "AREAID" NUMBER(10,0) NOT NULL,
  "ROLEVALUADORID" NUMBER(10,0) NOT NULL,
  CONSTRAINT "PK_EVALUADORPARTALCANCE" PRIMARY KEY ("PARTALCANCEID"),
  CONSTRAINT "UQ_PARTALCANCE" UNIQUE ("PARTICIPACIONID", "AREAID", "ROLEVALUADORID")
);

ALTER TABLE "EVALUADORPARTALCANCE" ADD CONSTRAINT "FK_PARTALC_AREA" FOREIGN KEY ("AREAID") REFERENCES "AREAEVALUACION" ("AREAID");

ALTER TABLE "EVALUADORPARTALCANCE" ADD CONSTRAINT "FK_PARTALC_PART" FOREIGN KEY ("PARTICIPACIONID") REFERENCES "EVALUADORPARTICIPACION" ("PARTICIPACIONID");

ALTER TABLE "EVALUADORPARTALCANCE" ADD CONSTRAINT "FK_PARTALC_ROL" FOREIGN KEY ("ROLEVALUADORID") REFERENCES "ROLEVALUADOR" ("ROLEVALUADORID");

CREATE TABLE "EVALUADORPARTGRUPO" (
  "PARTGRUPOID" NUMBER(10,0) NOT NULL,
  "PARTICIPACIONID" NUMBER(10,0) NOT NULL,
  "GRUPONUMERO" NUMBER(3,0) NOT NULL,
  "ESPRINCIPAL" NUMBER(1,0) DEFAULT 0 NOT NULL,
  CONSTRAINT "PK_EVALUADORPARTGRUPO" PRIMARY KEY ("PARTGRUPOID"),
  CONSTRAINT "UQ_PARTGRUPO" UNIQUE ("PARTICIPACIONID", "GRUPONUMERO")
);

ALTER TABLE "EVALUADORPARTGRUPO" ADD CONSTRAINT "FK_PARTGRUPO_PART" FOREIGN KEY ("PARTICIPACIONID") REFERENCES "EVALUADORPARTICIPACION" ("PARTICIPACIONID");

CREATE TABLE "RETROASIGNACION" (
  "RETROASIGNACIONID" NUMBER(10,0) NOT NULL,
  "RETROFORMULARIOID" NUMBER(10,0) NOT NULL,
  "PARTEVALUADORID" NUMBER(10,0) NOT NULL,
  "PARTEVALUADOID" NUMBER(10,0) NOT NULL,
  "ESTADO" NVARCHAR2(20) DEFAULT N'PENDIENTE' NOT NULL,
  "ORIGEN" NVARCHAR2(20) DEFAULT N'AUTOMATICA' NOT NULL,
  "MOTIVOREGLA" NVARCHAR2(200),
  "RETRORESPUESTAID" NUMBER(10,0),
  "USUARIOCREACION" NVARCHAR2(200),
  "FECHACREACION" DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT "PK_RETROASIGNACION" PRIMARY KEY ("RETROASIGNACIONID"),
  CONSTRAINT "UQ_RETROASIG_PAR" UNIQUE ("RETROFORMULARIOID", "PARTEVALUADORID", "PARTEVALUADOID"),
  CONSTRAINT "CK_RETROASIG_ESTADO" CHECK (ESTADO IN (N'PENDIENTE', N'ENVIADA', N'ANULADA')),
  CONSTRAINT "CK_RETROASIG_NOAUTO" CHECK (PARTEVALUADORID <> PARTEVALUADOID),
  CONSTRAINT "CK_RETROASIG_ORIGEN" CHECK (ORIGEN IN (N'AUTOMATICA', N'MANUAL'))
);

ALTER TABLE "RETROASIGNACION" ADD CONSTRAINT "FK_RETROASIG_EVALUADO" FOREIGN KEY ("PARTEVALUADOID") REFERENCES "EVALUADORPARTICIPACION" ("PARTICIPACIONID");

ALTER TABLE "RETROASIGNACION" ADD CONSTRAINT "FK_RETROASIG_EVALUADOR" FOREIGN KEY ("PARTEVALUADORID") REFERENCES "EVALUADORPARTICIPACION" ("PARTICIPACIONID");

ALTER TABLE "RETROASIGNACION" ADD CONSTRAINT "FK_RETROASIG_FORM" FOREIGN KEY ("RETROFORMULARIOID") REFERENCES "RETROFORMULARIO" ("RETROFORMULARIOID");

CREATE TABLE "RETRORESPUESTA" (
  "RETRORESPUESTAID" NUMBER(10,0) NOT NULL,
  "RETROSESIONID" NUMBER(10,0) NOT NULL,
  "RETROASIGNACIONID" NUMBER(10,0) NOT NULL,
  "RETROFORMULARIOID" NUMBER(10,0) NOT NULL,
  "PARTEVALUADORID" NUMBER(10,0) NOT NULL,
  "PARTEVALUADOID" NUMBER(10,0) NOT NULL,
  "PUNTAJEESCALA" NUMBER(6,2) DEFAULT 0 NOT NULL,
  "PUNTAJEMAXIMO" NUMBER(6,2) DEFAULT 0 NOT NULL,
  "PROMEDIO" NUMBER(5,2),
  "FECHAENVIO" DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT "PK_RETRORESPUESTA" PRIMARY KEY ("RETRORESPUESTAID"),
  CONSTRAINT "UQ_RETRORESP_ASIG" UNIQUE ("RETROASIGNACIONID")
);

ALTER TABLE "RETRORESPUESTA" ADD CONSTRAINT "FK_RETRORESP_ASIG" FOREIGN KEY ("RETROASIGNACIONID") REFERENCES "RETROASIGNACION" ("RETROASIGNACIONID");

ALTER TABLE "RETRORESPUESTA" ADD CONSTRAINT "FK_RETRORESP_EVALUADO" FOREIGN KEY ("PARTEVALUADOID") REFERENCES "EVALUADORPARTICIPACION" ("PARTICIPACIONID");

ALTER TABLE "RETRORESPUESTA" ADD CONSTRAINT "FK_RETRORESP_EVALUADOR" FOREIGN KEY ("PARTEVALUADORID") REFERENCES "EVALUADORPARTICIPACION" ("PARTICIPACIONID");

ALTER TABLE "RETRORESPUESTA" ADD CONSTRAINT "FK_RETRORESP_FORM" FOREIGN KEY ("RETROFORMULARIOID") REFERENCES "RETROFORMULARIO" ("RETROFORMULARIOID");

ALTER TABLE "RETRORESPUESTA" ADD CONSTRAINT "FK_RETRORESP_SES" FOREIGN KEY ("RETROSESIONID") REFERENCES "RETROSESION" ("RETROSESIONID");

CREATE TABLE "RETRORESPUESTAITEM" (
  "RETROITEMID" NUMBER(10,0) NOT NULL,
  "RETRORESPUESTAID" NUMBER(10,0) NOT NULL,
  "RETROPREGUNTAID" NUMBER(10,0) NOT NULL,
  "PREGUNTANUMERO" NUMBER(3,0) NOT NULL,
  "CALIFICACION" NUMBER(3,0),
  "COMENTARIO" NCLOB,
  CONSTRAINT "PK_RETRORESPUESTAITEM" PRIMARY KEY ("RETROITEMID"),
  CONSTRAINT "UQ_RETROITEM_PREG" UNIQUE ("RETRORESPUESTAID", "RETROPREGUNTAID")
);

ALTER TABLE "RETRORESPUESTAITEM" ADD CONSTRAINT "FK_RETROITEM_PREG" FOREIGN KEY ("RETROPREGUNTAID") REFERENCES "RETROPREGUNTA" ("RETROPREGUNTAID");

ALTER TABLE "RETRORESPUESTAITEM" ADD CONSTRAINT "FK_RETROITEM_RESP" FOREIGN KEY ("RETRORESPUESTAID") REFERENCES "RETRORESPUESTA" ("RETRORESPUESTAID");


-- ========== 2. SECUENCIAS ==========
-- Arrancan 1000 por encima del ultimo usado en el XE: deja hueco por si el
-- origen llegara a emitir alguna mas antes de apagarse.

CREATE SEQUENCE "PROYECTOVERSION_SEQ" START WITH 1001 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "USUARIOPERFIL_SEQ" START WITH 79981 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "ROLEVALUADOR_SEQ" START WITH 1010 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "PROCESOEVAL_SEQ" START WITH 1003 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "TIPOESTUDIO_SEQ" START WITH 1007 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "EVALUADOR_SEQ" START WITH 1159 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "EVALUADORPARTICIPACION_SEQ" START WITH 1393 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "EVALUADOREXPERIENCIA_SEQ" START WITH 1587 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "EVALUADORTIC_SEQ" START WITH 1235 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "EVALUADORPRUEBA_SEQ" START WITH 1297 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "EVALUADORESTUDIO_SEQ" START WITH 1803 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "CONVPROYGUARDADO_SEQ" START WITH 1073 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "EVALUADORAPROBACION_SEQ" START WITH 1325 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "EVALUADORCAPACITACION_SEQ" START WITH 1022 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "EVALUADORPARTPROYECTO_SEQ" START WITH 1850 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "RETROFORMULARIO_SEQ" START WITH 1072 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "RETROPREGUNTA_SEQ" START WITH 1773 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "RETROASIGNACION_SEQ" START WITH 1127 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "RETROSESION_SEQ" START WITH 1089 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "RETRORESPUESTA_SEQ" START WITH 1107 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "RETRORESPUESTAITEM_SEQ" START WITH 2189 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "RETROSUGERENCIA_SEQ" START WITH 1011 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "EVALUADORPARTGRUPO_SEQ" START WITH 1041 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "EVALUADORPARTALCANCE_SEQ" START WITH 1001 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "EVALUADORLOG_SEQ" START WITH 3897 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE "EVALUADORCERTIFICADO_SEQ" START WITH 1016 INCREMENT BY 1 NOCACHE;


-- ========== 3. INDICES ==========
-- Los 5 UNICOS de aqui NO son rendimiento: son reglas de negocio que Oracle
-- solo conoce por el indice. Sin ellos el Exadata acepta duplicados que el SEP
-- da por imposibles, y el backend llega a nombrar uno por su nombre para
-- convertir el ORA-00001 en un mensaje entendible.

CREATE INDEX "IX_CF_CIUDAD" ON "CENTROFORMACION" ("CIUDADID");

CREATE INDEX "IX_CF_REGIONAL" ON "CENTROFORMACION" ("REGIONALID");

CREATE INDEX "IX_CONVDOC_CONV" ON "CONVOCATORIADOCUMENTO" ("CONVOCATORIAID");

CREATE INDEX "IX_CONVDOC_TIPO" ON "CONVOCATORIADOCUMENTO" ("TIPODOCUMENTOCONVID");

CREATE INDEX "IX_CPG_CONV" ON "CONVPROYGUARDADO" ("CONVOCATORIAID");

CREATE INDEX "IX_EVALUADOR_ACTIVO" ON "EVALUADOR" ("EVALUADORACTIVO", "EVALUADORID");

CREATE INDEX "IX_APROB_FECHA" ON "EVALUADORAPROBACION" ("FECHAAPROBACION" DESC);

CREATE INDEX "IX_CAPAC_PART" ON "EVALUADORCAPACITACION" ("PARTICIPACIONID");

CREATE INDEX "IX_CERT_ANIO" ON "EVALUADORCERTIFICADO" ("ANIO", "ANULADO");

CREATE INDEX "IX_CERT_PART" ON "EVALUADORCERTIFICADO" ("PARTICIPACIONID");

CREATE UNIQUE INDEX "UQ_CERT_PART_VIGENTE" ON "EVALUADORCERTIFICADO" (CASE "ANULADO" WHEN 0 THEN "PARTICIPACIONID" END );

CREATE INDEX "IX_CONV_ANIO" ON "EVALUADORCONVOCATORIA" ("ANIO");

CREATE INDEX "IX_CONV_SEP" ON "EVALUADORCONVOCATORIA" ("CONVOCATORIASEPID");

CREATE UNIQUE INDEX "UQ_EVALCONV_SEP_PERIODO" ON "EVALUADORCONVOCATORIA" (CASE  WHEN "CONVOCATORIASEPID" IS NOT NULL THEN "CONVOCATORIASEPID" END , CASE  WHEN "CONVOCATORIASEPID" IS NOT NULL THEN NVL(TRIM("PERIODO"),U'-') END );

CREATE INDEX "IX_EVALDOC_EVAL" ON "EVALUADORDOCUMENTO" ("EVALUADORID");

CREATE INDEX "IX_EVALDOC_PART" ON "EVALUADORDOCUMENTO" ("PARTICIPACIONID");

CREATE INDEX "IX_EVALDOC_TIPO" ON "EVALUADORDOCUMENTO" ("TIPODOCUMENTOEVALID");

CREATE INDEX "IX_ESTUDIO_EVAL" ON "EVALUADORESTUDIO" ("EVALUADORID");

CREATE INDEX "IX_EXP_EVAL" ON "EVALUADOREXPERIENCIA" ("EVALUADORID");

CREATE INDEX "IX_EVALLOG_EVAL" ON "EVALUADORLOG" ("EVALUADORID", "FECHA" DESC);

CREATE INDEX "IX_EVALLOG_FECHA" ON "EVALUADORLOG" ("FECHA" DESC);

CREATE INDEX "IX_EVALLOG_PART" ON "EVALUADORLOG" ("PARTICIPACIONID");

CREATE INDEX "IX_EVALLOG_TABLA" ON "EVALUADORLOG" ("TABLA", "OPERACION");

CREATE INDEX "IX_PARTGRUPO_GRUPO" ON "EVALUADORPARTGRUPO" ("GRUPONUMERO");

CREATE INDEX "IX_PART_CONVOCATORIA" ON "EVALUADORPARTICIPACION" ("CONVOCATORIAID");

CREATE INDEX "IX_PART_ESTADO" ON "EVALUADORPARTICIPACION" ("ESTADOPARTID");

CREATE INDEX "IX_PART_EVAL_ANIO" ON "EVALUADORPARTICIPACION" ("EVALUADORID", "ANIO" DESC);

CREATE INDEX "IX_PARTPROY_GUARDADO" ON "EVALUADORPARTPROYECTO" ("GUARDADOID");

CREATE INDEX "IX_PARTPROY_PART" ON "EVALUADORPARTPROYECTO" ("PARTICIPACIONID");

CREATE INDEX "IX_PARTPROY_PROYECTO" ON "EVALUADORPARTPROYECTO" ("PROYECTOID");

CREATE INDEX "IX_PRUEBA_EVAL_ANIO" ON "EVALUADORPRUEBA" ("EVALUADORID", "ANIO" DESC);

CREATE INDEX "IX_PRUEBA_PART" ON "EVALUADORPRUEBA" ("PARTICIPACIONID");

CREATE INDEX "IX_TIC_EVAL" ON "EVALUADORTIC" ("EVALUADORID");

CREATE INDEX "IX_PROYECTOAPROBADO_FECHA" ON "PROYECTOAPROBADO" ("FECHAAPROBACION" DESC);

CREATE INDEX "IX_PROYECTOVERSION_FECHA" ON "PROYECTOVERSION" ("VERSIONFECHA" DESC);

CREATE INDEX "IX_PROYECTOVERSION_PROY" ON "PROYECTOVERSION" ("PROYECTOID");

CREATE UNIQUE INDEX "UX_PROYECTOVERSION_FINAL" ON "PROYECTOVERSION" (CASE "VERSIONESFINAL" WHEN 1 THEN "PROYECTOID" ELSE NULL END );

CREATE INDEX "IX_RETROASIG_EVALUADO" ON "RETROASIGNACION" ("PARTEVALUADOID", "ESTADO");

CREATE INDEX "IX_RETROASIG_EVALUADOR" ON "RETROASIGNACION" ("PARTEVALUADORID", "ESTADO");

CREATE UNIQUE INDEX "UQ_RETROFORM_ACTIVO" ON "RETROFORMULARIO" (CASE "ACTIVO" WHEN 1 THEN "CONVOCATORIAID" END );

CREATE INDEX "IX_RETRORESP_EVALUADO" ON "RETRORESPUESTA" ("PARTEVALUADOID");

CREATE INDEX "IX_RETRORESP_SES" ON "RETRORESPUESTA" ("RETROSESIONID");

CREATE INDEX "IX_RETROITEM_RESP" ON "RETRORESPUESTAITEM" ("RETRORESPUESTAID");

CREATE INDEX "IX_RETROSES_PART" ON "RETROSESION" ("PARTICIPACIONID");

CREATE UNIQUE INDEX "UQ_ROLEVALUADOR_CODIGO" ON "ROLEVALUADOR" ("ROLEVALUADORCODIGO");

CREATE INDEX "IX_USUARIOPERFIL_USU" ON "USUARIOPERFIL" ("USUARIOID", "ESTADO");


-- ========== 4. COMENTARIOS ==========

COMMENT ON TABLE "EVALUADORAPROBACION" IS 'Autorización del jefe directo para participar en un ciclo de evaluación. 1:1 con la participación.';

COMMENT ON TABLE "EVALUADORCAPACITACION" IS 'Curso de formación exigido en un ciclo de evaluación, con calificación y certificado.';

COMMENT ON TABLE "EVALUADORCERTIFICADO" IS 'Certificado de participación emitido por el sistema. No se borra: se anula.';

COMMENT ON TABLE "EVALUADORLOG" IS 'Auditoría de operaciones sensibles del banco de evaluadores. Solo escritura desde el backend; lectura para coordinación y admin.';

COMMENT ON TABLE "EVALUADORPARTALCANCE" IS 'Qué roles de qué áreas le corresponde retroalimentar a un evaluador transversal. Una fila por (área, rol).';

COMMENT ON TABLE "EVALUADORPARTGRUPO" IS 'Grupos (mesas) en que participó el evaluador ese año. Alimenta el generador de la matriz de retroalimentación.';

COMMENT ON TABLE "EVALUADORPARTPROYECTO" IS 'Proyectos evaluados por un evaluador en un ciclo. Reemplaza el CLOB PROYECTOSEVALUADOS.';

COMMENT ON TABLE "RETROASIGNACION" IS 'Par evaluador→evaluado generado por la matriz de reglas. Se ancla a PARTICIPACION para que el resultado caiga en el año correcto.';

COMMENT ON TABLE "RETROFORMULARIO" IS 'Instrumento de retroalimentación de un ciclo. Versionado: cada convocatoria puede tener su propio set de preguntas.';

COMMENT ON TABLE "RETROSESION" IS 'Un intento de diligenciamiento. Agrupa todas las respuestas enviadas de una vez + la pregunta general.';

COMMENT ON TABLE "RETROSUGERENCIA" IS 'Respuesta a la pregunta de tipo TEXTO_GENERAL. Es del proceso, no de un par evaluador-evaluado.';

COMMENT ON COLUMN "AREAEVALUACION"."GRUPOSDEFECTO" IS 'Grupos que por defecto pertenecen al área, separados por coma';

COMMENT ON COLUMN "ESTADOPARTICIPACION"."COLOR" IS 'Token de color para la UI (neutral, blue, indigo, cyan, amber, orange, green, red). No hex.';

COMMENT ON COLUMN "ESTADOPARTICIPACION"."ESFINAL" IS '1 = estado terminal, la participación ya no avanza.';

COMMENT ON COLUMN "ESTADOPARTICIPACION"."ESNEGATIVO" IS '1 = cierre sin haber evaluado (declinó, no aprobó, revocado). Se excluye de las métricas de desempeño.';

COMMENT ON COLUMN "EVALUADOR"."EVALUADORFOTOMINI" IS 'Miniatura JPEG (lado mayor 400 px) de EVALUADORFOTO, para mostrar en pantalla. La original se conserva y es la que se descarga y la que va en la ficha PDF. Se genera sola: al cargar la foto, o la primera vez que se pide si la fila es anterior a la v50.';

COMMENT ON COLUMN "EVALUADOR"."EVALUADORFOTONOMBRE" IS 'Nombre original del archivo de foto cargado (para Content-Disposition al descargar).';

COMMENT ON COLUMN "EVALUADORAPROBACION"."APROBADOREMAIL" IS 'Correo del jefe que autoriza. Desnormalizado a propósito: puede ser alguien fuera de PERSONA.';

COMMENT ON COLUMN "EVALUADORAPROBACION"."CORREOEVIDENCIA" IS 'Correo de autorización (.msg de Outlook o PDF). Tope 20 MB validado en aplicación.';

COMMENT ON COLUMN "EVALUADORCAPACITACION"."ORIGEN" IS 'EXTERNO = resultado cargado desde plataforma externa. SISTEMA = curso dictado y calificado dentro del SEP (fase futura).';

COMMENT ON COLUMN "EVALUADORCAPACITACION"."CALIFICACIONMINIMA" IS 'Nota de corte de ESE curso. Se copia de la convocatoria al crear, para que un cambio posterior no reescriba el histórico.';

COMMENT ON COLUMN "EVALUADORCAPACITACION"."APROBADO" IS '1 = aprobó. Alimenta el hito 4 del checklist del ciclo.';

COMMENT ON COLUMN "EVALUADORCERTIFICADO"."CONSECUTIVO" IS 'Numeración oficial dentro del año. Se calcula con SELECT ... FOR UPDATE sobre el año para evitar huecos y colisiones.';

COMMENT ON COLUMN "EVALUADORCERTIFICADO"."CODIGOVERIFICACION" IS 'Código público para validar el certificado en /verificar/:codigo. Aleatorio, no derivable del consecutivo.';

COMMENT ON COLUMN "EVALUADORCERTIFICADO"."DATOSSNAPSHOT" IS 'JSON con los datos usados al emitir (nombre, cédula, rol, proceso, mesa, fechas, horas). Congela el contenido para reimpresiones.';

COMMENT ON COLUMN "EVALUADORCERTIFICADO"."ARCHIVOPDF" IS 'PDF generado. Nullable: se puede regenerar desde DATOSSNAPSHOT si se pierde el BLOB.';

COMMENT ON COLUMN "EVALUADORCONVOCATORIA"."CERTIFICADOHABILITADO" IS '1 = la coordinación ya autorizó emitir certificados de este ciclo. Evita emisiones antes de cerrar el proceso.';

COMMENT ON COLUMN "EVALUADORCONVOCATORIA"."CONVOCATORIASEPID" IS 'FK lógica a la CONVOCATORIA real del SEP (la de proyectos). Nullable: un ciclo del banco puede no mapear 1:1.';

COMMENT ON COLUMN "EVALUADORCONVOCATORIA"."PUNTAJEMINIMOPRUEBA" IS 'Nota de corte de la prueba de conocimiento de ESE año. Cambia año a año.';

COMMENT ON COLUMN "EVALUADORCONVOCATORIA"."CERTIFICADOTEXTO" IS 'Cuerpo del certificado con placeholders: {{nombre}} {{identificacion}} {{rol}} {{proceso}} {{anio}} {{horas}} {{fechaInicio}} {{fechaFin}}.';

COMMENT ON COLUMN "EVALUADORDOCUMENTO"."PARTICIPACIONID" IS 'NULL = documento personal permanente (cédula, HV). No nulo = documento propio de ese ciclo.';

COMMENT ON COLUMN "EVALUADORLOG"."EVALUADORID" IS 'Evaluador afectado. Denormalizado para poder filtrar el log de una ficha sin recorrer todas las tablas.';

COMMENT ON COLUMN "EVALUADORLOG"."PARTICIPACIONID" IS 'Ciclo afectado, cuando aplica. Permite mostrar la auditoría dentro del año correspondiente.';

COMMENT ON COLUMN "EVALUADORLOG"."OPERACION" IS 'INSERT/UPDATE/DELETE genéricos, más ESTADO (cambio de estado del ciclo), GENERAR/ANULAR (matriz de retroalimentación) y EMITIR (certificado).';

COMMENT ON COLUMN "EVALUADORLOG"."VALORANTES" IS 'Snapshot JSON del registro antes del cambio. NULL en INSERT.';

COMMENT ON COLUMN "EVALUADORPARTICIPACION"."CONVOCATORIAID" IS 'Ciclo del banco al que pertenece. Habilita heredar los documentos generales del año sin duplicarlos por evaluador.';

COMMENT ON COLUMN "EVALUADORPARTICIPACION"."ESTADOPARTID" IS 'Estado declarado del ciclo. El backend calcula además un estadoSugerido desde el checklist y avisa si divergen.';

COMMENT ON COLUMN "EVALUADORPARTICIPACION"."AREAID" IS 'Área (Técnica/Jurídica/Financiera) en la que actuó ESE año. Es contexto anual, no atributo de la persona.';

COMMENT ON COLUMN "EVALUADORPARTICIPACION"."ESTRANSVERSAL" IS '1 = evaluó con alcance explícito multi-área (ver EVALUADORPARTALCANCE), no por su grupo.';

COMMENT ON COLUMN "EVALUADORPARTICIPACION"."MOTIVONOPARTICIPA" IS 'Por qué declinó / no aprobó / se le revocó. Obligatorio en aplicación cuando el estado es ESNEGATIVO = 1.';

COMMENT ON COLUMN "EVALUADORPARTPROYECTO"."PUNTAJEOTORGADO" IS 'Puntaje que ESTE evaluador le dio al proyecto (no el consolidado de la mesa).';

COMMENT ON COLUMN "EVALUADORPARTPROYECTO"."PROYECTOID" IS 'FK lógica a PROYECTO. Sin constraint: el histórico puede referirse a proyectos purgados.';

COMMENT ON COLUMN "EVALUADORPARTPROYECTO"."GUARDADOID" IS 'FK lógica a CONVPROYGUARDADO (v28) para proyectos formulados que nunca se importaron.';

COMMENT ON COLUMN "EVALUADORPRUEBA"."PARTICIPACIONID" IS 'Ciclo al que corresponde la prueba. NULL = histórico suelto (2021-2023) que todavía no se ató a una participación.';

COMMENT ON COLUMN "EVALUADORPRUEBA"."PUNTAJEMINIMO" IS 'Nota de corte vigente al presentar. Congelada para que un cambio posterior no reescriba el histórico.';

COMMENT ON COLUMN "RETROASIGNACION"."ESTADO" IS 'PENDIENTE / ENVIADA / ANULADA. ANULADA = el coordinador la retiró sin borrar la traza.';

COMMENT ON COLUMN "RETROASIGNACION"."ORIGEN" IS 'AUTOMATICA = la generó el motor de reglas. MANUAL = la agregó el coordinador a mano.';

COMMENT ON COLUMN "RETROASIGNACION"."MOTIVOREGLA" IS 'Regla que produjo el par (ej. "lider-tecnica→analistas-g1-6"). Sirve para auditar y depurar la matriz.';

COMMENT ON COLUMN "RETROFORMULARIO"."DURACIONMINUTOS" IS 'Minutos de referencia de la sesión. Al superarlos se marca SEEXCEDIO (no bloquea el envío).';

COMMENT ON COLUMN "RETROFORMULARIO"."RESULTADOANONIMO" IS '1 = al mostrar resultados nunca se revela quién calificó (solo el origen). La fila SÍ guarda el calificador para auditoría.';

COMMENT ON COLUMN "RETROFORMULARIO"."ABIERTO" IS '1 = los evaluadores pueden diligenciar. 0 = cerrado (solo lectura de resultados).';

COMMENT ON COLUMN "RETROFORMULARIO"."REGLASMATRIZ" IS 'JSON con la configuración del generador de pares: {"gruposPorArea":{"TECNICA":[1,2,3,4,5,6],...},"peerEvaluation":true}. Permite cambiar la topología año a año sin desplegar código.';

COMMENT ON COLUMN "RETROFORMULARIO"."ESCALAETIQUETAS" IS 'JSON {"1":"Deficiente",...,"5":"Excelente"}. Se congela con el instrumento del ciclo.';

COMMENT ON COLUMN "RETROPREGUNTA"."TIPO" IS 'ESCALA = radio ESCALAMIN..ESCALAMAX por persona evaluada. TEXTO_POR_PERSONA = textarea por cada evaluado. TEXTO_GENERAL = textarea única al cierre de la sesión (no por persona).';

COMMENT ON COLUMN "RETRORESPUESTA"."PUNTAJEMAXIMO" IS 'Máximo alcanzable con las preguntas de escala vigentes al momento del envío. Congelado para que un cambio del instrumento no altere el histórico.';

COMMENT ON COLUMN "RETRORESPUESTA"."PROMEDIO" IS 'PUNTAJEESCALA / número de preguntas de escala respondidas. Es el número que se muestra en la ficha del evaluado.';

COMMENT ON COLUMN "RETROSESION"."SEEXCEDIO" IS '1 = superó DURACIONMINUTOS. Es informativo para el reporte de tiempos, no bloquea el envío.';

COMMENT ON COLUMN "ROLEVALUADOR"."AREAID" IS 'Área a la que pertenece el rol por naturaleza (NULL = aplica a cualquier área).';

COMMENT ON COLUMN "TIPODOCUMENTOEVAL"."CODIGO" IS 'Código estable (ej. CEDULA, AUTORIZACION, CONFIDENCIALIDAD) usado por el backend.';

COMMENT ON COLUMN "TIPODOCUMENTOEVAL"."ADMITEMULTIPLE" IS '1 = varios documentos por evaluador; 0 = uno único (se reemplaza al subir).';

COMMENT ON COLUMN "TIPODOCUMENTOEVAL"."ORDEN" IS 'Orden de visualización en el listado del evaluador (menor primero).';

-- ============================================================
-- 5. LLAVES HACIA TABLAS QUE YA EXISTEN EN EL EXADATA
--
-- LOS BLOQUES 1 A 4 YA SE CORRIERON el 2026-09-10 y estan aplicados y
-- verificados. Este bloque 5 NO, y es el unico que falta del paso 1.
--
-- La primera version de estas 9 sentencias salio con la lista de columnas del
-- padre VACIA -- REFERENCES "CIUDAD" () -- y por eso murio con ORA-00936. Fue un
-- error del generador: buscaba las columnas del padre en un mapa que solo tenia
-- las de las 39 tablas nuevas. Ahora se leen del propio Exadata, que es donde la
-- llave se crea: si alla la clave primaria fuera distinta, fallaria igual.
--
-- SIGUE SIN CORRERSE TODAVIA. Estas llaves exigen que antes existan las 98 filas
-- padre que faltan (21 PERSONA, 77 USUARIO) y que esten resueltas las 8
-- colisiones de identificador. Van en el paso 3.
--
-- Reversa de este bloque: ALTER TABLE <hija> DROP CONSTRAINT <nombre>. No altera
-- ni una fila de las tablas del SENA: solo quita la referencia.
-- ============================================================

-- CENTROFORMACION -> CIUDAD (PK del Exadata: SYS_C0011095)
ALTER TABLE "CENTROFORMACION" ADD CONSTRAINT "FK_CF_CIUDAD" FOREIGN KEY ("CIUDADID") REFERENCES "CIUDAD" ("CIUDADID");

-- EVALUADORCONVOCATORIA -> CONVOCATORIA (PK del Exadata: SYS_C0011124)
ALTER TABLE "EVALUADORCONVOCATORIA" ADD CONSTRAINT "FK_EVALCONV_CONVSEP" FOREIGN KEY ("CONVOCATORIASEPID") REFERENCES "CONVOCATORIA" ("CONVOCATORIAID");

-- EVALUADOR -> CIUDAD (PK del Exadata: SYS_C0011095)
ALTER TABLE "EVALUADOR" ADD CONSTRAINT "FK_EVALUADOR_MUNICIPIO" FOREIGN KEY ("EVALUADORMUNICIPIOID") REFERENCES "CIUDAD" ("CIUDADID");

-- EVALUADOR -> PERSONA (PK del Exadata: SYS_C0025042)
ALTER TABLE "EVALUADOR" ADD CONSTRAINT "FK_EVALUADOR_PERSONA" FOREIGN KEY ("PERSONAID") REFERENCES "PERSONA" ("PERSONAID");

-- EVALUADORPARTICIPACION -> PERSONA (PK del Exadata: SYS_C0025042)
ALTER TABLE "EVALUADORPARTICIPACION" ADD CONSTRAINT "FK_PART_DINAMIZADOR" FOREIGN KEY ("DINAMIZADORPERSONAID") REFERENCES "PERSONA" ("PERSONAID");

-- PROYECTOAPROBADO -> PROYECTO (PK del Exadata: SYS_C0011020)
ALTER TABLE "PROYECTOAPROBADO" ADD CONSTRAINT "FK_PROYECTOAPROBADO_PROY" FOREIGN KEY ("PROYECTOID") REFERENCES "PROYECTO" ("PROYECTOID");

-- PROYECTOVERSION -> PROYECTO (PK del Exadata: SYS_C0011020)
ALTER TABLE "PROYECTOVERSION" ADD CONSTRAINT "FK_PROYECTOVERSION_PROYECTO" FOREIGN KEY ("PROYECTOID") REFERENCES "PROYECTO" ("PROYECTOID");

-- USUARIOPERFIL -> PERFIL (PK del Exadata: SYS_C0011116)
ALTER TABLE "USUARIOPERFIL" ADD CONSTRAINT "FK_USUARIOPERFIL_PERFIL" FOREIGN KEY ("PERFILID") REFERENCES "PERFIL" ("PERFILID");

-- USUARIOPERFIL -> USUARIO (PK del Exadata: SYS_C0011099)
ALTER TABLE "USUARIOPERFIL" ADD CONSTRAINT "FK_USUARIOPERFIL_USUARIO" FOREIGN KEY ("USUARIOID") REFERENCES "USUARIO" ("USUARIOID");
