-- v69 COMPROBACION — se corre DESPUES del v69, como SENADM.
--
-- Dice si llego todo o si quedo a medias. Cada consulta trae lo esperado al
-- lado, para poder comparar de un vistazo sin acordarse de los numeros.
--
-- No escribe nada: son cinco SELECT.

SET DEFINE OFF;

-- 1. Las tablas: deben ser 39 de 39.
SELECT 39 AS ESPERADAS, COUNT(*) AS CREADAS FROM USER_TABLES
 WHERE TABLE_NAME IN ('AREAEVALUACION', 'ARTICULACIONTERRITORIAL', 'CONVPROYGUARDADO', 'ESTADOPARTICIPACION', 'EVALUADOR', 'EVALUADOREXPERIENCIA', 'EVALUADORLOG', 'EVALUADORTIC', 'MODALIDADPART', 'PROCESOEVAL', 'PROYECTOVERSION', 'REGIONAL', 'RETONACIONAL', 'ROLEVALUADOR', 'TIPODOCUMENTOCONV', 'TIPODOCUMENTOEVAL', 'TIPOESTUDIO', 'USUARIOPERFIL', 'CENTROFORMACION', 'EVALUADORCONVOCATORIA', 'EVALUADORESTUDIO', 'EVALUADORPARTICIPACION', 'EVALUADORPARTPROYECTO', 'EVALUADORPRUEBA', 'PROYECTOAPROBADO', 'RETROFORMULARIO', 'RETROPREGUNTA', 'RETROSESION', 'RETROSUGERENCIA', 'CONVOCATORIADOCUMENTO', 'EVALUADORAPROBACION', 'EVALUADORCAPACITACION', 'EVALUADORCERTIFICADO', 'EVALUADORDOCUMENTO', 'EVALUADORPARTALCANCE', 'EVALUADORPARTGRUPO', 'RETROASIGNACION', 'RETRORESPUESTA', 'RETRORESPUESTAITEM');

-- 2. Si falta alguna, esta consulta la nombra. Vacia = todas llegaron.
WITH esperadas AS (
  SELECT 'AREAEVALUACION' AS t FROM dual
  UNION ALL SELECT 'ARTICULACIONTERRITORIAL' AS t FROM dual
  UNION ALL SELECT 'CONVPROYGUARDADO' AS t FROM dual
  UNION ALL SELECT 'ESTADOPARTICIPACION' AS t FROM dual
  UNION ALL SELECT 'EVALUADOR' AS t FROM dual
  UNION ALL SELECT 'EVALUADOREXPERIENCIA' AS t FROM dual
  UNION ALL SELECT 'EVALUADORLOG' AS t FROM dual
  UNION ALL SELECT 'EVALUADORTIC' AS t FROM dual
  UNION ALL SELECT 'MODALIDADPART' AS t FROM dual
  UNION ALL SELECT 'PROCESOEVAL' AS t FROM dual
  UNION ALL SELECT 'PROYECTOVERSION' AS t FROM dual
  UNION ALL SELECT 'REGIONAL' AS t FROM dual
  UNION ALL SELECT 'RETONACIONAL' AS t FROM dual
  UNION ALL SELECT 'ROLEVALUADOR' AS t FROM dual
  UNION ALL SELECT 'TIPODOCUMENTOCONV' AS t FROM dual
  UNION ALL SELECT 'TIPODOCUMENTOEVAL' AS t FROM dual
  UNION ALL SELECT 'TIPOESTUDIO' AS t FROM dual
  UNION ALL SELECT 'USUARIOPERFIL' AS t FROM dual
  UNION ALL SELECT 'CENTROFORMACION' AS t FROM dual
  UNION ALL SELECT 'EVALUADORCONVOCATORIA' AS t FROM dual
  UNION ALL SELECT 'EVALUADORESTUDIO' AS t FROM dual
  UNION ALL SELECT 'EVALUADORPARTICIPACION' AS t FROM dual
  UNION ALL SELECT 'EVALUADORPARTPROYECTO' AS t FROM dual
  UNION ALL SELECT 'EVALUADORPRUEBA' AS t FROM dual
  UNION ALL SELECT 'PROYECTOAPROBADO' AS t FROM dual
  UNION ALL SELECT 'RETROFORMULARIO' AS t FROM dual
  UNION ALL SELECT 'RETROPREGUNTA' AS t FROM dual
  UNION ALL SELECT 'RETROSESION' AS t FROM dual
  UNION ALL SELECT 'RETROSUGERENCIA' AS t FROM dual
  UNION ALL SELECT 'CONVOCATORIADOCUMENTO' AS t FROM dual
  UNION ALL SELECT 'EVALUADORAPROBACION' AS t FROM dual
  UNION ALL SELECT 'EVALUADORCAPACITACION' AS t FROM dual
  UNION ALL SELECT 'EVALUADORCERTIFICADO' AS t FROM dual
  UNION ALL SELECT 'EVALUADORDOCUMENTO' AS t FROM dual
  UNION ALL SELECT 'EVALUADORPARTALCANCE' AS t FROM dual
  UNION ALL SELECT 'EVALUADORPARTGRUPO' AS t FROM dual
  UNION ALL SELECT 'RETROASIGNACION' AS t FROM dual
  UNION ALL SELECT 'RETRORESPUESTA' AS t FROM dual
  UNION ALL SELECT 'RETRORESPUESTAITEM' AS t FROM dual
)
SELECT e.t AS TABLA_QUE_FALTA FROM esperadas e
 WHERE NOT EXISTS (SELECT 1 FROM USER_TABLES u WHERE u.TABLE_NAME = e.t)
 ORDER BY 1;

-- 3. Las secuencias: deben ser 26 de 26.
SELECT 26 AS ESPERADAS, COUNT(*) AS CREADAS FROM USER_SEQUENCES
 WHERE SEQUENCE_NAME IN ('PROYECTOVERSION_SEQ', 'USUARIOPERFIL_SEQ', 'ROLEVALUADOR_SEQ', 'PROCESOEVAL_SEQ', 'TIPOESTUDIO_SEQ', 'EVALUADOR_SEQ', 'EVALUADORPARTICIPACION_SEQ', 'EVALUADOREXPERIENCIA_SEQ', 'EVALUADORTIC_SEQ', 'EVALUADORPRUEBA_SEQ', 'EVALUADORESTUDIO_SEQ', 'CONVPROYGUARDADO_SEQ', 'EVALUADORAPROBACION_SEQ', 'EVALUADORCAPACITACION_SEQ', 'EVALUADORPARTPROYECTO_SEQ', 'RETROFORMULARIO_SEQ', 'RETROPREGUNTA_SEQ', 'RETROASIGNACION_SEQ', 'RETROSESION_SEQ', 'RETRORESPUESTA_SEQ', 'RETRORESPUESTAITEM_SEQ', 'RETROSUGERENCIA_SEQ', 'EVALUADORPARTGRUPO_SEQ', 'EVALUADORPARTALCANCE_SEQ', 'EVALUADORLOG_SEQ', 'EVALUADORCERTIFICADO_SEQ');

-- 4. Los indices: deben ser 46 de 46. Los 5 UNICOS de esta lista no son
--    rendimiento, son reglas de negocio: sin ellos entran duplicados que el SEP
--    da por imposibles.
SELECT 46 AS ESPERADOS, COUNT(*) AS CREADOS FROM USER_INDEXES
 WHERE INDEX_NAME IN ('IX_CF_CIUDAD', 'IX_CF_REGIONAL', 'IX_CONVDOC_CONV', 'IX_CONVDOC_TIPO', 'IX_CPG_CONV', 'IX_EVALUADOR_ACTIVO', 'IX_APROB_FECHA', 'IX_CAPAC_PART', 'IX_CERT_ANIO', 'IX_CERT_PART', 'UQ_CERT_PART_VIGENTE', 'IX_CONV_ANIO', 'IX_CONV_SEP', 'UQ_EVALCONV_SEP_PERIODO', 'IX_EVALDOC_EVAL', 'IX_EVALDOC_PART', 'IX_EVALDOC_TIPO', 'IX_ESTUDIO_EVAL', 'IX_EXP_EVAL', 'IX_EVALLOG_EVAL', 'IX_EVALLOG_FECHA', 'IX_EVALLOG_PART', 'IX_EVALLOG_TABLA', 'IX_PARTGRUPO_GRUPO', 'IX_PART_CONVOCATORIA', 'IX_PART_ESTADO', 'IX_PART_EVAL_ANIO', 'IX_PARTPROY_GUARDADO', 'IX_PARTPROY_PART', 'IX_PARTPROY_PROYECTO', 'IX_PRUEBA_EVAL_ANIO', 'IX_PRUEBA_PART', 'IX_TIC_EVAL', 'IX_PROYECTOAPROBADO_FECHA', 'IX_PROYECTOVERSION_FECHA', 'IX_PROYECTOVERSION_PROY', 'UX_PROYECTOVERSION_FINAL', 'IX_RETROASIG_EVALUADO', 'IX_RETROASIG_EVALUADOR', 'UQ_RETROFORM_ACTIVO', 'IX_RETRORESP_EVALUADO', 'IX_RETRORESP_SES', 'IX_RETROITEM_RESP', 'IX_RETROSES_PART', 'UQ_ROLEVALUADOR_CODIGO', 'IX_USUARIOPERFIL_USU');

-- 5. Los 5 indices unicos, uno por uno. Los cinco deben aparecer con UNIQUE.
SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS, INDEX_TYPE, STATUS
  FROM USER_INDEXES
 WHERE INDEX_NAME IN ('UQ_CERT_PART_VIGENTE', 'UQ_EVALCONV_SEP_PERIODO',
                      'UX_PROYECTOVERSION_FINAL', 'UQ_RETROFORM_ACTIVO',
                      'UQ_ROLEVALUADOR_CODIGO')
 ORDER BY INDEX_NAME;

-- 6. Las 9 llaves hacia tablas del SENA NO deben existir todavia.
--    Esperado: 0. Se crean en el paso 3, cuando esten las 98 filas padre.
SELECT COUNT(*) AS LLAVES_EXTERNAS_YA_PUESTAS FROM USER_CONSTRAINTS
 WHERE CONSTRAINT_NAME IN ('FK_EVALUADOR_MUNICIPIO', 'FK_EVALUADOR_PERSONA', 'FK_PROYECTOVERSION_PROYECTO', 'FK_USUARIOPERFIL_PERFIL', 'FK_USUARIOPERFIL_USUARIO', 'FK_CF_CIUDAD', 'FK_EVALCONV_CONVSEP', 'FK_PART_DINAMIZADOR', 'FK_PROYECTOAPROBADO_PROY');

-- 7. Y lo mas importante: que NADA del SENA se movio. Estas cifras son las de
--    antes de empezar, medidas el 2026-09-10.
SELECT 'PERSONA' AS TABLA, 292177 AS ANTES, COUNT(*) AS AHORA FROM PERSONA
UNION ALL SELECT 'USUARIO', 78822, COUNT(*) FROM USUARIO
UNION ALL SELECT 'PROYECTO', 1019, COUNT(*) FROM PROYECTO
UNION ALL SELECT 'EMPRESA', 865, COUNT(*) FROM EMPRESA
UNION ALL SELECT 'ACCIONFORMACION', 3801, COUNT(*) FROM ACCIONFORMACION
UNION ALL SELECT 'DOCUMENTOSPERSONAS', 28396, COUNT(*) FROM DOCUMENTOSPERSONAS;
