-- v69 REVERSA — deshace exactamente lo que creo v69_tablas_sep_en_exadata.sql.
--
-- Los 65 nombres de aqui se extrajeron del propio v69, asi que esta
-- reversa NO PUEDE nombrar nada que el v69 no haya creado.
--
-- LEER ANTES DE CORRER:
--   · Esto se corre como SENADM, que tiene rol DBA. Un nombre mal escrito aqui
--     no falla: borra una tabla del SENA. No se edita a la ligera.
--   · No hay comodines ni bucles a proposito: una sentencia por objeto.
--   · Los indices y comentarios se van solos con su tabla; no hace falta borrarlos.
--   · Si el v69 se corrio a medias, sobran DROP: los que fallen con ORA-00942
--     (table or view does not exist) son los que nunca se crearon. Es normal.
--
-- El orden es el INVERSO al de creacion. CASCADE CONSTRAINTS suelta las llaves
-- entre las 39 sin tocar nada de fuera; PURGE evita dejar los segmentos LOB en
-- la papelera del Exadata.

SET DEFINE OFF;

-- 1. Primero las llaves hacia tablas del SENA, si se llegaron a crear.
--    Esto NO altera los datos de esas tablas: solo quita la referencia.
ALTER TABLE "EVALUADOR" DROP CONSTRAINT "FK_EVALUADOR_MUNICIPIO";   -- apuntaba a CIUDAD
ALTER TABLE "EVALUADOR" DROP CONSTRAINT "FK_EVALUADOR_PERSONA";   -- apuntaba a PERSONA
ALTER TABLE "PROYECTOVERSION" DROP CONSTRAINT "FK_PROYECTOVERSION_PROYECTO";   -- apuntaba a PROYECTO
ALTER TABLE "USUARIOPERFIL" DROP CONSTRAINT "FK_USUARIOPERFIL_PERFIL";   -- apuntaba a PERFIL
ALTER TABLE "USUARIOPERFIL" DROP CONSTRAINT "FK_USUARIOPERFIL_USUARIO";   -- apuntaba a USUARIO
ALTER TABLE "CENTROFORMACION" DROP CONSTRAINT "FK_CF_CIUDAD";   -- apuntaba a CIUDAD
ALTER TABLE "EVALUADORCONVOCATORIA" DROP CONSTRAINT "FK_EVALCONV_CONVSEP";   -- apuntaba a CONVOCATORIA
ALTER TABLE "EVALUADORPARTICIPACION" DROP CONSTRAINT "FK_PART_DINAMIZADOR";   -- apuntaba a PERSONA
ALTER TABLE "PROYECTOAPROBADO" DROP CONSTRAINT "FK_PROYECTOAPROBADO_PROY";   -- apuntaba a PROYECTO

-- 2. Las 39 tablas, en orden inverso al de creacion.
DROP TABLE "RETRORESPUESTAITEM" CASCADE CONSTRAINTS PURGE;
DROP TABLE "RETRORESPUESTA" CASCADE CONSTRAINTS PURGE;
DROP TABLE "RETROASIGNACION" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADORPARTGRUPO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADORPARTALCANCE" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADORDOCUMENTO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADORCERTIFICADO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADORCAPACITACION" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADORAPROBACION" CASCADE CONSTRAINTS PURGE;
DROP TABLE "CONVOCATORIADOCUMENTO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "RETROSUGERENCIA" CASCADE CONSTRAINTS PURGE;
DROP TABLE "RETROSESION" CASCADE CONSTRAINTS PURGE;
DROP TABLE "RETROPREGUNTA" CASCADE CONSTRAINTS PURGE;
DROP TABLE "RETROFORMULARIO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "PROYECTOAPROBADO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADORPRUEBA" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADORPARTPROYECTO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADORPARTICIPACION" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADORESTUDIO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADORCONVOCATORIA" CASCADE CONSTRAINTS PURGE;
DROP TABLE "CENTROFORMACION" CASCADE CONSTRAINTS PURGE;
DROP TABLE "USUARIOPERFIL" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TIPOESTUDIO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TIPODOCUMENTOEVAL" CASCADE CONSTRAINTS PURGE;
DROP TABLE "TIPODOCUMENTOCONV" CASCADE CONSTRAINTS PURGE;
DROP TABLE "ROLEVALUADOR" CASCADE CONSTRAINTS PURGE;
DROP TABLE "RETONACIONAL" CASCADE CONSTRAINTS PURGE;
DROP TABLE "REGIONAL" CASCADE CONSTRAINTS PURGE;
DROP TABLE "PROYECTOVERSION" CASCADE CONSTRAINTS PURGE;
DROP TABLE "PROCESOEVAL" CASCADE CONSTRAINTS PURGE;
DROP TABLE "MODALIDADPART" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADORTIC" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADORLOG" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADOREXPERIENCIA" CASCADE CONSTRAINTS PURGE;
DROP TABLE "EVALUADOR" CASCADE CONSTRAINTS PURGE;
DROP TABLE "ESTADOPARTICIPACION" CASCADE CONSTRAINTS PURGE;
DROP TABLE "CONVPROYGUARDADO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "ARTICULACIONTERRITORIAL" CASCADE CONSTRAINTS PURGE;
DROP TABLE "AREAEVALUACION" CASCADE CONSTRAINTS PURGE;

-- 3. Las 26 secuencias.
DROP SEQUENCE "PROYECTOVERSION_SEQ";
DROP SEQUENCE "USUARIOPERFIL_SEQ";
DROP SEQUENCE "ROLEVALUADOR_SEQ";
DROP SEQUENCE "PROCESOEVAL_SEQ";
DROP SEQUENCE "TIPOESTUDIO_SEQ";
DROP SEQUENCE "EVALUADOR_SEQ";
DROP SEQUENCE "EVALUADORPARTICIPACION_SEQ";
DROP SEQUENCE "EVALUADOREXPERIENCIA_SEQ";
DROP SEQUENCE "EVALUADORTIC_SEQ";
DROP SEQUENCE "EVALUADORPRUEBA_SEQ";
DROP SEQUENCE "EVALUADORESTUDIO_SEQ";
DROP SEQUENCE "CONVPROYGUARDADO_SEQ";
DROP SEQUENCE "EVALUADORAPROBACION_SEQ";
DROP SEQUENCE "EVALUADORCAPACITACION_SEQ";
DROP SEQUENCE "EVALUADORPARTPROYECTO_SEQ";
DROP SEQUENCE "RETROFORMULARIO_SEQ";
DROP SEQUENCE "RETROPREGUNTA_SEQ";
DROP SEQUENCE "RETROASIGNACION_SEQ";
DROP SEQUENCE "RETROSESION_SEQ";
DROP SEQUENCE "RETRORESPUESTA_SEQ";
DROP SEQUENCE "RETRORESPUESTAITEM_SEQ";
DROP SEQUENCE "RETROSUGERENCIA_SEQ";
DROP SEQUENCE "EVALUADORPARTGRUPO_SEQ";
DROP SEQUENCE "EVALUADORPARTALCANCE_SEQ";
DROP SEQUENCE "EVALUADORLOG_SEQ";
DROP SEQUENCE "EVALUADORCERTIFICADO_SEQ";

-- 4. Comprobacion: las tres cuentas deben quedar en 0.
SELECT COUNT(*) AS TABLAS_QUE_QUEDAN FROM USER_TABLES
 WHERE TABLE_NAME IN ('AREAEVALUACION', 'ARTICULACIONTERRITORIAL', 'CONVPROYGUARDADO', 'ESTADOPARTICIPACION', 'EVALUADOR', 'EVALUADOREXPERIENCIA', 'EVALUADORLOG', 'EVALUADORTIC', 'MODALIDADPART', 'PROCESOEVAL', 'PROYECTOVERSION', 'REGIONAL', 'RETONACIONAL', 'ROLEVALUADOR', 'TIPODOCUMENTOCONV', 'TIPODOCUMENTOEVAL', 'TIPOESTUDIO', 'USUARIOPERFIL', 'CENTROFORMACION', 'EVALUADORCONVOCATORIA', 'EVALUADORESTUDIO', 'EVALUADORPARTICIPACION', 'EVALUADORPARTPROYECTO', 'EVALUADORPRUEBA', 'PROYECTOAPROBADO', 'RETROFORMULARIO', 'RETROPREGUNTA', 'RETROSESION', 'RETROSUGERENCIA', 'CONVOCATORIADOCUMENTO', 'EVALUADORAPROBACION', 'EVALUADORCAPACITACION', 'EVALUADORCERTIFICADO', 'EVALUADORDOCUMENTO', 'EVALUADORPARTALCANCE', 'EVALUADORPARTGRUPO', 'RETROASIGNACION', 'RETRORESPUESTA', 'RETRORESPUESTAITEM');
SELECT COUNT(*) AS SECUENCIAS_QUE_QUEDAN FROM USER_SEQUENCES
 WHERE SEQUENCE_NAME IN ('PROYECTOVERSION_SEQ', 'USUARIOPERFIL_SEQ', 'ROLEVALUADOR_SEQ', 'PROCESOEVAL_SEQ', 'TIPOESTUDIO_SEQ', 'EVALUADOR_SEQ', 'EVALUADORPARTICIPACION_SEQ', 'EVALUADOREXPERIENCIA_SEQ', 'EVALUADORTIC_SEQ', 'EVALUADORPRUEBA_SEQ', 'EVALUADORESTUDIO_SEQ', 'CONVPROYGUARDADO_SEQ', 'EVALUADORAPROBACION_SEQ', 'EVALUADORCAPACITACION_SEQ', 'EVALUADORPARTPROYECTO_SEQ', 'RETROFORMULARIO_SEQ', 'RETROPREGUNTA_SEQ', 'RETROASIGNACION_SEQ', 'RETROSESION_SEQ', 'RETRORESPUESTA_SEQ', 'RETRORESPUESTAITEM_SEQ', 'RETROSUGERENCIA_SEQ', 'EVALUADORPARTGRUPO_SEQ', 'EVALUADORPARTALCANCE_SEQ', 'EVALUADORLOG_SEQ', 'EVALUADORCERTIFICADO_SEQ');
SELECT COUNT(*) AS INDICES_QUE_QUEDAN FROM USER_INDEXES
 WHERE INDEX_NAME IN ('IX_CF_CIUDAD', 'IX_CF_REGIONAL', 'IX_CONVDOC_CONV', 'IX_CONVDOC_TIPO', 'IX_CPG_CONV', 'IX_EVALUADOR_ACTIVO', 'IX_APROB_FECHA', 'IX_CAPAC_PART', 'IX_CERT_ANIO', 'IX_CERT_PART', 'UQ_CERT_PART_VIGENTE', 'IX_CONV_ANIO', 'IX_CONV_SEP', 'UQ_EVALCONV_SEP_PERIODO', 'IX_EVALDOC_EVAL', 'IX_EVALDOC_PART', 'IX_EVALDOC_TIPO', 'IX_ESTUDIO_EVAL', 'IX_EXP_EVAL', 'IX_EVALLOG_EVAL', 'IX_EVALLOG_FECHA', 'IX_EVALLOG_PART', 'IX_EVALLOG_TABLA', 'IX_PARTGRUPO_GRUPO', 'IX_PART_CONVOCATORIA', 'IX_PART_ESTADO', 'IX_PART_EVAL_ANIO', 'IX_PARTPROY_GUARDADO', 'IX_PARTPROY_PART', 'IX_PARTPROY_PROYECTO', 'IX_PRUEBA_EVAL_ANIO', 'IX_PRUEBA_PART', 'IX_TIC_EVAL', 'IX_PROYECTOAPROBADO_FECHA', 'IX_PROYECTOVERSION_FECHA', 'IX_PROYECTOVERSION_PROY', 'UX_PROYECTOVERSION_FINAL', 'IX_RETROASIG_EVALUADO', 'IX_RETROASIG_EVALUADOR', 'UQ_RETROFORM_ACTIVO', 'IX_RETRORESP_EVALUADO', 'IX_RETRORESP_SES', 'IX_RETROITEM_RESP', 'IX_RETROSES_PART', 'UQ_ROLEVALUADOR_CODIGO', 'IX_USUARIOPERFIL_USU');
