-- Migración: Componente de alineación como campo único en ACCIONFORMACION

ALTER TABLE ACCIONFORMACION ADD ACCIONFORMACIONCOMPONENTEID NUMBER;

ALTER TABLE ACCIONFORMACION
  ADD CONSTRAINT FK_AF_ALINEACION_COMP
  FOREIGN KEY (ACCIONFORMACIONCOMPONENTEID)
  REFERENCES AFCOMPONENTE(AFCOMPONENTEID);

COMMIT;
