-- v70 — las columnas que el SEP usa y al Exadata del SENA le faltan.
--
-- Generado comparando las 220 tablas que existen en las dos bases, columna a
-- columna. No es una lista de memoria: sale del diccionario.
--
-- Son 24 columnas en 11 tablas. TODAS son ALTER TABLE ADD: no se
-- modifica ni se borra ninguna columna existente, y ninguna fila cambia de
-- valor. En Oracle 12c en adelante agregar una columna es un cambio de
-- metadatos: es instantaneo aunque la tabla tenga millones de filas.
--
-- POR QUE VA AHORA Y NO DESPUES: sin estas columnas, los INSERT de la
-- migracion fallan con ORA-00904 (identificador no valido). Lo descubrio el
-- ensayo del paso 3f-previo al intentar meter CONVOCATORIARESULTADOSPUBLICADOS.
--
-- Las NOT NULL llevan DEFAULT obligatoriamente: sin el, el ALTER falla sobre
-- las filas que ya existen. Van marcadas abajo.
--
-- Reversa: ALTER TABLE <tabla> DROP COLUMN <columna>. Como ninguna tenia datos
-- antes, no se pierde nada al quitarlas.
--
-- Correr como SENADM.

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET DEFINE OFF;
SET SERVEROUTPUT ON;

DECLARE
  v_base VARCHAR2(128);
BEGIN
  SELECT SYS_CONTEXT('USERENV','DB_NAME') INTO v_base FROM dual;
  IF v_base <> 'PDB_SEPDB' THEN
    RAISE_APPLICATION_ERROR(-20001, 'BASE EQUIVOCADA: estas en ' || v_base);
  END IF;
  DBMS_OUTPUT.PUT_LINE('Base correcta: ' || v_base);
END;
/


-- ACCIONFORMACION  (3801 filas en el Exadata)
ALTER TABLE SENADM."ACCIONFORMACION" ADD ("ACCIONFORMACIONJUSTCAMPESINO" NCLOB);
ALTER TABLE SENADM."ACCIONFORMACION" ADD ("ACCIONFORMACIONNUMPOPULAR" NUMBER);
ALTER TABLE SENADM."ACCIONFORMACION" ADD ("ACCIONFORMACIONJUSTPOPULAR" NCLOB);
ALTER TABLE SENADM."ACCIONFORMACION" ADD ("ACCIONFORMACIONCOMPONENTEID" NUMBER);
ALTER TABLE SENADM."ACCIONFORMACION" ADD ("ACCIONFORMACIONESTADOAPROBACION" NUMBER(1,0));
ALTER TABLE SENADM."ACCIONFORMACION" ADD ("ACCIONFORMACIONMOTIVORECHAZO" CLOB);

-- AFCOMPONENTE  (381 filas en el Exadata)
ALTER TABLE SENADM."AFCOMPONENTE" ADD ("RETONACIONALID" NUMBER);

-- AFGRUPO  (14183 filas en el Exadata)
ALTER TABLE SENADM."AFGRUPO" ADD ("AFGRUPOJUSTIFICACION" NCLOB);

-- AFRUBRO  (10256 filas en el Exadata)
ALTER TABLE SENADM."AFRUBRO" ADD ("AFRUBROJUSTIFICACION" NVARCHAR2(2000));
ALTER TABLE SENADM."AFRUBRO" ADD ("AFRUBRONUMHORAS" NUMBER DEFAULT 0);
ALTER TABLE SENADM."AFRUBRO" ADD ("AFRUBROPAQUETE" NVARCHAR2(10));
ALTER TABLE SENADM."AFRUBRO" ADD ("AFRUBRONUMEROGRUPOS" NUMBER DEFAULT 1);
ALTER TABLE SENADM."AFRUBRO" ADD ("AFRUBROPORCENTAJECOFINANCIACION" NUMBER);
ALTER TABLE SENADM."AFRUBRO" ADD ("AFRUBROPORCENTAJEDINERO" NUMBER);
ALTER TABLE SENADM."AFRUBRO" ADD ("AFRUBROPORCENTAJEESPECIE" NUMBER);

-- AFRUBRO1  (0 filas en el Exadata)
ALTER TABLE SENADM."AFRUBRO1" ADD ("AFRUBRONUMHORAS" NUMBER DEFAULT 0);
ALTER TABLE SENADM."AFRUBRO1" ADD ("AFRUBROPAQUETE" NVARCHAR2(10));

-- CONVOCATORIA  (9 filas en el Exadata)
--   NOT NULL: lleva DEFAULT 0 para las 9 filas que ya existen
ALTER TABLE SENADM."CONVOCATORIA" ADD ("CONVOCATORIARESULTADOSPUBLICADOS" NUMBER(1,0) DEFAULT 0 NOT NULL);

-- EMPRESA  (865 filas en el Exadata)
ALTER TABLE SENADM."EMPRESA" ADD ("EMPRESAESLABONES" NCLOB);
ALTER TABLE SENADM."EMPRESA" ADD ("EMPRESAINTERACCIONES" NCLOB);

-- FUENTEHERRAMIENTA  (11 filas en el Exadata)
--   NOT NULL: lleva DEFAULT 1 para las 11 filas que ya existen
ALTER TABLE SENADM."FUENTEHERRAMIENTA" ADD ("FUENTEHERRAMIENTAESTADO" NUMBER(1,0) DEFAULT 1 NOT NULL);

-- PROYECTO  (1019 filas en el Exadata)
ALTER TABLE SENADM."PROYECTO" ADD ("PROYECTOMOTIVORECHAZO" CLOB);

-- RUBRO  (258 filas en el Exadata)
ALTER TABLE SENADM."RUBRO" ADD ("RUBROMODALIDAD" NVARCHAR2(300));

-- UNIDADTEMATICA  (13947 filas en el Exadata)
ALTER TABLE SENADM."UNIDADTEMATICA" ADD ("ARTICULACIONTERRITORIALID" NUMBER);


-- ==================== COMPROBACION ====================
-- Deben aparecer las 24 columnas. Si falta alguna, el ALTER no corrio.
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, NULLABLE
  FROM ALL_TAB_COLUMNS WHERE OWNER='SENADM' AND (TABLE_NAME, COLUMN_NAME) IN (
    ('ACCIONFORMACION','ACCIONFORMACIONJUSTCAMPESINO'),
    ('ACCIONFORMACION','ACCIONFORMACIONNUMPOPULAR'),
    ('ACCIONFORMACION','ACCIONFORMACIONJUSTPOPULAR'),
    ('ACCIONFORMACION','ACCIONFORMACIONCOMPONENTEID'),
    ('ACCIONFORMACION','ACCIONFORMACIONESTADOAPROBACION'),
    ('ACCIONFORMACION','ACCIONFORMACIONMOTIVORECHAZO'),
    ('AFCOMPONENTE','RETONACIONALID'),
    ('AFGRUPO','AFGRUPOJUSTIFICACION'),
    ('AFRUBRO','AFRUBROJUSTIFICACION'),
    ('AFRUBRO','AFRUBRONUMHORAS'),
    ('AFRUBRO','AFRUBROPAQUETE'),
    ('AFRUBRO','AFRUBRONUMEROGRUPOS'),
    ('AFRUBRO','AFRUBROPORCENTAJECOFINANCIACION'),
    ('AFRUBRO','AFRUBROPORCENTAJEDINERO'),
    ('AFRUBRO','AFRUBROPORCENTAJEESPECIE'),
    ('AFRUBRO1','AFRUBRONUMHORAS'),
    ('AFRUBRO1','AFRUBROPAQUETE'),
    ('CONVOCATORIA','CONVOCATORIARESULTADOSPUBLICADOS'),
    ('EMPRESA','EMPRESAESLABONES'),
    ('EMPRESA','EMPRESAINTERACCIONES'),
    ('FUENTEHERRAMIENTA','FUENTEHERRAMIENTAESTADO'),
    ('PROYECTO','PROYECTOMOTIVORECHAZO'),
    ('RUBRO','RUBROMODALIDAD'),
    ('UNIDADTEMATICA','ARTICULACIONTERRITORIALID')
  ) ORDER BY TABLE_NAME, COLUMN_NAME;

-- Y que ninguna tabla perdio filas:
SELECT 'ACCIONFORMACION' AS TABLA, 3801 AS ANTES, COUNT(*) AS AHORA FROM SENADM."ACCIONFORMACION"
UNION ALL SELECT 'AFCOMPONENTE' AS TABLA, 381 AS ANTES, COUNT(*) AS AHORA FROM SENADM."AFCOMPONENTE"
UNION ALL SELECT 'AFGRUPO' AS TABLA, 14183 AS ANTES, COUNT(*) AS AHORA FROM SENADM."AFGRUPO"
UNION ALL SELECT 'AFRUBRO' AS TABLA, 10256 AS ANTES, COUNT(*) AS AHORA FROM SENADM."AFRUBRO"
UNION ALL SELECT 'AFRUBRO1' AS TABLA, 0 AS ANTES, COUNT(*) AS AHORA FROM SENADM."AFRUBRO1"
UNION ALL SELECT 'CONVOCATORIA' AS TABLA, 9 AS ANTES, COUNT(*) AS AHORA FROM SENADM."CONVOCATORIA"
UNION ALL SELECT 'EMPRESA' AS TABLA, 865 AS ANTES, COUNT(*) AS AHORA FROM SENADM."EMPRESA"
UNION ALL SELECT 'FUENTEHERRAMIENTA' AS TABLA, 11 AS ANTES, COUNT(*) AS AHORA FROM SENADM."FUENTEHERRAMIENTA"
UNION ALL SELECT 'PROYECTO' AS TABLA, 1019 AS ANTES, COUNT(*) AS AHORA FROM SENADM."PROYECTO"
UNION ALL SELECT 'RUBRO' AS TABLA, 258 AS ANTES, COUNT(*) AS AHORA FROM SENADM."RUBRO"
UNION ALL SELECT 'UNIDADTEMATICA' AS TABLA, 13947 AS ANTES, COUNT(*) AS AHORA FROM SENADM."UNIDADTEMATICA";


-- ==================== REVERSA ====================
-- ALTER TABLE SENADM."ACCIONFORMACION" DROP COLUMN "ACCIONFORMACIONJUSTCAMPESINO";
-- ALTER TABLE SENADM."ACCIONFORMACION" DROP COLUMN "ACCIONFORMACIONNUMPOPULAR";
-- ALTER TABLE SENADM."ACCIONFORMACION" DROP COLUMN "ACCIONFORMACIONJUSTPOPULAR";
-- ALTER TABLE SENADM."ACCIONFORMACION" DROP COLUMN "ACCIONFORMACIONCOMPONENTEID";
-- ALTER TABLE SENADM."ACCIONFORMACION" DROP COLUMN "ACCIONFORMACIONESTADOAPROBACION";
-- ALTER TABLE SENADM."ACCIONFORMACION" DROP COLUMN "ACCIONFORMACIONMOTIVORECHAZO";
-- ALTER TABLE SENADM."AFCOMPONENTE" DROP COLUMN "RETONACIONALID";
-- ALTER TABLE SENADM."AFGRUPO" DROP COLUMN "AFGRUPOJUSTIFICACION";
-- ALTER TABLE SENADM."AFRUBRO" DROP COLUMN "AFRUBROJUSTIFICACION";
-- ALTER TABLE SENADM."AFRUBRO" DROP COLUMN "AFRUBRONUMHORAS";
-- ALTER TABLE SENADM."AFRUBRO" DROP COLUMN "AFRUBROPAQUETE";
-- ALTER TABLE SENADM."AFRUBRO" DROP COLUMN "AFRUBRONUMEROGRUPOS";
-- ALTER TABLE SENADM."AFRUBRO" DROP COLUMN "AFRUBROPORCENTAJECOFINANCIACION";
-- ALTER TABLE SENADM."AFRUBRO" DROP COLUMN "AFRUBROPORCENTAJEDINERO";
-- ALTER TABLE SENADM."AFRUBRO" DROP COLUMN "AFRUBROPORCENTAJEESPECIE";
-- ALTER TABLE SENADM."AFRUBRO1" DROP COLUMN "AFRUBRONUMHORAS";
-- ALTER TABLE SENADM."AFRUBRO1" DROP COLUMN "AFRUBROPAQUETE";
-- ALTER TABLE SENADM."CONVOCATORIA" DROP COLUMN "CONVOCATORIARESULTADOSPUBLICADOS";
-- ALTER TABLE SENADM."EMPRESA" DROP COLUMN "EMPRESAESLABONES";
-- ALTER TABLE SENADM."EMPRESA" DROP COLUMN "EMPRESAINTERACCIONES";
-- ALTER TABLE SENADM."FUENTEHERRAMIENTA" DROP COLUMN "FUENTEHERRAMIENTAESTADO";
-- ALTER TABLE SENADM."PROYECTO" DROP COLUMN "PROYECTOMOTIVORECHAZO";
-- ALTER TABLE SENADM."RUBRO" DROP COLUMN "RUBROMODALIDAD";
-- ALTER TABLE SENADM."UNIDADTEMATICA" DROP COLUMN "ARTICULACIONTERRITORIALID";