-- PASO 3f (v71) — las 9 llaves foraneas hacia las tablas que ya existian.
--
-- Es el bloque 5 de la v69, separado en su propio archivo. Los bloques 1 a 4 de
-- la v69 ya estan aplicados; correr aquel archivo entero volveria a fallar en los
-- CREATE TABLE. Este se corre solo.
--
-- POR QUE HASTA AHORA
-- Estas llaves apuntan a CIUDAD, CONVOCATORIA, PERSONA, PROYECTO, PERFIL y
-- USUARIO. Las filas padre que faltaban ya entraron en los pasos 3b, 3d y
-- 3f-previo: 24 PERSONA, 82 USUARIO, 1 PERFIL, 5 CONVOCATORIA, 2 EMPRESA y
-- 2 PROYECTO. El mapa de traduccion de ids esta en respaldos/, fuera del repo.
--
-- POR QUE VA ANTES DEL PASO 4 Y NO DESPUES
-- Las 9 tablas hijas estan VACIAS: crear la llave ahora no valida ninguna fila y
-- es instantaneo. Y a partir de aqui la base misma vigila el paso 4 — si un id
-- quedara mal traducido, el INSERT muere con ORA-02291 en vez de dejar una fila
-- huerfana que nadie note.
--
-- ESTO ES DDL: cada ALTER confirma solo. No hay transaccion ni ROLLBACK posible.
-- Por eso va WHENEVER SQLERROR EXIT FAILURE: si una falla, para ahi mismo y las
-- anteriores quedan creadas. No es grave — no se toca ni una fila — y la reversa
-- del final las quita.
--
-- COMPROBADO CONTRA EL EXADATA ANTES DE GENERAR ESTO
--   · Las 9 tablas hijas existen y tienen 0 filas.
--   · Las 9 columnas hijas existen.
--   · Ninguna de las 9 llaves existe todavia.
--   · Las columnas de la clave primaria del padre se leyeron del diccionario del
--     Exadata, no de un mapa. La primera version salio con REFERENCES "CIUDAD" ()
--     y murio con ORA-00936 justo por eso.
--
-- Correr como SENADM, con F5.

WHENEVER SQLERROR EXIT FAILURE;
SET DEFINE OFF;
SET SERVEROUTPUT ON;

-- ==================== GUARDAS ====================
DECLARE
  v_base VARCHAR2(128); v_n NUMBER;
BEGIN
  SELECT SYS_CONTEXT('USERENV','DB_NAME') INTO v_base FROM dual;
  IF v_base <> 'PDB_SEPDB' THEN
    RAISE_APPLICATION_ERROR(-20001, 'BASE EQUIVOCADA: estas en ' || v_base);
  END IF;

  -- ninguna de las 9 llaves puede existir ya
  SELECT COUNT(*) INTO v_n FROM ALL_CONSTRAINTS
   WHERE OWNER='SENADM' AND CONSTRAINT_NAME IN (
     'FK_CF_CIUDAD',
     'FK_EVALCONV_CONVSEP',
     'FK_EVALUADOR_MUNICIPIO',
     'FK_EVALUADOR_PERSONA',
     'FK_PART_DINAMIZADOR',
     'FK_PROYECTOAPROBADO_PROY',
     'FK_PROYECTOVERSION_PROYECTO',
     'FK_USUARIOPERFIL_PERFIL',
     'FK_USUARIOPERFIL_USUARIO');
  IF v_n <> 0 THEN
    RAISE_APPLICATION_ERROR(-20002, 'Ya existen ' || v_n || ' de las 9 llaves. Esto ya se corrio.');
  END IF;

  -- las filas padre del 3f-previo tienen que estar
  SELECT COUNT(*) INTO v_n FROM SENADM.CONVOCATORIA WHERE "CONVOCATORIAID" BETWEEN 10 AND 14;
  IF v_n <> 5 THEN
    RAISE_APPLICATION_ERROR(-20003, 'Faltan convocatorias del 3f-previo: hay ' || v_n || ' de 5.');
  END IF;
  SELECT COUNT(*) INTO v_n FROM SENADM.PROYECTO WHERE "PROYECTOID" IN (3049, 3050);
  IF v_n <> 2 THEN
    RAISE_APPLICATION_ERROR(-20004, 'Faltan los 2 proyectos del 3f-previo: hay ' || v_n || ' de 2.');
  END IF;

  DBMS_OUTPUT.PUT_LINE('Base ' || v_base
    || ' — 0 de las 9 llaves creadas, filas padre presentes. Adelante.');
END;
/


-- ==================== LAS 9 LLAVES ====================

-- CENTROFORMACION.CIUDADID -> CIUDAD  (el centro de formacion vive en un municipio)
--   CIUDAD tiene 1126 filas · su PK es SYS_C0011095 sobre ("CIUDADID")
ALTER TABLE SENADM."CENTROFORMACION" ADD CONSTRAINT "FK_CF_CIUDAD"
  FOREIGN KEY ("CIUDADID") REFERENCES SENADM."CIUDAD" ("CIUDADID");

-- EVALUADORCONVOCATORIA.CONVOCATORIASEPID -> CONVOCATORIA  (la convocatoria de evaluadores cuelga de una convocatoria del SEP)
--   CONVOCATORIA tiene 14 filas · su PK es SYS_C0011124 sobre ("CONVOCATORIAID")
ALTER TABLE SENADM."EVALUADORCONVOCATORIA" ADD CONSTRAINT "FK_EVALCONV_CONVSEP"
  FOREIGN KEY ("CONVOCATORIASEPID") REFERENCES SENADM."CONVOCATORIA" ("CONVOCATORIAID");

-- EVALUADOR.EVALUADORMUNICIPIOID -> CIUDAD  (el evaluador reside en un municipio)
--   CIUDAD tiene 1126 filas · su PK es SYS_C0011095 sobre ("CIUDADID")
ALTER TABLE SENADM."EVALUADOR" ADD CONSTRAINT "FK_EVALUADOR_MUNICIPIO"
  FOREIGN KEY ("EVALUADORMUNICIPIOID") REFERENCES SENADM."CIUDAD" ("CIUDADID");

-- EVALUADOR.PERSONAID -> PERSONA  (todo evaluador es una persona del SENA)
--   PERSONA tiene 292201 filas · su PK es SYS_C0025042 sobre ("PERSONAID")
ALTER TABLE SENADM."EVALUADOR" ADD CONSTRAINT "FK_EVALUADOR_PERSONA"
  FOREIGN KEY ("PERSONAID") REFERENCES SENADM."PERSONA" ("PERSONAID");

-- EVALUADORPARTICIPACION.DINAMIZADORPERSONAID -> PERSONA  (quien dinamiza la participacion tambien es una persona)
--   PERSONA tiene 292201 filas · su PK es SYS_C0025042 sobre ("PERSONAID")
ALTER TABLE SENADM."EVALUADORPARTICIPACION" ADD CONSTRAINT "FK_PART_DINAMIZADOR"
  FOREIGN KEY ("DINAMIZADORPERSONAID") REFERENCES SENADM."PERSONA" ("PERSONAID");

-- PROYECTOAPROBADO.PROYECTOID -> PROYECTO  (el proyecto aprobado apunta al proyecto real)
--   PROYECTO tiene 1021 filas · su PK es SYS_C0011020 sobre ("PROYECTOID")
ALTER TABLE SENADM."PROYECTOAPROBADO" ADD CONSTRAINT "FK_PROYECTOAPROBADO_PROY"
  FOREIGN KEY ("PROYECTOID") REFERENCES SENADM."PROYECTO" ("PROYECTOID");

-- PROYECTOVERSION.PROYECTOID -> PROYECTO  (cada version es version de un proyecto)
--   PROYECTO tiene 1021 filas · su PK es SYS_C0011020 sobre ("PROYECTOID")
ALTER TABLE SENADM."PROYECTOVERSION" ADD CONSTRAINT "FK_PROYECTOVERSION_PROYECTO"
  FOREIGN KEY ("PROYECTOID") REFERENCES SENADM."PROYECTO" ("PROYECTOID");

-- USUARIOPERFIL.PERFILID -> PERFIL  (el multirol asigna un perfil...)
--   PERFIL tiene 15 filas · su PK es SYS_C0011116 sobre ("PERFILID")
ALTER TABLE SENADM."USUARIOPERFIL" ADD CONSTRAINT "FK_USUARIOPERFIL_PERFIL"
  FOREIGN KEY ("PERFILID") REFERENCES SENADM."PERFIL" ("PERFILID");

-- USUARIOPERFIL.USUARIOID -> USUARIO  (...a un usuario)
--   USUARIO tiene 78903 filas · su PK es SYS_C0011099 sobre ("USUARIOID")
ALTER TABLE SENADM."USUARIOPERFIL" ADD CONSTRAINT "FK_USUARIOPERFIL_USUARIO"
  FOREIGN KEY ("USUARIOID") REFERENCES SENADM."USUARIO" ("USUARIOID");


-- ==================== COMPROBACION ====================
-- Tienen que salir las 9, todas ENABLED y VALIDATED.
SELECT c.CONSTRAINT_NAME, c.TABLE_NAME AS HIJA, cc.COLUMN_NAME AS COLUMNA,
       rc.TABLE_NAME AS PADRE, c.STATUS, c.VALIDATED
  FROM ALL_CONSTRAINTS c
  JOIN ALL_CONS_COLUMNS cc ON cc.OWNER=c.OWNER AND cc.CONSTRAINT_NAME=c.CONSTRAINT_NAME
  JOIN ALL_CONSTRAINTS rc ON rc.OWNER=c.R_OWNER AND rc.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME
 WHERE c.OWNER='SENADM' AND c.CONSTRAINT_NAME IN (
   'FK_CF_CIUDAD',
   'FK_EVALCONV_CONVSEP',
   'FK_EVALUADOR_MUNICIPIO',
   'FK_EVALUADOR_PERSONA',
   'FK_PART_DINAMIZADOR',
   'FK_PROYECTOAPROBADO_PROY',
   'FK_PROYECTOVERSION_PROYECTO',
   'FK_USUARIOPERFIL_PERFIL',
   'FK_USUARIOPERFIL_USUARIO')
 ORDER BY c.TABLE_NAME, c.CONSTRAINT_NAME;

-- Y que las tablas del SENA no perdieron ni ganaron filas:
SELECT 'PERSONA' AS TABLA, 292201 AS ESPERADO, COUNT(*) AS AHORA FROM SENADM."PERSONA"
UNION ALL SELECT 'USUARIO' AS TABLA, 78903 AS ESPERADO, COUNT(*) AS AHORA FROM SENADM."USUARIO"
UNION ALL SELECT 'PROYECTO' AS TABLA, 1021 AS ESPERADO, COUNT(*) AS AHORA FROM SENADM."PROYECTO"
UNION ALL SELECT 'EMPRESA' AS TABLA, 867 AS ESPERADO, COUNT(*) AS AHORA FROM SENADM."EMPRESA"
UNION ALL SELECT 'CONVOCATORIA' AS TABLA, 14 AS ESPERADO, COUNT(*) AS AHORA FROM SENADM."CONVOCATORIA"
UNION ALL SELECT 'CIUDAD' AS TABLA, 1126 AS ESPERADO, COUNT(*) AS AHORA FROM SENADM."CIUDAD"
UNION ALL SELECT 'PERFIL' AS TABLA, 15 AS ESPERADO, COUNT(*) AS AHORA FROM SENADM."PERFIL";


-- ==================== REVERSA ====================
-- Quita las llaves sin tocar una sola fila. Descomentar y correr.
-- ALTER TABLE SENADM."CENTROFORMACION" DROP CONSTRAINT "FK_CF_CIUDAD";
-- ALTER TABLE SENADM."EVALUADORCONVOCATORIA" DROP CONSTRAINT "FK_EVALCONV_CONVSEP";
-- ALTER TABLE SENADM."EVALUADOR" DROP CONSTRAINT "FK_EVALUADOR_MUNICIPIO";
-- ALTER TABLE SENADM."EVALUADOR" DROP CONSTRAINT "FK_EVALUADOR_PERSONA";
-- ALTER TABLE SENADM."EVALUADORPARTICIPACION" DROP CONSTRAINT "FK_PART_DINAMIZADOR";
-- ALTER TABLE SENADM."PROYECTOAPROBADO" DROP CONSTRAINT "FK_PROYECTOAPROBADO_PROY";
-- ALTER TABLE SENADM."PROYECTOVERSION" DROP CONSTRAINT "FK_PROYECTOVERSION_PROYECTO";
-- ALTER TABLE SENADM."USUARIOPERFIL" DROP CONSTRAINT "FK_USUARIOPERFIL_PERFIL";
-- ALTER TABLE SENADM."USUARIOPERFIL" DROP CONSTRAINT "FK_USUARIOPERFIL_USUARIO";
