-- =============================================================================
-- Migración: Convocatoria 10 + Rubros FCE-2026 + Estructura RUBRO/AFRUBRO1
-- Versión: 8.0
-- Fecha: 2026-04-21
-- Autor: JoSeLoDiAz
-- =============================================================================

-- 1. RUBROPAQUETE NUMBER -> NVARCHAR2(10) (codigos descriptivos PA01..PA15)
ALTER TABLE RUBRO ADD RUBROPAQUETE_COD NVARCHAR2(10);
UPDATE RUBRO SET RUBROPAQUETE_COD = CASE RUBROPAQUETE
  WHEN 0  THEN 'TRANSF'
  WHEN 1  THEN 'PA01'  WHEN 2  THEN 'PA02'  WHEN 3  THEN 'PA03'
  WHEN 4  THEN 'PA04'  WHEN 5  THEN 'PA05'  WHEN 6  THEN 'PA06'
  WHEN 7  THEN 'PA07'  WHEN 8  THEN 'PA08'  WHEN 9  THEN 'PA09'
  WHEN 10 THEN 'PA10'  WHEN 11 THEN 'PA11'  WHEN 13 THEN 'PA13'
  WHEN 15 THEN 'PA15'  ELSE 'PA05' END;
ALTER TABLE RUBRO DROP COLUMN RUBROPAQUETE;
ALTER TABLE RUBRO RENAME COLUMN RUBROPAQUETE_COD TO RUBROPAQUETE;

-- Referencia paquetes:
-- PA01=Horas capacitador  PA02=Unidades traduccion  PA03=Dias alquiler salon
-- PA04=Unidades cuadernos PA05=Fijo sin multiplicador PA06=Dias alojamiento
-- PA07=Virtual global/benef PA08=Capacitador x dia   PA09=Lider/especial
-- PA10=Material impreso/digital x unidad  PA11=Hora/beneficiario
-- PA13=Dias/unidades promo PA14=Minutos video PA15=% gastos operacion
-- TRANSF=Transferencia de conocimiento

-- 2. RUBROMODALIDAD: lista modalidades permitidas separadas por coma
ALTER TABLE RUBRO ADD RUBROMODALIDAD NVARCHAR2(300);

-- 3. AFRUBRO1: columnas faltantes para el formulario web
ALTER TABLE AFRUBRO1 ADD AFRUBROJUSTIFICACION NVARCHAR2(3000);
ALTER TABLE AFRUBRO1 ADD AFRUBRONUMHORAS NUMBER DEFAULT 0;
ALTER TABLE AFRUBRO1 ADD AFRUBROPAQUETE NVARCHAR2(10);

COMMIT;

-- 4. Rubros convocatoria 10 (FCE-2026) - 58 rubros
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (344,10,N'R01.1.1',N'R01.1.1 HONORARIOS - CAPACITADOR NACIONAL - TÉCNICO Y/O TECNÓLOGO TITULADO, CON EXPERIENCIA RELACIONADA COMPROBADA MÍNIMO DE CINCO (5) AÑOS. SE ACEPTA LA EQUIVALENCIA DEL TÍTULO DE TÉCNICO Y/O TECNÓLOGO',N'TÉCNICO Y/O TECNÓLOGO TITULADO, CON EXPERIENCIA RELACIONADA
COMPROBADA MÍNIMO DE CINCO (5) AÑOS.
SE ACEPTA LA EQUIVALENCIA DEL TÍTULO DE TÉCNICO Y/O TECNÓLOGO
POR:
A. HABER TERMINADO MATERIAS DE LA FORMACIÓN DE TÉCNICO
Y/O TECNÓLOGO Y 1 AÑOS DE EXPERIENCIA RELACIONADA, ADICIONAL A
LA EXIGIDA, O
B. APROBACIÓN DE 2 AÑOS DE EDUCACIÓN SUPERIOR, Y 1 AÑO
DE EXPERIENCIA RELACIONADA ADICIONAL A LA EXIGIDA, O
C. ACREDITAR LA CERTIFICACIÓN VIGENTE DE COMPETENCIAS EN
NORMAS QUE GUARDEN RELACIÓN CON EL OBJETO DE LA FORMACIÓN Y 1
AÑO DE EXPERIENCIA RELACIONADA ADICIONAL A LA EXIGIDA',292362,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA01',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (345,10,N'R01.1.2',N'R01.1.2 HONORARIOS - CAPACITADOR NACIONAL - PROFESIONAL TITULADO CON EXPERIENCIA RELACIONADA COMPROBADA, MÍNIMO DE TRES (3) AÑOS',N'PROFESIONAL TITULADO CON EXPERIENCIA RELACIONADA COMPROBADA,
MÍNIMO DE TRES (3) AÑOS.',380169,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA01',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (346,10,N'R01.1.3',N'R01.1.3 HONORARIOS - CAPACITADOR NACIONAL - PROFESIONAL CON TÍTULO DE ESPECIALIZACIÓN Y EXPERIENCIA RELACIONADA COMPROBADA, MÍNIMO DE TRES (3) AÑOS',N'PROFESIONAL CON TÍTULO DE ESPECIALIZACIÓN Y EXPERIENCIA
RELACIONADA COMPROBADA, MÍNIMO DE TRES (3) AÑOS.
SE ACEPTA LA EQUIVALENCIA DEL TÍTULO DE ESPECIALIZACIÓN POR: DOS (2) AÑOS DE EXPERIENCIA PROFESIONAL ADICIONAL A LA EXIGIDA,
RELACIONADA CON LA FORMACIÓN A IMPARTIR, SIEMPRE Y CUANDO SE
ACREDITE EL TÍTULO PROFESIONAL.',476684,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA01',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (347,10,N'R01.1.4',N'R01.1.4 HONORARIOS - CAPACITADOR NACIONAL - PROFESIONAL CON TÍTULO DE MAESTRÍA Y EXPERIENCIA RELACIONADA COMPROBADA, MÍNIMO DE TRES (3) AÑOS',N'PROFESIONAL CON TÍTULO DE MAESTRÍA Y EXPERIENCIA RELACIONADA
COMPROBADA, MÍNIMO DE TRES (3) AÑOS.
SE ACEPTA LA EQUIVALENCIA DEL TÍTULO DE MAESTRÍA POR:
TÍTULO DE ESPECIALIZACIÓN Y TRES (3) AÑOS DE EXPERIENCIA
PROFESIONAL ADICIONAL A LA EXIGIDA, RELACIONADA CON LA FORMACIÓN
A IMPARTIR, SIEMPRE Y CUANDO SE ACREDITE EL TÍTULO PROFESIONAL.',578664,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA01',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (348,10,N'R01.1.5',N'R01.1.5 HONORARIOS - CAPACITADOR NACIONAL - PROFESIONAL CON TÍTULO DE DOCTORADO Y CON EXPERIENCIA RELACIONADA COMPROBADA, MÍNIMO DE TRES (3) AÑOS',N'PROFESIONAL CON TÍTULO DE DOCTORADO Y CON EXPERIENCIA
RELACIONADA COMPROBADA, MÍNIMO DE TRES (3) AÑOS.',710240,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA01',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (349,10,N'R01.2.1',N'R01.2.1 HONORARIOS - CAPACITADOR INTERNACIONAL - TÉCNICO Y/O TECNÓLOGO TITULADO, CON EXPERIENCIA RELACIONADA COMPROBADA MÍNIMO DE CINCO (5) AÑOS',N'TÉCNICO Y/O TECNÓLOGO TITULADO, CON EXPERIENCIA RELACIONADA
COMPROBADA MÍNIMO DE CINCO (5) AÑOS.
SE ACEPTA LA EQUIVALENCIA DEL TÍTULO DE TÉCNICO Y/O TECNÓLOGO
POR:
UN (1) AÑO DE EXPERIENCIA RELACIONADA ADICIONAL A LA SOLICITADA,
SIEMPRE Y CUANDO SE ACREDITE LA TERMINACIÓN Y LA APROBACIÓN DE
LOS ESTUDIOS EN LA RESPECTIVA MODALIDAD.',454521,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA01',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (350,10,N'R01.2.2',N'R01.2.2 HONORARIOS - CAPACITADOR INTERNACIONAL - PROFESIONAL TITULADO CON EXPERIENCIA RELACIONADA COMPROBADA, MÍNIMO DE CINCO (5) AÑOS',N'PROFESIONAL TITULADO CON EXPERIENCIA RELACIONADA COMPROBADA,
MÍNIMO DE CINCO (5) AÑOS.',780552,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA01',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (351,10,N'R01.2.3',N'R01.2.3 HONORARIOS - CAPACITADOR INTERNACIONAL - PROFESIONAL CON TÍTULO DE ESPECIALIZACIÓN Y EXPERIENCIA RELACIONADA COMPROBADA, MÍNIMO DE CINCO (5) AÑOS',N'PROFESIONAL CON TÍTULO DE ESPECIALIZACIÓN Y EXPERIENCIA
RELACIONADA COMPROBADA, MÍNIMO DE CINCO (5) AÑOS.
SE ACEPTA LA EQUIVALENCIA DEL TÍTULO DE ESPECIALIZACIÓN POR:
DOS (2) AÑOS DE EXPERIENCIA PROFESIONAL ADICIONAL A LA EXIGIDA,
RELACIONADA CON LA FORMACIÓN A IMPARTIR, SIEMPRE Y CUANDO SE
ACREDITE EL TÍTULO PROFESIONAL.',917210,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA01',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (352,10,N'R01.2.4',N'R01.2.4 HONORARIOS - CAPACITADOR INTERNACIONAL - PROFESIONAL CON TITULO DE MAESTRIA Y EXPERIENCIA RELACIONADA COMPROBADA, MINIMO DE CINCO (5) AÑOS',N'PROFESIONAL CON TÍTULO DE MAESTRÍA Y EXPERIENCIA RELACIONADA
COMPROBADA, MÍNIMO DE CINCO (5) AÑOS.
SE ACEPTA LA EQUIVALENCIA DEL TÍTULO DE MAESTRÍA POR:
TÍTULO PROFESIONAL + TÍTULO DE ESPECIALIZACIÓN Y TRES (3) AÑOS DE
EXPERIENCIA PROFESIONAL ADICIONAL A LA EXIGIDA, RELACIONADA CON LA
FORMACIÓN A IMPARTIR.',1128779,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA01',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (353,10,N'R01.2.5',N'R01.2.5 HONORARIOS - CAPACITADOR INTERNACIONAL - PROFESIONAL CON TITULO DE DOCTORADO, CON EXPERIENCIA RELACIONADA COMPROBADA, MINIMO DE CINCO (5) AÑOS, AFIN CON EL OBJETIVO DE LA FORMACIÓN',N'PROFESIONAL CON TÍTULO DE DOCTORADO, CON EXPERIENCIA
RELACIONADA COMPROBADA, MÍNIMO DE CINCO (5) AÑOS, AFÍN CON EL
OBJETO DE LA FORMACIÓN.',1636380,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA01',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (354,10,N'R01.3.1.1',N'R01.3.1.1 HONORARIOS LÍDER MUNDIAL Y NACIONAL - LÍDER MUNDIAL',N'PERSONA QUE CUENTA CON RECONOCIMIENTO MUNDIAL POR SU
INFLUENCIA INTERNACIONAL, CON ALTAS CAPACIDADES EN EL ÁREA
DE CONOCIMIENTO DE LA FORMACIÓN A DESARROLLAR, CON
EXPERIENCIA RECONOCIDA EN EL ÁREA TEMÁTICA.
DEBERÁN TENER UN AMPLIO RECONOCIMIENTO EN EL SECTOR
OBJETO DE LA FORMACIÓN Y CERTIFICAR LA EXPERIENCIA LABORAL EN
POR LO MENOS CUATRO (4) PAÍSES DIFERENTES A SU PAÍS DE
NACIMIENTO, DOMINAR MÍNIMO DOS (2) IDIOMAS, INCLUIDO EL
NATIVO. ASÍ MISMO, DEBERÁN ACREDITAR AL MENOS LA
PUBLICACIÓN DE UN LIBRO O CUATRO (4) PUBLICACIONES EN
REVISTAS NACIONALES Y/O INTERNACIONALES, EN CALIDAD DE
AUTOR/COAUTOR O MÍNIMO CINCO (5) PUBLICACIONES EN MEDIOS
DE COMUNICACIÓN EN LAS QUE SE HABLE DE LA EXPERIENCIA DEL
LÍDER MUNDIAL, CON LA TEMÁTICA AFÍN CON EL OBJETO DE LA
FORMACIÓN QUE VA A IMPARTIR. (PUBLICACIONES NO MAYORES A
DOS AÑOS).',26790064,1,0,1,NULL,NULL,1,1,1,0,1,5,N'PA09',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (355,10,N'R01.3.1.2',N'R01.3.1.2 HONORARIOS LÍDER MUNDIAL Y NACIONAL - LÍDER NACIONAL',N'PERSONA QUE CUENTA CON RECONOCIMIENTO NACIONAL POR SU
INFLUENCIA NACIONAL, CON ALTAS CAPACIDADES EN EL ÁREA DE
CONOCIMIENTO DE LA FORMACIÓN A DESARROLLAR, CON
EXPERIENCIA RECONOCIDA EN EL ÁREA TEMÁTICA Y CERTIFICAR LA
EXPERIENCIA MÍNIMA EN 6 EVENTOS. ASÍ MISMO, DEBERÁ
VERIFICARSE EN LOS MEDIOS, PUBLICACIONES REALIZADAS QUE
DESCRIBAN LA EXPERIENCIA Y VIDA DE ESTOS LIDERES NACIONALES,
CON LAS TEMÁTICAS AFINES CON EL OBJETO DE LA FORMACIÓN QUE
VA A IMPARTIR.',11185767,1,0,1,NULL,NULL,1,1,1,0,1,5,N'PA09',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (356,10,N'R02.1',N'R02.1 ALOJAMIENTO, MANUTENCIÓN Y TRANSPORTE LOCAL - CAPACITADOR NACIONAL',N'APLICA PARA TODOS LOS CAPACITADORES NACIONALES,
INDEPENDIENTE DE SU PERFIL Y FORMACIÓN ACADÉMICA.
INCLUYE CAPACITADORES INTERNOS NACIONALES LOS CUALES
ESTARÁN A CARGO DE LA CONTRAPARTIDA EN DINERO DEL
CONVINIENTE.',510102,1,0,1,NULL,NULL,1,1,1,0,1,4,N'PA08',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (357,10,N'R02.2',N'R02.2 ALOJAMIENTO, MANUTENCIÓN Y Y TRANSPORTE LOCAL - CAPACITADOR INTERNACIONAL Y LIDER MUNDIAL Y NACIONAL',N'APLICA PARA TODOS LOS CAPACITADORES INTERNACIONALES,
INDEPENDIENTE DE SU PERFIL Y FORMACIÓN ACADÉMICA.
INCLUYE CAPACITADORES INTERNOS EXTRANJEROS.',722037,1,0,1,NULL,NULL,1,1,1,0,1,4,N'PA08',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (358,10,N'R03.1',N'R03.1 HONORARIOS TRADUCCIÓN SIMULTÁNEA Y ALQUILER DE EQUIPOS NECESARIOS - HONORARIOS PARA TRADUCIÓN DE CONFERENCIA SIMULTÁNEA',N'HONORARIOS PARA TRADUCCIÓN DE
CONFERENCIA SIMULTÁNEA',513268,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA02',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (359,10,N'R03.2',N'R03.2 HONORARIOS TRADUCCIÓN SIMULTÁNEA Y ALQUILER DE EQUIPOS NECESARIOS - ALQUILER DE EQUIPOS',N'ALQUILER DE EQUIPOS',421785,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA02',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (360,10,N'R04',N'R04 TIQUETES AÉREOS, TERRESTRES INTERMUNICIPALES Y/O FLUVIAL',N'SE RECONOCERÁ EL VALOR DE LOS TIQUETES
AÉREOS, TERRESTRES INTERMUNICIPALES Y/O
FLUVIAL DE LOS CAPACITADORES NACIONALES E
INTERNACIONALES Y TRADUCTORES. SE INCLUYEN
LOS CAPACITADORES INTERNOS QUE ESTÉN
PROGRAMADOS PREVIAMENTE DENTRO DE LAS
ACCIONES DE FORMACIÓN LOS CUALES ESTARÁN
A CARGO DE LA CONTRAPARTIDA EN DINERO DEL
CONVINIENTE.',0,1,0,1,NULL,NULL,1,1,1,0,1,5,N'PA05',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (361,10,N'R05.1.1',N'R05.1.1 MATERIAL DE FORMACIÓN - IMPRESO - CARTILLA IMPRESA',N'CARTILLA IMPRESA
(IMPRESIÓN FULL COLOR DE MIN 30 HOJAS TAMAÑO CARTA, PAPEL BOND
DE 75 GRS)
APLICA PARA TODOS LOS EVENTOS DE FORMACIÓN PRESENCIAL, MENOS
FORO Y CONFERENCIA',61234,1,0,1,NULL,NULL,1,1,1,0,1,2,N'PA10',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (362,10,N'R05.1.2',N'R05.1.2 MATERIAL DE FORMACIÓN - IMPRESO - FOLLETO IMPRESO',N'FOLLETO IMPRESO
(IMPRESIÓN FULL COLOR, TAMAÑO OFICIO, DOS CARAS, PAPEL
PROPALCOTE) APLICA ÚNICAMENTE PARA LOS EVENTOS DE FORMACIÓN
PRESENCIAL CONFERENCIA Y FORO',6600,1,0,1,NULL,NULL,1,1,1,0,1,2,N'PA10',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (363,10,N'R05.1.3',N'R05.1.3 MATERIAL DE FORMACIÓN - IMPRESO - LIBRO IMPRESO CON CÓDIGO ISBN',N'LIBRO IMPRESO CON CÓDIGO ISBN
(APLICA PARA LOS EVENTOS DE FORMACIÓN PRESENCIALES CURSO,
DIPLOMADO, SEMINARIO Y TALLER)
DEBE ESTAR JUSTIFICADO SU USO EN LA FORMACIÓN Y DEBE GUARDAR
RELACIÓN CON LA TEMÁTICA DE LA ACCIÓN DE FORMACIÓN.',227239,1,0,1,NULL,NULL,1,1,1,0,1,2,N'PA10',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (364,10,N'R05.2.1',N'R05.2.1 MATERIAL DE FORMACIÓN - DIGITAL - LIBRO ELECTRÓNICO-DIGITAL CON CÓDIGO ISBN',N'LIBRO ELECTRÓNICO-DIGITAL CON CÓDIGO ISBN (NO APLICA PARA
CONFERENCIAS NI FOROS)
DEBE ESTAR JUSTIFICADO SU USO EN LA FORMACIÓN Y DEBE GUARDAR
RELACIÓN CON LA TEMÁTICA DE LA ACCIÓN DE FORMACIÓN.',105789,1,0,1,NULL,NULL,1,1,1,0,1,2,N'PA10',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (365,10,N'R05.3.1',N'R05.3.1 MATERIAL DE FORMACIÓN - DIAGRAMACIÓN - DIAGRAMACIÓN CARTILLA',N'DIAGRAMACIÓN CARTILLA
SERVICIO DE DIAGRAMACIÓN PARA CARTILLA DE 60 PÁGINAS. SE PAGARÁ
SOLO UNA VEZ POR ACCIÓN DE FORMACIÓN.',3126436,1,0,1,NULL,NULL,1,1,1,0,1,5,N'PA05',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (366,10,N'R05.3.2',N'R05.3.2 MATERIAL DE FORMACIÓN - DIAGRAMACIÓN - DIAGRAMACIÓN FOLLETO',N'DIAGRAMACIÓN FOLLETO
SERVICIO DE DIAGRAMACIÓN PARA FOLLETO DE 2 PÁGINAS. SE PAGARÁ
SOLO UNA VEZ POR ACCIÓN DE FORMACIÓN.',104215,1,0,1,NULL,NULL,1,1,1,0,1,2,N'PA10',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (367,10,N'R05.4.1',N'R05.4.1 MATERIAL DE FORMACIÓN - RECURSOS DIDACTICOS - ACCESO A SIMULADORES ONLINE TEMPORALES',N'ACCESO A SIMULADORES ONLINE
TEMPORALES.
DEBE SER ADQUIRIDO EN ENTIDADES
RECONOCIDAS NACIONAL O
INTERNACIONALMENTE.
LA TEMÁTICA DEBE ESTAR
RELACIONADA DIRECTAMENTE CON LA
ACCIÓN DE FORMACIÓN Y DEBE
CORRESPONDER A HORAS PRÁCTICAS. POR ACCIÓN DE FORMACIÓN
PRESENCIAL, 1 ACCESO POR
COMPUTADOR CON
INTERACCIÓN DE 5
BENEFICIARIOS EN CADA
EQUIPO.',219764,1,0,1,NULL,NULL,1,1,1,0,1,2,N'PA10',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (368,10,N'R05.4.2',N'R05.4.2 MATERIAL DE FORMACIÓN - RECURSOS DIDACTICOS - APLICACIONES MULTIMEDIA INTERACTIVAS',N'APLICACIONES MULTIMEDIA
INTERACTIVAS. APLICA SOLO UNA VEZ POR
ACCIÓN DE FORMACIÓN PARA
LAS MODALIDADES
PRESENCIALES Y PAT.',60647,1,0,1,NULL,NULL,1,1,1,0,1,5,N'PA09',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (369,10,N'R05.4.3',N'R05.4.3 MATERIAL DE FORMACIÓN - RECURSOS DIDACTICOS - ACCESO A ENTORNOS EN REALIDAD VIRTUAL O AUMENTADA',N'ACCESO A ENTORNOS DE
REALIDAD VIRTUAL O AUMENTADA. APLICA PARA LOS EVENTOS
DE FORMACIÓN PRESENCIAL
TALLER, CURSO Y DIPLOMADO',0,1,0,1,NULL,NULL,1,1,1,0,1,5,N'PA05',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (370,10,N'R05.4.4',N'R05.4.4 MATERIAL DE FORMACIÓN - RECURSOS DIDACTICOS - ALQUILER DE EQUIPOS PARA REALIDAD VIRTUAL O AUMENTADA',N'ALQUILER DE EQUIPOS PARA
REALIDAD VIRTUAL O AUMENTADA. APLICA PARA LOS EVENTOS
DE FORMACIÓN PRESENCIAL
TALLER, CURSO Y DIPLOMADO',0,1,0,1,NULL,NULL,1,1,1,0,1,5,N'PA05',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (371,10,N'R06',N'R06 INSUMOS PARA LA FORMACIÓN PRACTICA (BIEN CONSUMIBLE UTILIZADO EN EL PROCESO PRODUCTIVO DE OTRO BIEN)',N'INSUMOS:
(BIEN CONSUMIBLE UTILIZADO EN EL PROCESO PRODUCTIVO DE OTRO BIEN)
SE RECONOCERÁ ÚNICAMENTE EN LOS CASOS QUE SEAN REQUERIDOS PARA
LA EJECUCIÓN DE LAS ACCIONES DE FORMACIÓN Y EN LAS CANTIDADES
ESTRICTAMENTE NECESARIAS.
SE RECONOCERÁ EL VALOR DEL GASTO DE ACUERDO CON LA CALIDAD Y
MATERIALES UTILIZADOS EN LA FORMACIÓN.',0,1,0,1,NULL,NULL,1,1,1,0,1,5,N'PA05',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (372,10,N'R07.1.1.1',N'R07.1.1.1 ALQUILER DE SALONES Y/O ESPACIOS - AULAS BÁSICAS (ESPACIOS FÍSICOS EN FINCAS Y TALLERES, INSTITUCIONES BÁSICA Y MEDIA, SALONES COMUNALES.) - HASTA 30 BENEFICIARIOS',N'PARA
FORMACIONES HASTA 30
BENEFICIARIOS. AULAS BÁSICAS
(ESPACIOS FÍSICOS EN FINCAS Y
TALLERES, INSTITUCIONES BÁSICA Y
MEDIA, SALONES COMUNALES)',55125,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA03',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (373,10,N'R07.1.1.2',N'R07.1.1.2 ALQUILER DE SALONES Y/O ESPACIOS - AULAS CONVENCIONALES (INSTITUCIONES DE EDUCACIÓN SUPERIOR) - HASTA 30 BENEFICIARIOS',N'PARA
FORMACIONES HASTA 30
BENEFICIARIOS. AULAS CONVENCIONALES
(INSTITUCIONES DE EDUCACIÓN
SUPERIOR).',202454,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA03',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (374,10,N'R07.1.1.3',N'R07.1.1.3 ALQUILER DE SALONES Y/O ESPACIOS - SALONES, HOTELES, LABORATORIOS, AULAS GASTRONOMÍA, SALONES EMPRESARIALES) - HASTA 30 BENEFICIARIOS',N'PARA
FORMACIONES HASTA 30
BENEFICIARIOS. SALONES HOTELES,
LABORATORIOS, AULAS
GASTRONOMÍA, SALONES
EMPRESARIALES)',402885,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA03',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (375,10,N'R07.1.2.1',N'R07.1.2.1 ALQUILER DE SALONES Y/O ESPACIOS - AULAS BÁSICAS (ESPACIOS FÍSICOS EN FINCAS Y TALLERES, INSTITUCIONES BÁSICA Y MEDIA, SALONES COMUNALES) - ENTRE 31 Y 150 BENEFICIARIOS',N'PARA FORMACIONES ENTRE
31 Y 150 BENEFICIARIOS. AULAS BÁSICAS
(ESPACIOS FÍSICOS EN FINCAS Y
TALLERES, INSTITUCIONES BÁSICA Y
MEDIA, SALONES COMUNALES)',204393,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA03',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (376,10,N'R07.1.2.2',N'R07.1.2.2 ALQUILER DE SALONES Y/O ESPACIOS - AULAS CONVENCIONALES (INSTITUCIONES DE EDUCACIÓN SUPERIOR) PARA FORMACIONES ENTRE 31 Y 150 BENEFICIARIOS',N'PARA FORMACIONES ENTRE
31 Y 150 BENEFICIARIOS. AULAS CONVENCIONALES
(INSTITUCIONES DE EDUCACIÓN
SUPERIOR).',418287,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA03',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (377,10,N'R07.1.2.3',N'R07.1.2.3 ALQUILER DE SALONES Y/O ESPACIOS - SALONES HOTELES, LABORATORIOS, AULAS GASTRONOMIA, SALONES EMPRESARIALES - PARA FORMACIONES ENTRE 31 Y 150 BENEFICIARIOS',N'PARA FORMACIONES ENTRE
31 Y 150 BENEFICIARIOS. SALONES HOTELES,
LABORATORIOS, AULAS
GASTRONOMÍA, SALONES
EMPRESARIALES)',586632,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA03',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (378,10,N'R07.1.3',N'R07.1.3 ALQUILER DE SALONES Y/O ESPACIOS - AUDITORIO - PARA FORMACIONES DE 151 BENEFICIARIOS EN ADELANTE',N'PARA FORMACIONES DE 151
BENEFICIARIOS EN
ADELANTE. AUDITORIO',716410,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA03',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (379,10,N'R07.2.1',N'R07.2.1 ALQUILER DE SALONES Y/O ESPACIOS - AULAS DIGITALES PARA FORMACIÓN PRESENCIAL ASISTIDA POR HERRAMIENTAS TECNOLÓGICAS (INCLUIDOS EQUIPOS Y CONECTIVIDAD)',N'AULAS DIGITALES PARA
FORMACIÓN
PRESENCIAL ASISTIDA
POR HERRAMIENTAS
TECNOLÓGICAS
(INCLUIDOS EQUIPOS
Y CONECTIVIDAD). R07.2.1 VALOR ALQUILER HORA PLATAFORMA
$294 HORA',294,1,0,1,NULL,NULL,1,1,1,0,1,1,N'PA03',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (380,10,N'R07.2.2',N'R07.2.2 ALQUILER DE SALONES Y/O ESPACIOS - AULAS DIGITALES PARA FORMACIÓN PRESENCIAL ASISTIDA POR HERRAMIENTAS TECNOLÓGICAS (INCLUIDOS EQUIPOS Y CONECTIVIDAD)',N'AULAS DIGITALES PARA
FORMACIÓN
PRESENCIAL ASISTIDA
POR HERRAMIENTAS
TECNOLÓGICAS
(INCLUIDOS EQUIPOS
Y CONECTIVIDAD). R07.2.2 VALOR ALQUILER HORA COMPUTADORES O EQUIPOS PARA
USO EXCLUSIVO DE LOS BENEFICIARIOS POR LAS HORAS DE LA
FORMACIÓN
$647 HORA/BENEFICIARIO',647,1,0,1,NULL,NULL,1,1,1,0,1,8,N'PA11',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (381,10,N'R07.2.3',N'R07.2.3 ALQUILER DE SALONES Y/O ESPACIOS - AULAS DIGITALES PARA FORMACIÓN PRESENCIAL ASISTIDA POR HERRAMIENTAS TECNOLÓGICAS (INCLUIDOS EQUIPOS Y CONECTIVIDAD)',N'AULAS DIGITALES PARA
FORMACIÓN
PRESENCIAL ASISTIDA
POR HERRAMIENTAS
TECNOLÓGICAS
(INCLUIDOS EQUIPOS
Y CONECTIVIDAD). R07.2.3 VALOR HORA CONECTIVIDAD POR LAS HORAS DE LA
FORMACIÓN
$664 HORA/BENEFICIARIO',664,1,0,1,NULL,NULL,1,1,1,0,1,8,N'PA11',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (382,10,N'R08',N'R08 EQUIPOS ESPECIALIZADOS PARA PRACTICAS EN LAS ACCIONES DE FORMACIÓN',N'INCLUYE LOS EQUIPOS NECESARIOS PARA LA REALIZACIÓN EXCLUSIVA
DE PRÁCTICAS EN EL DESEMPEÑO DE UNA ACTIVIDAD ESPECÍFICA
CON LA TEMÁTICA DETERMINADA EN LA ACCIÓN DE FORMACIÓN Y
ESTOS DEBEN ESTAR PROGRAMADOS PREVIAMENTE DENTRO DEL
PROYECTO APROBADO. SU RECONOCIMIENTO SE REALIZARÁ DE
ACUERDO CON EL ANÁLISIS DE PRECIOS DE MERCADO PRESENTADO
POR EL CONVINIENTE. (SE RECONOCE SOLO PARA FORMACIÓN
PRESENCIAL)',0,1,0,1,NULL,NULL,1,1,1,0,1,5,N'PA05',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (383,10,N'R09',N'R09: GASTOS DE OPERACIÓN DEL PROYECTO',N'SE CONSIDERAN GASTOS DE OPERACIÓN, AQUELLOS QUE FORMAN PARTE DE LAS ACTIVIDADES TENDIENTES A CUMPLIR
EL OBJETO DE LAS ACCIONES DE FORMACIÓN.',0,0,1,1,NULL,NULL,1,1,1,0,1,5,N'ME01',N'Caso05');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (384,10,N'R09.1',N'R09.1: CUANDO SE TRATE DE PROYECTOS POR VALOR MAYOR DE $200.000.000 EL PORCENTAJE MÁXIMO PARA ESTE RUBRO SERÁ HASTA EL 10% DEL VALOR TOTAL DE LAS ACCIONES DE FORMACIÓN DEL PROYECTO. ',N'R09.1: CUANDO SE TRATE DE PROYECTOS POR VALOR MAYOR DE $200.000.000 EL PORCENTAJE MÁXIMO PARA ESTE RUBRO SERÁ HASTA EL 10% DEL VALOR TOTAL DE LAS ACCIONES DE FORMACIÓN DEL PROYECTO. ',0,0,1,1,NULL,NULL,1,1,1,0,1,20,N'PA15',N'');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (385,10,N'R09.2',N'R09.2: CUANDO SE TRATE DE PROYECTOS POR VALOR MENOR O IGUAL DE $200.000.000 EL PORCENTAJE MÁXIMO PARA ESTE RUBRO SERÁ HASTA EL 16% DEL VALOR TOTAL DE LAS ACCIONES DE FORMACIÓN DEL PROYECTO.',N'R09.2: CUANDO SE TRATE DE PROYECTOS POR VALOR MENOR O IGUAL DE $200.000.000 EL PORCENTAJE MÁXIMO PARA ESTE RUBRO SERÁ HASTA EL 16% DEL VALOR TOTAL DE LAS ACCIONES DE FORMACIÓN DEL PROYECTO.',0,0,1,1,NULL,NULL,1,1,1,0,1,20,N'PA15',N'');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (386,10,N'R010.1',N'R010.1 FORMACIÓN VIRTUAL - CURSO 20 HORAS',N'R010.1 CURSO 20 HORAS. SE PRESUPUESTA DE MANERA GLOBAL POR PERSONA. INCLUYE
TODOS LOS COSTOS DE VIRTUALIZACIÓN E IMPARTICIÓN
(COSTOS DE PLATAFORMA, HONORARIOS DE CAPACITADORES
NACIONALES O INTERNACIONALES, MATERIAL DE FORMACIÓN Y
AYUDAS PROPIAS DE ESTA MODALIDAD)',647766,1,0,1,NULL,NULL,1,1,1,0,1,3,N'PA07',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (387,10,N'R010.2',N'R010.2 FORMACIÓN VIRTUAL - CURSO 40 HORAS',N'R010.2 CURSO 40 HORAS. SE PRESUPUESTA DE MANERA GLOBAL POR PERSONA. INCLUYE
TODOS LOS COSTOS DE VIRTUALIZACIÓN E IMPARTICIÓN
(COSTOS DE PLATAFORMA, HONORARIOS DE CAPACITADORES
NACIONALES O INTERNACIONALES, MATERIAL DE FORMACIÓN Y
AYUDAS PROPIAS DE ESTA MODALIDAD)',1307519,1,0,1,NULL,NULL,1,1,1,0,1,3,N'PA07',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (388,10,N'R010.3',N'R010.3 FORMACIÓN VIRTUAL - DIPLOMADO 80 HORAS',N'R010.3 DIPLOMADO 80 HORAS. SE PRESUPUESTA DE MANERA GLOBAL POR PERSONA. INCLUYE
TODOS LOS COSTOS DE VIRTUALIZACIÓN E IMPARTICIÓN
(COSTOS DE PLATAFORMA, HONORARIOS DE CAPACITADORES
NACIONALES O INTERNACIONALES, MATERIAL DE FORMACIÓN Y
AYUDAS PROPIAS DE ESTA MODALIDAD)',2716498,1,0,1,NULL,NULL,1,1,1,0,1,3,N'PA07',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (389,10,N'R010.4',N'R010.4 FORMACIÓN VIRTUAL - DIPLOMADO 120 HORAS',N'R010.4 DIPLOMADO 120 HORAS. SE PRESUPUESTA DE MANERA GLOBAL POR PERSONA. INCLUYE
TODOS LOS COSTOS DE VIRTUALIZACIÓN E IMPARTICIÓN
(COSTOS DE PLATAFORMA, HONORARIOS DE CAPACITADORES
NACIONALES O INTERNACIONALES, MATERIAL DE FORMACIÓN Y
AYUDAS PROPIAS DE ESTA MODALIDAD)',3517547,1,0,1,NULL,NULL,1,1,1,0,1,3,N'PA07',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (390,10,N'R011',N'R011 HONORARIOS CAPACITADORES INTERNOS',N'PARA ESTE RUBRO SE DEBERÁ TENER EN CUENTA LOS
PERFILES DESCRITOS EN EL ARTÍCULO 2º DE LA PRESENTE RESOLUCIÓN, APLICABLES PARA CAPACITADORES
NACIONALES O INTERNACIONALES. SE DEBERÁ PRESENTAR ÚNICAMENTE COMO CONTRAPARTIDA EN ESPECIE.
UNIDAD DE MEDIDA: HORA DE FORMACIÓN. PARA LOS CAPACITADORES INTERNOS, EL RUBRO “ALOJAMIENTO, MANUTENCIÓN Y TRANSPORTE LOCAL Y/O
INTERMUNICIPAL”, SE RECONOCERÁ EL DÍA ANTES Y/O EL DÍA DESPUÉS DE LA JORNADA DE FORMACIÓN CON CARGO A
LOS RECURSOS DE CONTRAPARTIDA EN DINERO DEL CONVINIENTE CONFORME A LO SEÑALADO EN RUBRO R02 Y A LA
NOTA 9 DE ESTA RESOLUCIÓN.',0,1,0,1,NULL,NULL,1,1,1,0,1,5,N'PA05',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (391,10,N'R012.1',N'R012.1 PROMOCIÓN Y DIVULGACIÓN DE LOS EVENTOS DE FORMACIÓN - BACKING DIGITAL',N'BACKING DIGITAL
(APLICA PARA LOS EVENTOS DE FORMACIÓN SEMINARIO, CONFERENCIA
Y/O FORO PRESENCIAL O HIBRIDO) SERÁ DIGITAL, SE RECONOCE VALOR
DÍA DEL VIDEO BEAM.',396753,1,0,1,NULL,NULL,1,1,1,0,1,4,N'PA13',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (392,10,N'R012.2',N'R012.2 PROMOCIÓN Y DIVULGACIÓN DELOS EVENTOS DE FORMACIÓN - EDICIÓN DEL VIDEO DE (2 MINUTOS)',N'EDICIÓN DEL VIDEO DE 2 MINUTOS',471741,1,0,1,NULL,NULL,1,1,1,0,1,5,N'PA05',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (393,10,N'R012.3',N'R012.3 PROMOCIÓN Y DIVULGACIÓN DE LOS EVENTOS DE FORMACIÓN - EDICIÓN DEL VIDEO DE (4 MINUTOS)',N'EDICIÓN DEL VIDEO DE 4 MINUTOS',943483,1,0,1,NULL,NULL,1,1,1,0,1,2,N'PA10',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (394,10,N'R012.4',N'R012.4 PROMOCIÓN Y DIVULGACIÓN DE LOS EVENTOS DE FORMACIÓN - EDICIÓN PODCAST ( 5 MINUTOS)',N'EDICIÓN PODCAST 5 MINUTOS',622477,1,0,1,NULL,NULL,1,1,1,0,1,2,N'PA10',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (395,10,N'R012.5',N'R012.5 PROMOCIÓN Y DIVULGACIÓN DE LOS EVENTOS DE FORMACIÓN - EDICIÓN PODCAST ( 10 MINUTOS)',N'EDICIÓN PODCAST 10 MINUTOS',1244954,1,0,1,NULL,NULL,1,1,1,0,1,2,N'PA10',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (396,10,N'R012.6',N'R012.6 PROMOCIÓN Y DIVULGACIÓN DE LOS EVENTOS DE FORMACIÓN - EDICIÓN PODCAST ( 15 MINUTOS)',N'EDICIÓN PODCAST 15 MINUTOS',1867430,1,0,1,NULL,NULL,1,1,1,0,1,2,N'PA10',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (397,10,N'R012.7',N'R012.7 PROMOCIÓN Y DIVULGACIÓN DE LOS EVENTOS DE FORMACIÓN - DISEÑO E IMPRESIÓN DE INFOGRAFIA',N'DISEÑO E IMPRESIÓN DE INFOGRAFÍA',290328,1,0,1,NULL,NULL,1,1,1,0,1,5,N'PA09',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (398,10,N'R012.8',N'R012.8 PROMOCIÓN Y DIVULGACIÓN DE LOS EVENTOS DE FORMACIÓN - DIAGRAMACIÓN DE ARTÍCULO, MÁXIMO 20 PAGINAS',N'DIAGRAMACIÓN DE ARTÍCULO, MÁXIMO 20 PAGINAS',52108,1,0,1,NULL,NULL,1,1,1,0,1,2,N'PA09',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (399,10,N'R013',N'R013 PÓLIZAS DE SEGURO.  ',N'GARANTÍAS REQUERIDAS PARA LA EJECUCIÓN DEL PROYECTO CON CARGO A
LA CONTRAPARTIDA EN DINERO DEL CONVINIENTE.',0,1,0,1,NULL,NULL,1,1,1,0,1,5,N'PA05',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (400,10,N'R014',N'R014 ALIMENTACIÓN Y TRANSPORTE PARA BENEFICIARIOS DEL SECTOR AGROPECUARIO.  ',N'ALIMENTACIÓN Y TRANSPORTE PARA BENEFICIARIOS DEL SECTOR AGROPECUARIO. DE
CONFORMIDAD CON LO DISPUESTO EN EL PARÁGRAFO 1 DEL ARTÍCULO 19 DEL ACUERDO 0007 DE 2021, “PARA EL
CASO DE PROYECTOS CUYOS BENEFICIARIOS DE LAS ACCIONES DE FORMACIÓN SEAN PRODUCTORES DEL SECTOR
AGROPECUARIO, PODRÁN INCLUIR EL RUBRO MANUTENCIÓN (ALIMENTACIÓN) Y EL RUBRO TRANSPORTE LOCAL, PARA LOS
BENEFICIARIOS DE LA CAPACITACIÓN. ESTOS RUBROS DEBEN ESTAR A CARGO DE LA CONTRAPARTIDA DEL CONVINIENTE.
EN NINGÚN CASO EL VALOR DE ESTE RUBRO PODRÁ SUPERAR EL CINCUENTA POR CIENTO (50%) DEL VALOR TOTAL DE LA
CONTRAPARTIDA DE LA ACCIÓN DE FORMACIÓN.”',0,1,0,1,NULL,NULL,1,1,1,0,1,5,N'PA05',N'PRESENCIAL,PRESENCIAL HÍBRIDA,PAT,VIRTUAL');
INSERT INTO RUBRO (RUBROID,CONVOCATORIAIDRUBRO,RUBROCODIGO,RUBRONOMBRE,RUBRODESCRIPCION,RUBROTOPE,RUBROAF,RUBROPROYECTO,TIPOUNIDADID,RUBROCANTIDADBENEF,RUBROPORCENTAJE,FORMULAASOCIADA,RUBROPERFILUT,RUBROACTIVO,RUBROTRANSFERENCIA,RUBROINTERNACIONAL,RUBROCASO,RUBROPAQUETE,RUBROMODALIDAD) VALUES (401,10,N'R015',N'R015: TRANSFERENCIA DE CONOCIMIENTO Y TECNOLOGÍA',N'TRANSFERENCIA DE CONOCIMIENTO Y TECNOLOGÍA. SE ENTIENDE COMO EL PROCESO DE APROPIACIÓN
E INCORPORACIÓN DE CONOCIMIENTOS, TECNOLOGÍAS Y DE NUEVAS PRÁCTICAS, GENERADAS EN LOS PROYECTOS
EJECUTADOS EN EL MARCO DEL PROGRAMA DE FORMACIÓN CONTINUA ESPECIALIZADA, COMO EJERCICIO DE
EXTENSIÓN DE LA ACTIVIDAD FORMATIVA DE CADA UNO DE LOS CONVENIOS SUSCRITOS, EN FAVOR DE LA COMUNIDAD
SENA, AGENTES DEL SISTEMA NACIONAL DE CIENCIA, TECNOLOGÍA E INNOVACIÓN Y DEL PERSONAL QUE DEFINA LA ENTIDAD, QUIENES ACTUARÁN COMO RECEPTORES, GENERADORES Y SOCIALIZADORES DE LAS NUEVAS PRÁCTICAS Y CONOCIMIENTOS.
EL PORCENTAJE DE TRANSFERENCIA DE CONOCIMIENTO ESTARÁ A CARGO DE LA CONTRAPARTIDA EN DINERO DEL
CONVINIENTE Y SE ESTABLECERÁ SOBRE EL VALOR TOTAL DE LAS ACCIONES DE FORMACIÓN DEL PROYECTO, CONFORME
LO SEÑALA EL NUMERAL 15 DEL ARTÍCULO 19 DEL ACUERDO 007 DE 2021 Y LAS CONDICIONES QUE SE FIJEN EN EL
RESPECTIVO PLIEGO DE LA CONVOCATORIA.',0,0,1,1,NULL,NULL,1,1,1,1,1,5,N'ME01',N'Caso05');

COMMIT;
